### ISSUE TITLE
Basic Map Members Page UI

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#100]
# 權限設定
https://docs.google.com/document/d/1Tpebb1ZkfcC4iv1CCFe_5ENBImf2qijFyEZ2NWE3clg/

Map owner add members into a map
  - by username 
  - by email
  - by link: public link (不用擔心 expire 的問題，不是發邀請信) ：Login members 加入 map
  - on dashboard
  - on Map editor

- Dashboard display 要區分 map owner 與 map contributor 

# UI
基本要求頁面：
1. Dashboard 上加入 contributor 的流程
2. Map Editor 上
  - 加入 contributor 的流程
  - contributor 主動 join map
3. 預設 public

進階頁面：
- 不同權限的人看到的 map 畫面，與權限告知
  - map owner: map toolbar, inbox, 操作 map editor, 加卡
  - contributor: view map, 加卡
  - login guest: 看不到 inbox,  join map 選項，可以 view map
  - not login guest: 看不到 inbox，有 join map 選項，但是任何操作要求 log in

# 預計 implement sprint:
7/4-7/17

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1015023

**Comment by aelcenganda** [comment]
update 權限設計文檔

**Comment by aelcenganda** [comment]
Verified
