### ISSUE TITLE
全站操作行為 UI 界定

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#101]
sense_tool 操作設定
https://docs.google.com/document/d/1ydHOMmLcD9lW-5_ihg8DF9NIYYhR2XTX6HZjKgL74fs/edit

基礎：
- [x] **Box List 操作：拖拉、select box item**
- [x] map toolbar: tool tip、context menu ( 選取才會出現的）
- [x] open box ：用 btn 開，缺圖 （現在是用雙擊開）

進階定義
（- 拖拉：拖的時候中間的圖）
（- Copy and Paste）
（- batch tagging： 現在有操作行為，沒有 inspector 的圖，先暫時不做，因為不確定 multi-select 的需求）

需要有 flow 的 wireframe

# UI

## Toolbar
文字提示區域
https://zpl.io/VQYQRv5

https://zpl.io/2pOx3Nj
對應 Icon 說明
https://docs.google.com/document/d/1ydHOMmLcD9lW-5_ihg8DF9NIYYhR2XTX6HZjKgL74fs/edit
對應情境說明（操作手冊）
https://www.figma.com/file/LXTOm22zs67LAP5mBOawuqT6/icon_figma
icon file

icon svg files
https://drive.google.com/drive/folders/1L-clBKwCsYr8Z67hrMZZZsgzeexixRhv?usp=sharing

## Box List
Box-list
https://zpl.io/25qApKe

Box-list 加卡片
https://zpl.io/2GQWA99

Box-list 移出卡片
https://zpl.io/2ZJnDy1

Bach tag
https://zpl.io/bWYdX4n

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1014887

**Comment by Kanailly** [comment]
所以這裡是需要把文件裡面的描述，按照情形（物件）產出流程圖嗎？

**Comment by aelcenganda** [comment]
@Kanailly 麻煩凱蘭先把 open box btn 和 Box List 拖拉、select box item 先貼到外面跟工程師確認可行性。

**Comment by Kanailly** [comment]
打開figma按鍵盤Ｃ，就會叫出comment。
或是點左上方toolbar最右邊那個（Ｔ旁邊的那個）icon，叫出comment。

**Comment by aelcenganda** [comment]
最後決定：Box list 不做拖拉，也不做 select，用 hover 過去 eject card from box list。 UI 見 https://github.com/SenseTW/sensetw/issues/136
