### ISSUE TITLE
PM：Design Filter/Search behaviour

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#103]
New Spec:
https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1242670/detail

---- 舊版------
Inbox
Map
Dashboard

# Job Story
- When: I am adding cards into map
- I want to: find related cards by keywords
- So that: I can add supportive information on the map

for Inbox filter
- filter by tag, said by who, stakeholders, (source?)
- 想要可以 double filter (像是 GitHub、hypothesis，可以 filter 一次 tag 之後再 filter annotator 之類的)

## Out of Scope
- elastic search

## UI 設計、操作設計
1. 輸入框
  - 輸入文字
  - 字首相同的 tag, said by whom, stakeholders
  - 選取
  - 顯示 filter 結果

2. 直接點選卡片上的 tag 就可以 filter （待討論）

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1015341

**Comment by aelcenganda** [comment]
![2018-06-11 09 54 31](https://user-images.githubusercontent.com/9480974/41211872-dda51af8-6d6c-11e8-9e59-64d283ed243b.png)
根據不同性質的交叉 filt

**Comment by aelcenganda** [comment]
@pm5 想問你可以 filter 再 filter 嗎？

例如：
有指定欄位的：
1. tag:托育政策 stakeholder:內政部
3. tag:托育政策 tag:居家醫療
未指定欄位
2. 托育政策、居家醫療

**Comment by pm5** [comment]
You can have multiple filters so longs as them have well-defined AND and OR behaviour.

**Comment by aelcenganda** [comment]
Spec 開在新的 productboard 上
