### ISSUE TITLE
Basic Account Page UI

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#108]
目前只做重設密碼，從 Top Navigator 連入

# Form Fields
顯示：
username
輸入框：
1. old password
2. new password
3. Confirm new password

# UI
https://zpl.io/aB5RBmK
噴錯資訊
https://zpl.io/blpDjrG

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1011959

**Comment by Kanailly** [comment]
頁面連結updated。

**Comment by aelcenganda** [comment]
@Kanailly 
1. 想問是只要打開就看得到 change password 嗎？另外 update password 拼錯了。
2. 我本來沒有想讓使用者改註冊 email，而是想要讓使用者可以選擇要不要公開他的 email。

@pm5 想問你固定 username ，讓使用者可以改 email 會很麻煩嗎？

**Comment by pm5** [comment]
> 想問你固定 username ，讓使用者可以改 email 會很麻煩嗎？

It should be straight forward.

**Comment by Kanailly** [comment]
@aelcenganda  
所以現在是～ 不管能不能讓他改email都要有選項讓他能決定要不要公開email嗎？
那有要讓他改email嗎？

**Comment by aelcenganda** [comment]
@Kanailly @pm5 那先不要讓他改 email，也先不要讓他可以選要不要公開 email。 Starting from minimal features.

**Comment by Kanailly** [comment]
ok 圖已改
