### ISSUE TITLE
Require 欄位錯誤訊息

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#110]
# Job Story
When: I create a new card
I want to: the key information I type in show on Inbox and Map
So that: I want create an empty card or a card looking blank in Inbox and on Map

# Success Criteria:
1. 標注 Required 欄位
- Card: Card Summary
- Box: Box title
2. Required 欄位空白則無法創建卡片，噴錯誤訊息：
Card summary is required to create a card.
Box title is required to create a box.

# UI

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1038139

**Comment by caasi** [comment]
要更動的地方大概在：

* https://github.com/SenseTW/sensetw/tree/master/sensemap/src/components/CardContent
* https://github.com/SenseTW/sensetw/tree/master/sensemap/src/components/BoxContent
* https://github.com/SenseTW/sensetw/tree/master/sensemap/src/components/DashboardPage/MapContent

這專案已經裝了不綁框架的 [validator](https://www.npmjs.com/package/validator) ，可以繼續用。

**Comment by hychen** [comment]
這我想討論一下，覺得 card summary, box title 都空白，自己覺得比較好用，因為當下不一定想到要寫什麼，但就是要擺個東西在那邊。

**Comment by Kanailly** [comment]
這邊我沒意見。
參考cardsorting的case，對於協助使用者分堆資料的這個時候並不需要強烈要求他下些什麼就是了。

**Comment by aelcenganda** [comment]
我這邊主要是因為當時 inbox 創了太多空白卡了，很可怕。尤其是 hypothesis 過來沒有把 quote 複製一段放到 summary 的話會有一堆空白卡片在 inbox。我同意 box 可以先不要有 title。但是卡片是先放一張空白在那邊再加內容嗎？還是會先有 description？我是怕使用者創建完太多只有 description 的卡片後，發現 map 上一片空白。

**Comment by hychen** [comment]
per discussing with ael, 要將 add new card, add new box 的行為改成直接在 map 上出現比較直覺，明天我會想跟大家討論一下 inbox 跟 map 之間的關係跟動線。

**Comment by Kanailly** [comment]
好喔。不過這裡說一下，覺得有幾個項目扯在一起了。 現在 tool bar 的那個issue為關掉不是因為icon沒畫完，而是卡在操作行為手冊的內容修訂。「全站操作行為 UI 界定」這個issue的內容是原本說要做“拖拉”，但是後來拖拉不做改成用hover出現btn去eject，於是eject card又出現了「Eject a card from Box List UI」這個issue。 
我是覺得既然要討論，那勢必全站操作手冊就又會改，不如明天討論出個決議再來弄。
然後我記得當時把編輯放在inspector有它討論的歷史脈絡，一來是無法直接像realtimeboard那樣直接在物件上編輯（工程實作上的耗費考量的樣子）另外是考量當時的開發時程，所以最後採用先在inspector編輯的方式。 明天要討論的話，應該一起討論下這個版本要實作的時程，還有人力時間配置的規劃，這樣介面上規劃的操作可行的選項會有差。

**Comment by aelcenganda** [comment]
因為覺得使用者有創見空白卡片的需求，之前主要是避免使用者手笨開了太多張空白卡片，但之後新增卡片的使用者卡片如果做好，應該就沒有這個問題。決議先不做 required 欄位。
