### ISSUE TITLE
Set Password (Account Page)

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#111]
# 前提

* 要有 user 功能才能開始做 https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/951467/detail

# 2. 
when: 當我已 log in 
want: 想要更新密碼
so that: 可以到https://sensetw.productboard.com/feature-board/152244-feature-organization/features/1011959/detail 改密碼

# UI
Update information btn inactive
Hide 頭像 inactive

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1012464

**Comment by aelcenganda** [comment]
@pm5 這個應該是放錯 sprint 了，account page 都還沒做就要你做 set password。你同意的話，我就移到下個 sprint。

Forget password，之前的決定是現在先 forget password 統一寄信到 hello@sense.tw，下個 sprint 要不要改再討論
https://github.com/SenseTW/sensetw/issues/126

**Comment by pm5** [comment]
okay

**Comment by caasi** [comment]
Settings 連結在右上角的選單中：

![2018-07-06 03 57 56](https://user-images.githubusercontent.com/1164470/42345128-f71fcae2-80d0-11e8-9413-c611386161cb.png)

整頁長這樣：

![2018-07-06 03 58 08](https://user-images.githubusercontent.com/1164470/42345138-00a44dcc-80d1-11e8-99ab-b14d821d0ce9.png)

輸入值不合法時：

![2018-07-06 03 58 26](https://user-images.githubusercontent.com/1164470/42345152-07ee8e9e-80d1-11e8-9f3f-91a34943698d.png)

輸入值合法時輸入值合法時：

![2018-07-06 03 58 43](https://user-images.githubusercontent.com/1164470/42345160-0dfd6972-80d1-11e8-8674-487d79eef1e2.png)

**Comment by caasi** [comment]
對了密碼可以不要有位數上限嗎？有些人慣用的密碼就大於 16 位。
