### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#112]
# Job Story
When I first visit sense.tw
I want to know what sense.tw can help me to accomplish
so that I can decide whether to sign up

# Success Criteria
- 註冊/登入 btn
- sense.tw 介紹
- 工具 scenario 介紹
- 協作區連結： beta.hackfoldr.org/sense-tw

# 文字草稿
https://hackmd.io/ivc-JOBzQEWs4SUtLlDF3A

# UI
- 繼續使用 strikingly，
https://www.strikingly.com/s/sites/11743708/edit

## customized domain issue: 找 Yen-Wen
方案一：
網域用 about.sense.tw
方案二：
sense.tw 是 landing page
app.sense.tw 是 map 啊
[X] 方案三：workaround
沒有 log-in 就 redirect 到 about

## UI elements 
For check the Font size / color on tool objects
https://zpl.io/2EAlnRD 
Objects elements
https://drive.google.com/drive/folders/1mkhtI_4PdJUiQvFZm39KPP14Nr-czny2?usp=sharing

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1018113

**Comment by aelcenganda** [comment]
做好囉！！
https://about.sense.tw/
