### ISSUE TITLE
Help page

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#113]
# Job Story
When I have problems using sense.tw
I want to know how to operate or ask for service support
So that I can continue using sense.tw

# Success Criteria
- support email: hello@sense.tw 
- Link from Navigator
- cheatsheet for map editor and annotation
- easy to understand without further instruction
- introduction of toolbar icon, inbox, inspector

# To do:
ael: 介紹架構
KL: 引導操作細節

# 可能形式： 
- Google Doc (v) 
- modal 跳出（preferred）
- 另開分頁

# Out of scope
- instant message support
- 如何使用工具的長篇或是圖文並茂介紹放在新手教學

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1018109

**Comment by aelcenganda** [comment]
先把架構列在這邊：
https://hackmd.io/kX5W5jnXSTGt0a0CajoMcA?both

**Comment by aelcenganda** [comment]
先做在 GitBook 上：
help.sense.tw

**Comment by aelcenganda** [comment]
還差總架構圖、常見問題，

但可以請 @caasi 先幫忙把 help page 連到 navigation bar 的 "?" 了嗎 
https://help.sense.tw/
