### ISSUE TITLE
Add annotated doc/web from Map to via.sense.tw by btn

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#114]
# Job Story:
- When I am using map editor
- I want to create annotated cards on sources
- so that I can add annotated cards in inbox

# UI
https://app.zeplin.io/project/5ae1980f28546a5bbf985063/screen/5b215df14daaca5228e44b77?

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1038154

**Comment by aelcenganda** [comment]
Verified
