### ISSUE TITLE
Show map link

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#115]
# Success criteria
- unique map url
- show map url
  - when Map Editor is open
  - share btn on Dashboard 
https://sensetw.productboard.com/feature-board/152244-feature-organization/features/975261/detail

# Next sprint
- View only for non-map-owner

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/895090

**Comment by aelcenganda** [comment]
Verified: url

差 share btn 要 copy 到剪貼簿

**Comment by aelcenganda** [comment]
不需要 share copy link, share btn disabled
