### ISSUE TITLE
Hypothesis Client 頁面隱藏部分功能

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#116]
為了 Hypothesis integration，要把連到 hypothesis，或是我們沒有要接的功能隱藏掉。

https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1012085/detail

要導回 map，關掉除了註記跟回應以外 hypothesis 的功能:

1. 隱藏 Page Note
3. 隱藏分享按鈕
4. 隱藏個別 annotation  的權限設定選單。 (預設 in that group, 非 only me)
5. default 不打開 sidebar。
6. 隱藏 reply to comment
7. 隱藏 account setting，只能 log out
8. logo 連回 dashboard
9. （Group 裡關掉 public）。

# UI:
https://www.figma.com/file/CblZ9n4CV1gVnLs4ZIgNljwL/Hypothesis-client-%E9%A0%81%E4%BF%AE%E6%94%B9?node-id=3%3A0

https://www.figma.com/file/CblZ9n4CV1gVnLs4ZIgNljwL/Hypothesis-client-%E9%A0%81%E4%BF%AE%E6%94%B9

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1038166

**Comment by aelcenganda** [comment]
@caasi Hypothesis Client 要隱藏什麼已經標好了，就麻煩你直接隱藏和加 button。

**Comment by caasi** [comment]
Check https://github.com/SenseTW/client/commit/79272a8407185640e61acb39193cb8a05965d2a1
