### ISSUE TITLE
UI: New Map Editor Layout: 圖形化 toolbar

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#118]
https://app.zeplin.io/project/5ae1980f28546a5bbf985063/screen/5b0af73ad2155a4e2c806337

pm5: 怎麼把七個按鈕變成四個按鈕？

# UI
https://zpl.io/2pOx3Nj
對應 Icon 說明
https://docs.google.com/document/d/1ydHOMmLcD9lW-5_ihg8DF9NIYYhR2XTX6HZjKgL74fs/edit
對應情境說明（操作手冊）
https://www.figma.com/file/LXTOm22zs67LAP5mBOawuqT6/icon_figma
icon file
###### icon svg files
https://drive.google.com/drive/folders/1L-clBKwCsYr8Z67hrMZZZsgzeexixRhv?usp=sharing

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1038165

**Comment by aelcenganda** [comment]
Verified

**Comment by aelcenganda** [comment]
icon 已經給卡西沒問題了
