### ISSUE TITLE
GraphQL backend

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#119]
Build a basic backend to support map functions, and replace Graphcool.

# Success Criteria

* Replace all Graphcool API functions that are used by map app
* Deploy to api.sense.tw

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1049039

**Comment by pm5** [comment]
Closed by 4bb88dd7ef47d07a275536d279aeba067338facc
