### ISSUE TITLE
Card type assign 顏色：Q, A, Box, Note, Normal

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#12]
Q, A, Box, Note, Normal
顏色固定五種
（未來才需要改顏色）
https://zpl.io/V189PMX

（Type 對應到 color，color 對應到議題分析表的欄位。）

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/902243

**Comment by aelcenganda** [comment]
Card type 不是 feature，直接合併到新增和修改卡片的 feature 裡。
