### ISSUE TITLE
Replace Hypothesis API backend

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#120]
重寫 Hypothesis REST API，用 sensemap 資料庫取代 Hypothesis backend。

# Prerequisites

* https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1049039/detail

# Success Criteria

* Client 可以取得 API endpoint，測試 OAuth 2.0 登入（假 token）
* Deploy

# Out of Scope

* Annotation 操作、group 操作（在其它 issue）

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1049093

**Comment by pm5** [comment]
Closed by 6a6b3dbc6a806eb73d7e00c79998eb3bdd5999dc
