### ISSUE TITLE
Forget Password +註冊驗證 email

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#126]
# Job Story

1. 
when: 當我忘記密碼時
want: 我想在 log in 頁面 https://sensetw.productboard.com/feature-board/152244-feature-organization/features/951393/detail request ti 重設密碼 （https://github.com/SenseTW/sensetw/issues/88）
so that: 可以改密碼

# 目前狀態
Forget password linked to mail to hello@sense.tw

## Success Criteria:
- 使用者可以在 log in page 忘記密碼時重設密碼
- 寄 email 重設密碼（擇一）：
  1. 系統直接給亂數新密碼
  2. activate link 重新設定新密碼

## UI
Forget Password 
https://zpl.io/2pdD5Jr

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1038241

**Comment by pm5** [comment]
- [ ] Reset password token generator for activation link & db & verify
- [ ] Reset password pages
- [ ] Reset password code
- [ ] Email reset password letter
- [ ] Test & documentation

**Comment by pm5** [comment]
https://forgetpassword.staging.sense.tw/ 封測中。

**Comment by aelcenganda** [comment]
幾個回饋：
1. 寄 email 能不能用 hello 之外另一個 email？例如 no_reply@sense.tw、support@sense.tw，然後寄信人名稱改為 sense.tw

2. email 內文:

Forgot your password? Let's reset your password at: "reset link"

If you don’t want to change it, just ignore this email. Your password will stay the same.
If you have more questions, send us a note at hello@sense.tw . We’d love to help!

3.  成功 reset password:
Your password has been successfully reset. LOG IN now

**Comment by pm5** [comment]
Finished at #261

**Comment by aelcenganda** [comment]
我用我的帳號 reset password

error: relation "reset_password_token" does not exist
    at Connection.parseE (/workspace/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (/workspace/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (/workspace/node_modules/pg/lib/connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)

**Comment by aelcenganda** [comment]
再加上 unit test

**Comment by pm5** [comment]
修好了
