### ISSUE TITLE
Map Toolbar v.2: icon

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#132]
# Job Story
When: 我在 Map 上要作圖的時候
I want to: 我會想要有個工具列的按鈕可以執行所有動作
So that 我可以把分析架構做出來

# Success Criteria
1. 取代目前的文字選單
2. 滑過 icon 有顯示英文 tootips
3. 常駐選單+浮動選單
4.  根據 selection 的物件，按鈕 disabled and activate：例如選取兩個物件才能連線
5. Scrolling canvas 的時候不會消失，工具列常駐畫面正上方

# Out of Scope

# UI （ Not completed yet）
https://github.com/SenseTW/sensetw/issues/118

對應 Icon 說明
https://zpl.io/2pOx3Nj

對應情境說明（操作手冊）
https://docs.google.com/document/d/1ydHOMmLcD9lW-5_ihg8DF9NIYYhR2XTX6HZjKgL74fs/edit

icon file
https://www.figma.com/file/LXTOm22zs67LAP5mBOawuqT6/icon_figma

icon svg files
https://drive.google.com/drive/folders/1L-clBKwCsYr8Z67hrMZZZsgzeexixRhv?usp=sharing

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1074766

**Comment by aelcenganda** [comment]
需要 hide unbox 這個選項

**Comment by caasi** [comment]
Box 外：

![2018-07-12 19 10 25](https://user-images.githubusercontent.com/1164470/42629900-8b950710-8607-11e8-9322-3173feaa7f7e.png)

Box 內：

![2018-07-12 19 11 16](https://user-images.githubusercontent.com/1164470/42629899-8b658012-8607-11e8-8505-66ce5e57b221.png)

多選：

![2018-07-12 19 11 40](https://user-images.githubusercontent.com/1164470/42629898-8b300fe0-8607-11e8-8947-56d9c5b8c758.png)

等 https://icon-menu.staging.sense.tw/ rebuild 後就能看見。

**Comment by aelcenganda** [comment]
@caasi 需要 hide 「batch tagging」、「Copy」、「Unbox」這三個 icon。

其他規則：
 Open Box 只限於選取一個 Box 時使用，多選的話 disabled

@Kanailly 跟你確認一下，應該可以 multi select 然後「刪除」。目前是 multi-select 後只會刪除被選取的第一個物件

**Comment by Kanailly** [comment]
預期是multi-select案刪除就是都刪掉被選取的項目。目前是 multi-select 後只會刪除被選取的第一個物件，這是應該bug吧
但一直都有功能建置跟預期版本的落差。目前的icon可以對應現行的右邊操作list。

**Comment by caasi** [comment]
現在 multi-select 時無法刪除，我想新問題是「要不要加上多選刪除」

![2018-07-16 16 19 09](https://user-images.githubusercontent.com/1164470/42748814-126eab88-8914-11e8-89c2-b2fd4a3aea87.png)

**Comment by caasi** [comment]
選 box + card 時會出現刪除功能，希望能在 #147 討論一下 unbox 和 delete 是不是同一件事。

![2018-07-16 16 28 26](https://user-images.githubusercontent.com/1164470/42749176-718ffb2a-8915-11e8-8319-78761e2bc8ce.png)

**Comment by aelcenganda** [comment]
剩 UI 定義 unbox、 delete box 操作設定，另開 issue 處理：
https://github.com/SenseTW/sensetw/issues/149
