### ISSUE TITLE
全局觀 UI study and design

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#134]
# job story
When 我想要拉議題架構時
I want to 有全局觀
So that 我可以：
- 看到全部整體架構或是局部放大的架構
- 可以在看到比較完整架構的狀況下連線、拖曳卡片、grouping，或者是點開看 details
- 移動放卡片的地方

# 操作定義：
1. 整頁模式：單鍵切換、hot key 切換
2. 縮小到固定倍率改 layout
2. selection on card and box in 整頁模式
3. Hover to show card summary and box list
4. Don't open inspector 因為太佔空間
5. 容許 toolbar 操作：連線、把卡片加入 box
6. 從整頁模式上選取一個點或多個點，以中間的點為中心跳回 100% 模式

# UI
https://zpl.io/2vYwW6r

下個 sprint：
物件拖曳
新增卡片、新增 box（以後新增卡片和box還是放到中下方好了）

# Success Criteria
- Box 的字要在全局觀中可以看到
- 可以選取物件進行操作
- 快速流暢切換，一隻手可以做到（在投影的情況）

# research

週一討論結果，有幾種可能做法也可以混合
I. 直接跳 view all nodes，像遊戲的全景地圖
II. 無段式縮放：考慮先定固定倍率可能未來會對 user 造成困擾。
III. 為了塞下所有東西，改 layout：e.g. Box 留字，卡變點，滑過去字才出現。目的是在不同層次顯示不同重要程度的資訊。

還需要 research 不同工具，例如心智圖軟體、遊戲介面
1. 不同倍率上可以還有需要看到幾個節點
2. 每個節點上有多少資訊量，e.g. 字多長

週三 7/11先給 draft solutions，卡西會需要幾個可能的解法的圖或是 video
週四 7/12 UI sync 一起決定哪個解決方案
週一 7/16 要給 UI

# Out of Scope

# Note
hychen 需要的需求是 preview，移動到那個地方。
ael: 要解決的問題是可以看到比較多的議題框架

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/951510

**Comment by aelcenganda** [comment]
Productboard: https://sensetw.productboard.com/feature-board/152244-feature-organization/features/1102399/detail

決定先做以下幾個功能，會先畫 UI，目標不開 inspector，不讓他編輯、新增，只能新增連線和刪除，但是可以從這個畫面跳到別的畫面。

![2018-07-12 17 37 52](https://user-images.githubusercontent.com/9480974/42625435-5adc21ce-85fa-11e8-8d97-06be0797b407.png)

**Comment by Kanailly** [comment]
https://zpl.io/2vYwW6r
剛剛討論的初步畫面。
先做whole page，預期這會是最小scale size的最後狀況。

**Comment by aelcenganda** [comment]
今天討論是以後的想像最佳狀況是 zoom in zoom out 到某個小倍率之後，會改 layout，然後所有操作都跟原本 100% map 一樣。

下次 sprint 的目標是：
- 看得清楚字，又要看到整體架構，勢必要改 layout
所以做整頁模式，但是只開放連線，不開 inspector 不然很佔空間。

@Kanailly 我希望 box list 在整頁模式裡不展開，hover 過去才顯示裡面有什麼卡。

**Comment by aelcenganda** [comment]
@Kanailly 另外，如果有時間的話，也可以先定義一下「物件拖曳」的動作，可能會再放到下個 sprint 裡去實作。

**Comment by Kanailly** [comment]
https://zpl.io/2vYwW6r

**Comment by aelcenganda** [comment]
小結：

這個 sprint 先做到圖的右邊， hover 過去顯示整條 box list，沒有漢堡。
左邊配合之後 box list item 的 selection 和 eject 再去規劃。
