### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#135]

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1083481

**Comment by aelcenganda** [comment]
@Kanailly 我先試用了 PROTT，加完連結後會自動排序收合各個 frame，看你覺得這樣有沒有幫助：
https://prottapp.com/p/df06a2

**Comment by aelcenganda** [comment]
我再用 realtimeboard 排了一個比較能補充加字的版本，希望能明確的標示出哪個 page 優先 fulfill 的目的，跟設計原則。
https://realtimeboard.com/app/board/o9J_k0fhpKQ=/?moveToWidget=3074457346151498413

**Comment by aelcenganda** [comment]
另開 interaction map 討論：
https://github.com/SenseTW/sensetw/issues/150
