### ISSUE TITLE
Redirect missing routes to the index page

### ISSUE THREAD

**Issue by caasi** [SenseTW/sensetw#140]
**Is your feature request related to a problem? Please describe.**
single page application 靠 js 來更新 URL ，但訪問該 URL 時， server 會跳到 XML 頁面，顯示沒有這個 key。

**Describe the solution you'd like**
希望類似下列的解法，可以正常地呈現我們的 web app ： http://to-u.xyz/2016/04/21/react-nginx/

**Comment by caasi** [comment]
現在的 routes 在 https://github.com/SenseTW/sensetw/blob/master/sensemap/src/types/routes.ts

未來可能還會加 `/profile` 或 `/map/:mid/inbox` 之類的。

**Comment by wenchen** [comment]
這部分我打算拆兩個部分
1. 靜態檔案, URL必須包含 [name].[ext]的格式, 假設靜態檔案無法取得, 依然會拿到404
2. 非靜態檔案, URL非 [name].[ext]格式, 那才會導入 /index.html

**Comment by wenchen** [comment]
修改完成
