### ISSUE TITLE
當兩張卡片有連線時不能刪除卡片

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#143]
## Describe the bug
選取一張有連線的卡片時，無法按刪除鈕刪除

## To Reproduce
1. 在 Map 上選取一張有 edge 的 Card
2. 按功能選單「刪除」
3. 無反應

## Expected behavior
按刪除可以從 Map 上刪掉，在 inbox 中留存

## Reference

#187

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1096874

**Comment by pm5** [comment]
我記得在 Graphcool 上是正常的，所以大概是後端沒處理好
