### ISSUE TITLE
Map view point reset

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#144]
## Describe the bug
有時候 map 打開會看不到卡片，因為是記得上一張 map 移動的位置，所以可能在別張 map 已經移動一個畫布以外的距離，跳到另一個 map 那個位置如果沒東西，會不知道怎麼辦。

## To Reproduce
1. Open Map A
2. drag Map A far from the map center area
3. Close Map A and open Map B with less cards
4. see the blank area on Map B

## Expected behavior
1. Remember each map last view points
or 
2. reset map view point every time open a map

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1096877

**Comment by aelcenganda** [comment]
@hychen 你確定已經 merge 到 master 了嗎？我在 staging 看還是沒有 reset

**Comment by aelcenganda** [comment]
沒事，Verified，會 reset 到一開始的中心點。之後要不要使用者回到上次檢視的點再討論。
