### ISSUE TITLE
Multi-select 卡片時應該可以一起刪除

### ISSUE THREAD

**Issue by caasi** [SenseTW/sensetw#147]
**Is your feature request related to a problem? Please describe.**
現在可以多選不特定數量的卡片與盒子，多選卡片時應該可以一起刪除所有卡片。

**Describe the solution you'd like**
多選不特定數量的卡片時，可以按下 delete icon 一次移除所有選中的卡片。

**Additional context**
多選卡片和盒子時該怎麼處理呢？ unbox 和 delete 是一樣的行為嗎？

**Comment by pm5** [comment]
Duplicate to #187
