### ISSUE TITLE
Edit said by who 修正增加意見來源 by 卡片欄位資訊

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#15]
空白輸入 text 的欄位
（能不能用選的再說）
https://zpl.io/V189PMX

意見多元性與可信度
是用欄位切換可以顯示呢？ 還是卡片上的標籤顯示？
或是有利害關係人架map，box 點開可以看到特定利害關係人的發言？

**Comment by aelcenganda** [comment]
填寫利害關係人目前是一個欄位，不是一個新功能，直接合併到新增和修改卡片的 feature 裡。
