### ISSUE TITLE
Map Editor log in

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#151]
# Job Story
When I visit sense.tw
I want to log in Map Editor
So that I can create my own maps or join others' maps

# Note:
所以是所有人只要有 link 而且 log in 都可以編輯 map 嗎？ 
這邊還是需要權限控管。
ael: 傾向目前全部都 public，只要求大家 log in 才能編輯，沒有做任何權限控管。

# Success Criteria
1. log in on sense.tw
2. log in sense.tw if the user is already logged in on via.sense.tw
3. log in via.sense.tw if the user is already logged in on sense.tw
4. After logging in sense.tw, go to Personal Dashboard
5. Only logged in can edit, not logged in guest can view

# Out of Scope
- Map member managements
- public, private map

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1102246

**Comment by hychen** [comment]
完成前端 session management
https://github.com/SenseTW/sensetw/tree/signup_login_v2

**Comment by pm5** [comment]
![img_0636](https://user-images.githubusercontent.com/119645/43069207-1e3fa26a-8e9f-11e8-831c-dba7b46bd61a.jpg)

目前想到三個方案。

方案一是 via-WebClipper 搬到 `sense.tw` domain 底下，可能用 `sense.tw/v` 之類的 URL prefix，就可以分享 cookie。

方案二是用 iframe。看起來太麻煩所以先不認真考慮。

方案三是用 top-domain cookie 交換 `sense_tw_login` state，只有 `true` 和 `false` 兩種值。每個 client 的 private session 會留一份 copy，登入時會 update top-domain login state；如果發現自己的 login state 跟 top-domain login state 不符合，就 redirect 到登入，這時因為已經在其它 client 登入過了，登入 form 會自動通過完成 token 交換再 redirect 回原畫面。

**Comment by aelcenganda** [comment]
補充一下現在 map editor 的 log in 因為是假頁面，所以造成 user confused 以為自己已經 sign up 了但其實還沒有。hychen 今天會先拿掉 map editor 的 signup/login 頁面。

@pm5 下週一 co-work 跟 @hychen 對一下串接哪邊卡住了，很需要推出去的時候有地方 log in 讓我們收email。

**Comment by hychen** [comment]
我先把 dashboard 上的 login/signup 頁面拿掉了。

**Comment by pm5** [comment]
今天討論的 login 作法。

![img_0647](https://user-images.githubusercontent.com/119645/43708470-163768ba-999d-11e8-98e5-819f15100e8e.jpg)

1. 把 backend 的 session cookie 改到 `.sense.tw`
2. Web clipper 目前繼續用 OAuth 2.0
3. Map editor 看是要用 OAuth 還是利用 session cookie
4. Map editor 要加一個 load user profile 的步驗；可以用 https://api.sense.tw/h/api/profile 或是 backend 加一個新的

**Comment by aelcenganda** [comment]
Note:
1. 使用 OAuth 實作無法同步 log in => 就要再自動 log in 一次
2. 目前還沒有規劃 personal dashboard，之後要實作再打開
