### ISSUE TITLE
UI: Refine log in- log out 流程

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#153]
# Job Story
When I log in on via.sense.tw
I want to
1. jump back to the document I was about to annotate
2. at least tell me to go back to the original tab

So that I can annotate on the document or web

目前狀況：
log in 之後一片空白

# Success Criteria
1. user log in 知如何前往 dashboard 或是去 via.sense.tw

# To do:
1. Report 現狀的 bug
2. 流暢狀態頁面要怎麼跳轉 7/23 （一），討論確認

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1102263

**Comment by aelcenganda** [comment]
已跳轉
