### ISSUE TITLE
UI: Not logged in guest view on Map

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#161]
不同權限看到的頁面不同

# UI
https://zpl.io/aRYQy9p

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1112535

**Comment by aelcenganda** [comment]
Not logged in:
- 不能開 inbox
- Inspector 編輯功能關掉

**Comment by aelcenganda** [comment]
verified
