### ISSUE TITLE
UI: MVP UX enhancement

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#163]
做完 interaction map 之後會有幾個可能改善 UI 的方向：

1. 修現有流程和圖片
2. Box List
2. Zoom in/out
3. multi-contributor
4. filter

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1114860

**Comment by aelcenganda** [comment]
@Kanailly 剛剛看了一下 interaction map 開的需求，覺得刪除 box 的確認訊息要先做，（刪除 map 次要）。
