### ISSUE TITLE
8/4 易用性測試規劃

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#164]
時間：8/1-8/5（建議在 8/4（六） 排時段讓大家選 time slot）
人數：3 人，一般工讀生即可

目的：
- 測試產品使用流暢度與抓 bug
- 知道卡關節點

需交付具體任務（以下可能）：
1. 整理 g0v 黑客松提案
2. Debater 過去整理議題
3. 數位國家
4. 女性主義者給問嗎

## 分工：
- hychen/ael: 選主題
- KL 給 flow

## 文件：
https://docs.google.com/document/d/1nNQhJo2zOKYsaFxY_4CXOLWcBvW7Bm7PnhMlhjV07lI/edit
https://docs.google.com/spreadsheets/d/1T1CchbpFX5VB3Yozu4UAgxDvXz1Cryqg4YHwkDdUlsU/edit#gid=1118755373

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1112266

**Comment by aelcenganda** [comment]
訪談完兩位。

**Comment by aelcenganda** [comment]
易用性測試整理，還有週一討論易用性要改的項目：
https://hackmd.io/feweqGPrSniQNBB6sUBHFA?view

卡片設計: 加 creator、new layout
resolution / 全局觀ＱＱ（小班要給size,使用目的
要修改的小地方跟要補的流程圖。
