### ISSUE TITLE
Mapping user feedbacks to job stories and features

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#165]
1. mapping
2. 寫下每個 action, component, page 最主要完成的價值是什麼

要決定接下來開發方向：

1. Original map editor enhancement
2. zoom in/out or whole page view enhancement
3. multi-contributor 權限
4. filter and search

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1114898

**Comment by aelcenganda** [comment]
只數位化到一半
https://realtimeboard.com/app/board/o9J_k0fhpKQ=/?moveToWidget=3074457346154406400

**Comment by aelcenganda** [comment]
先暫時不做了
