### ISSUE TITLE
8 月深度訪談

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#166]
時間：～八月底
人數：2-3 人，需已經使用視覺化方式整理議題資料的人（數位工具或是線下工具）
目的：
- 重新切的 segment 中，專注問整理資料怎麼拉架構
- 確認全局觀、多重觀點、多人協作的需求
- 需有一人是在旁邊看三個小時看怎麼整理，或是錄影

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1111326

**Comment by aelcenganda** [comment]
目前訪完劉李俊達、Lilian。確認全局觀，探討 tag 和分類的功能。

多人協作的部分還是比較少，可能需要 comment
