### ISSUE TITLE
8 月使用者問卷調查

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#167]
時間：～八月底
人數：線上問卷，放在 landing page 和產品裡
目的：
- 將訪談中的重點需求轉換成問題讓人評分重要性和不滿意的程度
- 確認全局觀、多重觀點、多人協作需求的**優先順序**
- 找到潛在使用者的 profile 與訪談對象

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1099964

**Comment by aelcenganda** [comment]
未定好 desired outcomes 無法製作問卷，先放棄。
