### ISSUE TITLE
Blog: 社群 update 兼產品宣傳

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#168]
目的：
- Community update，讓社群其他人知道我們在做什麼
- [x] MVP 開發過程
- [x] COSCUP 活動總結

擴散計畫：
https://hackmd.io/mERFperMRi-30qZpTyQjYg?view

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1099967

**Comment by aelcenganda** [comment]
等服務可以註冊的時候，8/1 一起上線

**Comment by aelcenganda** [comment]
等產品 ready 再發

**Comment by aelcenganda** [comment]
COSCUP 小記：科技社群如何參與科技政策規劃（我們需要更多 Pizza！）
https://blog.sense.tw/2018/08/community-tech-policy-coscup/

在口水戰中縱覽全局，一起用 sense.tw 來畫議題地圖吧！
https://blog.sense.tw/2018/08/sense-beta-issue-map/
