### ISSUE TITLE
7/25 Telegram 群組宣傳

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#169]
- [ ] 宣傳文字（ael）
- [ ] 宣傳圖 （這邊不用設計師出圖好了）
- [ ] 宣傳 link，Facebook event page?
- [ ] 轉貼

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1111255

**Comment by aelcenganda** [comment]
沒有做
