### ISSUE TITLE
8/6 Poster: 放在 COSCUP 攤位

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#170]
目的：
- 吸引人來 COSCUP 的攤位
- 知道這個攤位在幹嘛

COSCUP 文宣品內容
https://hackmd.io/a1giZ7pYRqGR4dE6xd4YPQ

素材：
- [x] ael 會先開一個 drive 讓大家丟東西
- [x] 設計 8/3
- [x] 送印 8/6

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1111176

**Comment by aelcenganda** [comment]
已送印
