### ISSUE TITLE
使用者條款

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#171]
https://trello.com/c/RatwuLw2/340-%E4%BD%BF%E7%94%A8%E8%80%85%E6%A2%9D%E6%AC%BE

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1114743

**Comment by aelcenganda** [comment]
需要請法務再 review。
review 完之後要掛到 log in 頁面連結。

**Comment by aelcenganda** [comment]
@hychen 需要補連結到 api.sense.tw 的連結

**Comment by pm5** [comment]
Closed by 31ede3ccc743bd4188745a58de619c6cb1cc4cff

**Comment by aelcenganda** [comment]
應該要加上公開 map 的協作資料的開放授權。

**Comment by aelcenganda** [comment]
@hychen 資料須加上 CC BY-SA 3.0

**Comment by aelcenganda** [comment]
已經加到 staging。
