### ISSUE TITLE
8/6 g0v 黑客松歷屆關心議題整理＋粉絲頁行銷

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#172]
目的：
1. 提供科技會報 g0v 黑客松關心議題圖像：分大類，列出問題點
2. Demo case for sense.tw

要隨著 7/31 staging push 到 sense.tw 時，同步釋出結果與介紹。
https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1099969/detail

# g0v Summit 前衝刺
- [x] 10/1 雅鈞 map 完成
- [x] 10/2 配合宣傳 content
- [x] 10/3 Release to g0v slack、 g0v 後勤中心

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1100022

**Comment by aelcenganda** [comment]
postpone

**Comment by aelcenganda** [comment]
only blogpost left

**Comment by hychen** [comment]
track blogpost task here #302
