### ISSUE TITLE
Sense local development env

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#173]
讓 Sense Backend, Frontend, via, Postgres 可以在本地端用 docker + docker compose 快速部署起來，讓 developer 可以快速測試 backend/frontend/via/postgres 改完的結果。

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1114951

**Comment by hychen** [comment]
per discussing @wenchen, 彥文會在 https://github.com/SenseTW/devenv 去寫接近 Sense 線上營運環境的設定 script。

預期提供的指令:

1. active:
2. deactive 

source code 會用 git submodule or git subtree binding 放回 sensetw。

**Comment by aelcenganda** [comment]
verified
