### ISSUE TITLE
麵包屑在 log in, sign up 還是有 annotation

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#179]
**Describe the bug**
在 Sign-in/up, change passwords 的時候
1. 還會有 annotation btn 在麵包屑上
2. 若是點選進入 map 之後再 log in，還有 Dashboard>Map 的麵包屑顯示

**Expected behavior**
2.（優先） Log in/out 原本沒有規劃麵包屑，決定要換原本設計的白色 navigation bar
https://app.zeplin.io/project/5ae1980f28546a5bbf985063/screen/5b1ab25847e04a5879b93f21

1. 根據 UI ，在 Setting 的時候麵包屑應該改成 setting
https://app.zeplin.io/project/5ae1980f28546a5bbf985063/screen/5b309e986386e3b32428a528

**Screenshots**
![2018-07-26 15 10 17](https://user-images.githubusercontent.com/9480974/43255055-6063cece-90fb-11e8-88e2-a2e8164d4a05.png)

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1141687

**Comment by pm5** [comment]
改用 api.sense.tw login 以後已經沒有了。
