### ISSUE TITLE
無法在 client log out

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#181]
ael: 在 via.sense.tw 的 client 已經 log in，但是沒辦法 log out。改用無痕視窗就可以順利 log in/out。懷疑是我平常用的 browser 是 log in 之前 sense.tw 的帳號，結果現在無法 log out。

![2018-07-26 15 33 38](https://user-images.githubusercontent.com/9480974/43255344-288e40fa-90fc-11e8-9c36-954d42fe5a55.png)

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1141703

**Comment by wenchen** [comment]
在實作 revoke_token 之後, 已經可以正常 logout
https://github.com/SenseTW/sensetw/commit/71b83fdc036329f64a2c31569920044fcc6428e3

**Comment by wenchen** [comment]
目前 via 已經更新了，假如說有遇到還是無法註記的狀態 (老用戶)
可以請先上 https://api.sense.tw/logout 然後 reload via 就可以了。
