### ISSUE TITLE
Map Editor Not logged in views

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#185]
# Map Editor
UI:
https://app.zeplin.io/project/5ae1980f28546a5bbf985063/screen/5b5ecf3f20dc537f0f22ca75

## Prerequisites

* https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1102246/detail

## Success criteria
- Inbox disable
- inspector edit disable
- 左上方登入提示

# Dashboard
~~dashboard 未 log in 是直接導到 about.sense.tw~~
更改 spec：因為現在 landing page 如果連到 sign up 的話，sign up 後又會跳回 landing page

Dashboard 未 log in-> 
1. 不能新增 map
2. 不能 edit map details
3. 右上角人物大頭像改為 Log in

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1141566

**Comment by caasi** [comment]
> dashboard 未 log in 是直接導到 about.sense.tw

現在 sense.tw 會直接 redirect 到 sense.tw/map (dashboard) ，要是導到 about.sense.tw 會回不到 dashborad ，也無法 login 耶。

**Comment by aelcenganda** [comment]
@caasi 啊啊啊啊，對不起我 spec 沒寫清楚。

我重新改了：
Dashboard 未 log in->
- 不能新增 map
- 不能 edit map details
- 右上角人物大頭像改為 Log in

**Comment by caasi** [comment]
補一下現況：

![localhost_3000_map_94aa8a0d-7013-4fcb-b850-c1e29d7c1c76](https://user-images.githubusercontent.com/1164470/43934718-3ab321f0-9c83-11e8-886c-88bc289eb98e.png)
![localhost_3000_map_94aa8a0d-7013-4fcb-b850-c1e29d7c1c76 1](https://user-images.githubusercontent.com/1164470/43934717-3a7f0e56-9c83-11e8-9ab5-25b3dbe0ae11.png)
![localhost_3000_map_94aa8a0d-7013-4fcb-b850-c1e29d7c1c76 2](https://user-images.githubusercontent.com/1164470/43934716-3a47bcee-9c83-11e8-9361-0da565d114bf.png)

**Comment by aelcenganda** [comment]
噢噢感謝卡西～～現在因為右上角的帳戶設定被拿掉了。之後 map log in 做好後，右上角帳戶設定的地方，應該也會有一個 log in 的入口。
