### ISSUE TITLE
Hide features

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#186]
Hide:
- Search bar on Dashboard and in inbox
- Member on Dashboard

Inactive:
Delete a Map on Dashboard（未來要 map owner 才能刪）

interaction map:
https://www.draw.io/#G1usy1O2WQq-qlpXTJJ_WYdPdIaMOp3nlt

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1141564

**Comment by caasi** [comment]
6a17ace 按說明隱藏了 member 按鈕還有兩個 search 框框， disable delete 按鈕。

和 eede3db 有些不同，我先以 issue 上有紀錄的為準。

**Comment by aelcenganda** [comment]
@caasi 是不是連 Inbox 的 sync btn 都一起隱藏了。

**Comment by hychen** [comment]
sync btn 我有在用。
