### ISSUE TITLE
刪除 Cards and Box

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#187]
UI 設定：
https://github.com/SenseTW/sensetw/issues/149

1. Unbox 這個動作先取消
2. 處理多選，然後「刪除」的操作

對應 Icon 說明
https://zpl.io/2pOx3Nj

對應情境說明（操作手冊）
https://docs.google.com/document/d/1ydHOMmLcD9lW-5_ihg8DF9NIYYhR2XTX6HZjKgL74fs/edit

# 刪除

### Card x1 
目前：選取卡片會出現icon，按下刪除卡片就消失，跟預期一樣。

###  Card x2 (以上）選取兩張卡片
**目前**：沒有跳出 刪除 icon，跳出來的是batch tag（現階段先把batch tag隱藏）
**預期**：跳出刪除icon，按下刪除從map上消失

###  box without cards
**目前**：在map層沒有顯示刪除icon，
**預期**：跳出刪除icon，按下刪除從map上消失

###  box-list  
**目前**：沒有顯示刪除 icon
 **期望**：顯示刪除 icon ，按下去就刪除該box-list (應該要跳通知「確定要刪除有內容的box嗎？」看有沒有時間做 => 先不做）

### empty box  with card 空的box ＋ 一張卡片
**目前**：只會刪掉box，卡片沒有被刪掉
 **期望**：box 跟 卡片同時被刪掉

### box without card and cards
**目前**：只會刪掉box，卡片沒有被刪掉
 **期望**：box 跟 卡片同時被刪掉 （有時間的話做跳出通知「確定要刪除有內容的box嗎？」）

### 兩個以上的box-list
**目前**：沒有跳出 刪除 icon，跳出來的是batch tag（現階段先把batch tag隱藏）
 **期望**：顯示刪除 icon ，按下去就刪除該box-list (應該要跳通知「確定要刪除有內容的box嗎？」看有沒有時間做）
—————————————————

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1141813

**Comment by caasi** [comment]
整理一下現況：

### Card x1

> 目前：選取卡片會出現icon，按下刪除卡片就消失，跟預期一樣。

和預期一樣，自 map 上消失，但是仍在 inbox 中。

### Card x2 (以上）選取兩張卡片

> 目前：沒有跳出 刪除 icon，跳出來的是batch tag（現階段先把batch tag隱藏）

跳出刪除icon，按下刪除從map上消失，仍在 inbox 中。

### box without cards

> 目前：在map層沒有顯示刪除icon，

預期：跳出刪除icon，按下刪除從map上消失。

### box-list

> 目前：沒有顯示刪除 icon
> 期望：顯示刪除 icon ，按下去就刪除該box-list (應該要跳通知「確定要刪除有內容的box嗎？」看有沒有時間做 => 先不做）

目前無法選擇 box list 上的 cards 。

### empty box with card 空的box ＋ 一張卡片

> 期望：box 跟 卡片同時被刪掉

一起被刪掉。

### box without card and cards

> 期望：box 跟 卡片同時被刪掉 （有時間的話做跳出通知「確定要刪除有內容的box嗎？」）

一起被刪掉，不會跳通知。

### 兩個以上的box-list

> 期望：顯示刪除 icon ，按下去就刪除該box-list (應該要跳通知「確定要刪除有內容的box嗎？」看有沒有時間做）

一起被刪掉，不會跳通知。
