### ISSUE TITLE
View Cards in Map Inbox

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#19]
# Job Story
當我打開 map inbox 時，
我會想要可以清楚快速地瀏覽大量卡片獲得重要資訊（summary & tag），
讓我可以大概知道這個 map 要處理哪些資訊與開始在 map 上分類加 box。

# Fields
## Card 
- summary
- tag
- source title
- type by color
- ~~owner~~

# UI 
TBD

# Success Criteria
1. map inbox 打開時仍然可以看到 map 編輯頁面。
2. map inbox 頁面可以關掉。
3. 使用者可以在十分鐘內看完一百張卡片，知道有哪些 summary 和 tag。
4. 使用者可以在 30 秒內找到他已經看過，想要加入 map 的卡
5. Map Inbox 用按鈕換頁
6. Map Inbox 按照內容 update time 排，最新的排前面。

# Out Of Scope
1. 滑動換頁
2. Personal inbox
2. Search result
3. Filter by tag
4. Mark/flag certain cards
5. Recommendation algorithm
6. Sorted by time, owner
7. 切換排列方式，e.g. list view, card view
8. 在 Inbox 裡可以排序，例如往左移，或是拖拉換位置。
9. 可以點擊卡片或 source link 打開 original source
( Above can be features in the future but not now )

# 待討論 with designer

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/955471

**Comment by pm5** [comment]
UI 加了 title。要補。

**Comment by aelcenganda** [comment]
打開 Inbox 的時候，右邊的 Map 和 Box 切換會不見。

![2018-05-21 21 27 10](https://user-images.githubusercontent.com/9480974/40337433-a537878a-5d3d-11e8-9f21-6a8db501213f.png)

**Comment by aelcenganda** [comment]
每張卡片都有驚爆上師的 tag ><

**Comment by hychen** [comment]
拿掉驚爆上師的 Tag

**Comment by pm5** [comment]
還有打開 Inbox 的時候，右邊的 Map 和 Box 切換會不見還沒改。

**Comment by aelcenganda** [comment]
有修好了喔～～超級感謝

**Comment by aelcenganda** [comment]
沒有開 inspector 的時候還是會不見

**Comment by aelcenganda** [comment]
已經改了 layout，不會有這個問題了
