### ISSUE TITLE
設定 og image, title, description

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#192]
# Job Story
When I share a map on social media, e.g. Facebook,
I want to the see preview
So that people would be interested

# Success Criteria before 10/5 
- og_title: Map_name - Sense.tw
- description: Map_description
- image：先全部用一樣的：https://drive.google.com/file/d/1TarBEvSn_zI-RJHOi17yCknhiy1zsTQ6/view?usp=sharing
需要請 @Kanailly 再出一張 1200 x 630 pixels，不然至少 600 x 315
https://developers.facebook.com/docs/sharing/best-practices/

# Success Criteria （之後拆開來）
- og_title: Map_name - Sense.tw
- description: Map_description
- image：先全部用一樣的：https://drive.google.com/file/d/1TarBEvSn_zI-RJHOi17yCknhiy1zsTQ6/view?usp=sharing
需要請凱蘭再出一張 1200 x 630 pixels，不然至少 600 x 315
https://developers.facebook.com/docs/sharing/best-practices/

# 未來想要但應該沒有時間做
- 使用者可以上傳圖片
- 或是自動截圖全局觀作為顯圖

# Solutions

Several choices:

1. Universal app. Caasi 說需要先請 backend 把 html 檔分出來，這個 sprint 先出全站。
2. Run a preloader with phantomjs at backend and redirect robots to there.  We only need one static HTML for each map
3. Run a backend to render HTML headers only for robots.

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1141740

**Comment by caasi** [comment]
求圖片 XD

**Comment by aelcenganda** [comment]
圖片連結：https://drive.google.com/file/d/1TarBEvSn_zI-RJHOi17yCknhiy1zsTQ6/view?usp=sharing

**Comment by caasi** [comment]
抓不到 `og:image` ：
![2018-10-09 11 43 16](https://user-images.githubusercontent.com/1164470/46645664-9b04bc80-cbb8-11e8-9c3c-4651678a29ec.png)

**Comment by aelcenganda** [comment]
目前是有每張 Map 分別的 og:title 和 description #305 ，圖片統一用公版圖片，因為暫且沒有 image upload #303
