### ISSUE TITLE
UI: Zoom in/out + 不同解析度

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#196]
目前狀況：
整頁模式和 100% 分別記住位置
選取物件會 focus 從整頁模式到 100%

目前通行的款式：
- VGA (640x480)
- SVGA (800x600)
1024 x 768

# Success criteria
- 使用者覺得是整張畫布縮放
- 在一定倍率下換 layout（whole picture）
- 可以快速跳到 whole picture 的倍率又跳回百分之百
- 考慮 Box List ejection 操作
- 不同筆電螢幕都方便整理
- 手機瀏覽，要可以觸控滑動
- 投影機投影討論
- 不同倍率不同 layout：全局觀自動算涵蓋全部卡片，但是顯示 layout 是對應到倍率範圍

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1096896

**Comment by aelcenganda** [comment]
ael：
全頁模式按鈕：跳到可以看到所有卡片的倍率，如果倍率沒有很小，就維持原本的 100% layout
縮放：若是縮放到一定倍率之下，換成全頁模式的 layout


紀錄一下剛剛跟卡西討論的結果和會遇到的問題：
1. 目前卡片大小寫死，不會按照內容調整大小。若要比較順暢的縮放，需要卡片和 Box 在畫面上改變大小，而不是 server 寫死。
2. 目前若是要換 layout，線要重連，因為卡片位置是紀錄在左上角，但是現在 100% 跟全頁模式的卡片大小不一樣，線又是連到卡片中心，這樣會需要重新連線。所以會需要更換以卡片中心作為座標。

**Comment by aelcenganda** [comment]
13 吋 Retina
2560 x 1600

iPad （新）
2048 x 1536

Full HD
1920 x 1080

**13 吋螢幕：
1440 x 900 

一般投影（XGA）：
1024 x 768**

SVGA： （舊式的投影機）
800x600

**Comment by aelcenganda** [comment]
卡片 layout 修改：
- source title 拿掉、有 map creator, last updated time (1 hr ago 或是絕對時間）
需要決定放大、縮小的字數、字體大小變化
快速回某倍率，要不要設定倍率上限？e.g. 200%
要不要有邊界框啦？
卡片位置要以中心為準
要調兩種 layout 的長寬比

**Comment by aelcenganda** [comment]
全局觀的 Box 字數應該要隨著放大縮小不要 cut 字

**Comment by Kanailly** [comment]
# UI 不同解析度卡片預先縮小數值：
* VGA (640x480)
縮一半：卡片寬度*0.5
* SVGA (800x600)
卡片寬度*0.6
* 1024 x 768
卡片寬度*0.7

**Comment by aelcenganda** [comment]
差兩個側欄不同解析度下的特定寬度與 body 字級大小

**Comment by Kanailly** [comment]
- VGA (640x480)
縮一半：卡片寬度*0.5
inspector寬度：128
  字級： 7
  欄位高度*0.5
- SVGA (800x600)
卡片寬度*0.6
inspector寬度：160
  字級： 8
  欄位高度*0.5
- 1024 x 768
卡片寬度*0.7
  inspector寬度：204
  字級： 9
  欄位高度*0.6

**Comment by aelcenganda** [comment]
implementation at #252
