### ISSUE TITLE
Create a new Box on Map

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#2]
# Job Story
- When: 
  1. 我發現有一群卡片可以用一個抽象概念概括時，
  2. 我先有一個分析架構時，
- I want to: 我會想要在 Map 上新增 Box，
- So that 我可以把相關的 Cards 收在 Box 裡，減少最外層的畫面複雜度。

# Fields
## Box Base
使用者可以編輯的，按順序：
+ title: 缺乏跨界人才 (string, required)  - the title of a box. Max 40 characters.
+ summary: (string) - Summary of a Box. Max 150 characters.
+ tags: tag1, tag2, tag3 (string) - Tags on a Box, separated by comma. 

## Box
+ Attributes (Box Base)
    + box_id: 780FF (string, required) - the id of a box.
    + created: 1415203908 (number) - time stamp.
    + last_updated: 7815203908 (number) - time stamp.
    + ~~owner (User) - who own this box.~~
    + map_id (string, required) - the id of the map it belongs to.
    + cards (array[Card]) - the cards in this box.

# UI 
zpl.io/2y7WrXG
https://zpl.io/VK0yenP

# Success Criteria
1. 新增 Box 在 Map 上
2. 新 Box 出現在畫面中間偏下
3. Box 長的跟卡片不一樣，要可以看得出來是一個可以把東西放進去的 Box
4. Box 大小不因字數改變
5. 多的字可以自動截短顯示，或是不讓使用者輸入過長字串。
6. 用跟卡片一樣的 Inspector 側邊欄

# Out Of Scope
1. 選取多張卡片直接新增一個 box，然後卡片消失
2. 可選擇 Box color

# 待討論
1. Box title, summary, tag 的字數限制

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/901744

**Comment by aelcenganda** [comment]
差距：
1. 需要更改欄位順序

**Comment by caasi** [comment]
現況：

![2018-05-17 09 05 40](https://user-images.githubusercontent.com/1164470/40189564-9c6414dc-59b1-11e8-875d-c4bbf58d8852.png)

* 多的字可以自動截短顯示，或是不讓使用者輸入過長字串。

在 map 上實現前者有點麻煩，求建議。
