### ISSUE TITLE
Assign a Card in Inbox to a Box

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#20]
# Job Story
當我在瀏覽 inbox 大量的卡片時，
我會想要一次選取多張 card 加入一個 box，
讓我可以迅速在 map 上分類卡片。

# UI 
TBD

# Out Of Scope
3. 卡片消失跟出現的動畫

# Success Criteria
1. 可以選取多張卡片
2. 可以取消選取單張卡片
3. 可以取消選取全部卡片
4. 可以在 box 頁面同時加入卡片
5. 在 inbox 裡面的卡片如果被加入到 map ，則將其調暗。
5. 可以在 map 頁面，點選 box，加入一張卡片
6. 拖拉卡片進 box (not implemented)
7. 按 shift 連續選取多張卡片

# 待討論
1. 在 inbox 裡面的卡片如果被加入到 map ，要將其隱藏、調暗還是放到後面去呢？
- 隱藏：
  - 好處：使用者有清完卡片的感覺，很清楚知道哪些資訊還沒有被放到 map 上
  - 壞處：card 消失，在沒有搜尋功能的狀況下使得使用者很難記得要找的卡片位子在哪裡，因為卡片位置會一直變動。覺得用 list 的方式說不定比較好，因為是單一往下一直找。如果是格狀的 card，光是左右位置改變就很容易會找不到。（假設使用者會用位置記 card 在哪裡的印象）而且未來想要同一張卡片放到不同 box 裡會找不到在哪裡。
- 調暗：
  - 好處：card 位置固定方便尋找。
  - 壞處： card 數量永遠不變，下一個想要的資訊可能要換好幾頁才找到。
- 放到後面：
  - 好處：可以優先看到還沒加入的 card，也可以保留 card 讓之後尋找。
  - 壞處：開發成本高。

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/955470

**Comment by aelcenganda** [comment]
還不行從 inbox 直接選取卡片加入 box 裡，而不先經過 Map。

**Comment by hychen** [comment]
改為: 從 inbox 拖拉卡片到 Box。

**Comment by pm5** [comment]
I think we can close this.
