### ISSUE TITLE
COSCUP 籌備 checklist

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#201]
### BoF、擺攤、工作坊規劃
https://hackmd.io/Oy5ioZhxRmiKu0b9sUQDOw?view
- [x] 工作坊規劃
- [ ] 順走工作坊流程
- [ ] 8/10 場勘

### 網路行銷
- [ ] 8/2-6 Telegram #169 
- [x] 8/2-6 Facebook Event Page #193 
- [ ] 8/10 Public Money, Public Code

### 文宣品
文宣品文字
https://hackmd.io/a1giZ7pYRqGR4dE6xd4YPQ
- [x] 8/6 海報 #170 
- [x] 8/6 貼紙 #194 
- [x] 8/6 酷卡 #195

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1150648

**Comment by aelcenganda** [comment]
文宣品圖檔
https://drive.google.com/drive/u/0/folders/1mxL6zrW5jlUynpopbqFmeWLf0Ef8ag9C
