### ISSUE TITLE
想把 description 字數上限拉到一千字

### ISSUE THREAD

**Issue by aelcenganda** [SenseTW/sensetw#202]
**Is your feature request related to a problem? Please describe.**
Description 字數 250 字太少。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hychen** [comment]
per discussion with @pm5 , 把 description 改存成TEXT , 這樣字數就無限制

**Comment by caasi** [comment]
我在網頁前端加了些限制，好避免超過 255 字時呼叫更新 API 。

等後端改完再拿掉。
