### ISSUE TITLE
Hover 文字固定大小

### ISSUE THREAD

**Issue by aelcenganda** [SenseTW/sensetw#203]
**Is your feature request related to a problem? Please describe.**
目前 hover 過去因為固定倍率而文字太小了，會看不到字。

![2018-08-02 10 05 08](https://user-images.githubusercontent.com/9480974/43558375-c552d7ea-963b-11e8-9ed1-ea2f2c4fb038.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aelcenganda** [comment]
Hover 文字大小在 100% 的時候13級；寬:180

**Comment by caasi** [comment]
和凱蘭見面討論後修正了字的大小、寬度和行高：

* 文字大小： 16px
* CardList 寬度： 200px
* 行高： 1.2em
