### ISSUE TITLE
Can not annotate after login sometimes

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#209]
**Describe the bug**

```
injector.bundle.js?f9cffe:242 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': TypeError: Failed to construct 'URL': Invalid base URL could not be cloned.
    at https://h.sense.tw/client/build/scripts/injector.bundle.js?f9cffe:242:1462
    at https://h.sense.tw/client/build/scripts/injector.bundle.js?f9cffe:167:5312
8angular.bundle.js?fc08de:12 looked up unknown feature orphans_tab
(anonymous) @ angular.bundle.js?fc08de:12
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aelcenganda** [comment]
使用者測試的時候發現，大家都不能在平常使用的瀏覽器介面下 annotate，在無痕模式下可以。

**Comment by linroex** [comment]
剛發現跟 Chrome Extension 應該沒有關係，到開發者工具 Clear Storage 後就可以在正常瀏覽器使用 annotate

**Comment by linroex** [comment]
![2018-08-18 4 39 50](https://user-images.githubusercontent.com/1254953/44297508-591c7000-a305-11e8-88d5-83efcd64906c.jpg)

**Comment by aelcenganda** [comment]
清過 clear storage 之後，有時候還要再清一次。

**Comment by wenchen** [comment]
相同的問題, 無法 refreshToken, 已修正
https://github.com/SenseTW/sensetw/commit/71b83fdc036329f64a2c31569920044fcc6428e3
