### ISSUE TITLE
via: 504 Gateway Error 

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#210]
**Describe the bug**

**To Reproduce**
1. Go to https://via.sense.tw/https%3A%2F%2Flaw.dgbas.gov.tw%2FLawContent.aspx%3Fid%3DFL017556

**Expected behavior**
1. 顯示 via client

** Actual Behavior
**Screenshots**
<img width="765" alt="2018-08-06 11 53 30" src="https://user-images.githubusercontent.com/38706/43696254-b152eb4a-996f-11e8-9af8-97c5795d0849.png">

**Comment by hychen** [comment]
應該是中文網名的問題。

**Comment by wenchen** [comment]
這個網址沒有中文字啊？

**Comment by wenchen** [comment]
我猜是被對方防火牆擋掉了, 我目前除非用在台灣的家用 IP, 不然都連不上這網站

**Comment by wenchen** [comment]
目前測試
* 走 NordVPN 各國都無法連上 law.dgbas.gov.tw
* 直接從 Google Cloud@CHANGHUA 也無法連上 law.dgbas.gov.tw
* 家用網路 / 掛 proxy.hinet.net 可以連上
是被他們防火牆擋住了

**Comment by hychen** [comment]
close this bug. 原因是主機總處防火牆對外部開放。
