### ISSUE TITLE
麵包屑上的 Dashboard > Map，可以顯示 Dashboard > Map_name

### ISSUE THREAD

**Issue by aelcenganda** [SenseTW/sensetw#215]
**Is your feature request related to a problem? Please describe.**
直接分享 Map 給別人的時候，別人進到這個 link 會不知道 Map 的主題是什麼，只看到一堆卡，也不一定會看到最上面或是最中心那張卡。

**Describe the solution you'd like**
麵包屑上的 Dashboard > Map，可以顯示 Dashboard > Map_name，例如
Dashboard > Public Money, Public Code

**Comment by caasi** [comment]
![2018-08-07 23 54 35](https://user-images.githubusercontent.com/1164470/43787331-4e976ac4-9a9d-11e8-8fa6-f5b8b23b123f.png)
