### ISSUE TITLE
New Card Layout on inspector

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#227]
- creator, last updated time, last updated users on inspector（差 UI）
- 顯示 description instead of source title on map
- New card types: Note (default), Statement, Definition, Problem, Solution, (Stakeholder?)。（這樣 annotate 的時候也要分類嗎？

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1189210

**Comment by caasi** [comment]
creator 和新的 card types 等明天合併 #246 後再處理。

**Comment by caasi** [comment]
新的 card type 顏色出來了嗎？

**Comment by aelcenganda** [comment]
差 card type 顏色和 backend
