### ISSUE TITLE
週一討論： Multi-contributor 互動模式。Map owner & contributor 權限 on map

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#228]
# review and planning 討論結果：

需求：想要整理同溫層裡面的論述，找出對公部門的說帖。 => 下週一討論

## 現有卡片操作權限：
- (v) 全開放 => 會比較類似維基共編，追求客觀事實、第三方參考、共識 => 卡片文字修訂紀錄，Map 文字修訂紀錄 User_name add a card ”XXXX”、卡片下 Comment
- 全部鎖只能編輯自己的卡片 => 會比較著重在個人意見 comment，需要搭配 mark/action 做互動，未來也需要處理卡片之間時間序或邏輯關係的表示
pm5：可以設計互動
ael: 卡片文字修訂紀錄與個人意見 comment 用便利貼補充的形式不互相衝突。

## Action 機制：
Notification update：哪些是上次打開視窗後新增的卡 => 互動討論為主的模型
 要 heartbeat 才能做到

## Full History
建議早點做，要怎麼呈現？
如果只是要上次有更新的，需要有登出才能知道
	如果要像 mobile app 靠攏， notification 可以考慮用 service worker 處理
	或是用絕對時間呢？可 highlight 在使用者自定義某個時間之後的卡片

hychen 整理的幾個糾結點與協作模型（持續補充）：
http://sense.tw/map/e1f2bd16-378f-4abc-a689-ade6937075e2

# 舊資料
更新之文件：
https://docs.google.com/document/d/1Tpebb1ZkfcC4iv1CCFe_5ENBImf2qijFyEZ2NWE3clg/edit

尚未更新 job story

# Job Story
When I edit the map
I want to know which cards are mine
So that I can delete my cards and know who contributes to the map

# Success Criteria
1. Map owner can
  - edit details of the map
  - delete the map
  - every operation on Map and Annotation, including delete any cards on map but not in inbox. (or simply hide the comments?)
  - Can't edit others' cards except tags
2. Map contributors can
  - annotate
  - edit and delete their own cards in Inbox and on Map
  - Add  Cards on Map
  - drag, edge
  - only box and delete own cards
  - Can't edit others' cards except tags

3. Every Card recorded creator

# Out of Scope
- Map member managements
- private map

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1012196

**Comment by aelcenganda** [comment]
Gavin & Rex 需求：想要整理同溫層裡面的論述，找出對公部門的說帖。 => 下週一討論
## 現有卡片操作權限：
- (v) 全開放 => 會比較類似維基共編，追求客觀事實、第三方參考、共識 => 卡片文字修訂紀錄，Map 文字修訂紀錄 User_name add a card ”XXXX”、卡片下 Comment
- 全部鎖只能編輯自己的卡片 => 會比較著重在個人意見 comment，需要搭配 mark/action 做互動，未來也需要處理卡片之間時間序或邏輯關係的表示
pm5：可以設計互動
ael: 卡片文字修訂紀錄與個人意見 comment 用便利貼補充的形式不互相衝突。

## Action 機制：
Notification update：哪些是上次打開視窗後新增的卡 => 互動討論為主的模型
 要 heartbeat 才能做到

## Full History
建議早點做，要怎麼呈現？
如果只是要上次有更新的，需要有登出才能知道
	如果要像 mobile app 靠攏， notification 可以考慮用 service worker 處理
	或是用絕對時間呢？可 highlight 在使用者自定義某個時間之後的卡片

**Comment by aelcenganda** [comment]
內部討論串：https://twistapp.com/a/31280/ch/70928/t/472304/

給凱蘭 survey 的協作模型 study 想要問的問題（有些東西還沒附連結）：

hychen 整理在 sense 的SENSE MAP 協作互動模型釐清（我會再補充上去）
http://sense.tw/map/e1f2bd16-378f-4abc-a689-ade6937075e2

## 協作目標：
1. 在同溫層內討論，釐清議題、凝聚共識
2. 非同步＋偶爾線上/線下討論的共編方式 => 產出精準的論證與有價值的資訊
  - 對於新進來的瀏覽者可以看到有意義的資訊（如何顯示重要訊息）
  - 新的協作者進來知道如何加入編輯
    - 如何 update users new contents
    - 如何提升討論品質、引導發言、引導互動
3. 想要維持實體便利貼工作坊時，加便利貼討論發言的行為，因為可以很明確看到新發言的 position 和便利貼顏色種類，還是需要多一個項目。
5. 如何處理爭議、形成共識（如何保留不同意見）
6. 如何 scale，5-10 人編輯、100 人互動（vote or share）、10000 人瀏覽

## 調查後關於工具的影響
- 權限
- 互動、tag
- Dashboard 設計
- 編輯 history
- comment、communication

## 參考工具與平台
- Wiki 、Hackpad、Google Doc 上共編、討論的行為
- Quora/知乎問答
- Arguman 與其他線上圖像化論證/整理資料的工具，例如心智圖
- GitHub 上的文件類型協作

## 可以回顧過去的討論內容：

Design Sprint 的 idea pool（我先列我想到的）
- 知乎共編問題
- 換位思考
- Fork and merge

線上 brainstorming 工具 Competitor
[Twist: Competitor](https://twistapp.com/a/31280/ch/70928/t/296542)

相關的線上公民討論工具與心智圖工具
https://twistapp.com/a/31280/ch/69983/t/211362/

遊戲設計：建立 safe space 的心理機制
https://twistapp.com/a/31280/ch/69983/t/177101
（覺得也可以參考薩爾達如何在開放世界引導玩家觸發做下一步行動）
https://www.youtube.com/watch?v=T35UQSWSM94

**Comment by aelcenganda** [comment]
結論：

1. edge 先物件化，可以標 direction 和寫 summary
2. Comment to be resolved with action tag 可以做成另一種小物件 attach on CARD, BOX, EDGE，但是時間不夠先不做。未來可以繼續發展成 voting 、Comment 轉成 CARD。
3. 先做 full history
4. 要討論要不要做 realtime collaboration

**Comment by aelcenganda** [comment]
再把詳細結論放上來

**Comment by aelcenganda** [comment]
結論：
1. Realtime collaboration 太花時間，不做，把 full history 做好
2. 會做 edge 物件化
3. Comments to be resolved 先不做，先把不同 card type 的回應做好。但需要注意怎麼導引用加卡的方式來回應，加卡也可以獲得比較長的回應。
3. 要做 tag / stakeholder view
