### ISSUE TITLE
Map 修改

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#229]
Map：
- 圖例
- annotation —> Add source
- 改 edit icon 為筆
- 加提示解說的位置。（待補）
- Map details on Map Editor

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1189430

**Comment by Kanailly** [comment]
# UI 
https://zpl.io/2pdkEMN
-----------------------
權限跳通知的設定要不要放到跳刪除訊息的那個issue~?
