### ISSUE TITLE
Delete Map & Box 確認刪除訊息

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#230]
# For Card in Inbox

Header: ⚠️Warning⚠️

Are you sure you want to delete this Card from Inbox?

⚠️Warning: This action cannot be undone. You can't recover this Card again.

btn:
Cancel, Delete

抄一下 productboard :P
![2018-09-27 15 29 16](https://user-images.githubusercontent.com/9480974/46130578-3b2f1d00-c26c-11e8-89d0-d5705bf78df1.png)

# For Box on Map（裡面有卡片的）
⚠️Warning⚠️

Are you sure you want to delete this Box and {number} Cards in the Box on Map? 

⚠️Warning: This action cannot be undone.

Note:
1. Only Cards will be restored in Inbox.
2. You can remove a Card out a Box by "eject" button on toolbar after you open the box.

btn:
Cancel, Delete

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1141733

**Comment by Kanailly** [comment]
# UI
刪inbox卡：https://zpl.io/29y9QXY
刪Box：https://zpl.io/aw1GRzj

**Comment by caasi** [comment]
現況：

![刪除卡片](https://user-images.githubusercontent.com/1164470/46349807-a9694a80-c685-11e8-9332-261bd41cda32.png)

![刪除 box](https://user-images.githubusercontent.com/1164470/46349821-b6863980-c685-11e8-8d1c-3c78f4d96e16.png)

![刪除有 1 張卡片的 box](https://user-images.githubusercontent.com/1164470/46349833-c00fa180-c685-11e8-9363-d5985c955150.png)

![刪除有複數卡片的 box](https://user-images.githubusercontent.com/1164470/46349856-cdc52700-c685-11e8-965f-933922e15a67.png)
