### ISSUE TITLE
9/11前 報告 50 社群關心議題報表

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#233]
Goal：
- 9/13 報告，讓科技會報知道社群跟他們想的不一樣
- 11 月為了結案
- 盤點 2013 年後，主要新聞事件、社群關心議題

To do：
- 把社群討論的空間盤出來
- 再找實習生協助盤點（9-11 月）：OCF 能不能幫忙、行政會議確認人力預算
- 簡報

未來：
- 把討論過的議題，用時間軸、列表把它呈現出來

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1100028

**Comment by aelcenganda** [comment]
簡報：
https://docs.google.com/presentation/d/1rZbeXW4N2A2XWia1p3cdr6XwdPTVKXI8IHPRrRaJAfo/edit#slide=id.g416f76dffe_0_0

整理表單：
https://docs.google.com/spreadsheets/d/1cB07Cy4rsQCqb9FB4Ju_KoMc6AHOammQ28AQei8-Gn0/edit#gid=302505972
