### ISSUE TITLE
Add Tags on a Card on Inspector

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#24]
# Job Story
- When: 我閱讀卡片的詳細資訊時
- I want to: 我會想要對卡片利用 tag 做分類
- So that: 方便我之後可以在卡片上瀏覽 tag 和搜尋關鍵字找出相關的卡片。

# UI 
TBD

# Out Of Scope
1. 巢狀 Tag。
2. different type of tags

# Success Criteria
1. 每個卡片的側邊欄有一個字串輸入欄可以讓使用者輸入多個 tag ，plain text 即可。 範例： "tag1, tag2, tag3"
2. tag 之間用 " , " 分割。

# 待討論
就是 tag 輸入後在 inspector 上的樣子： UI & RD

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/955508

**Comment by caasi** [comment]
Check https://github.com/SenseTW/sensetw/commit/71656e941d69394936539dfa9ecfe8a758646ce1
