### ISSUE TITLE
FE: Inbox, Map, Inspector enhancement (meta)

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#240]
# UI
https://app.zeplin.io/project/5ae1980f28546a5bbf985063/dashboard?

## Map 
- #273 右上角新增 "..." ，連到 map create 的 modal，可以 Edit Map details on Map
- #257 New layout: 5 card type, including color change in box item, and 5 box types

## Inspector
- #274 Inspector 有 advanced setting 收疊
- #257 5 card types with different placeholders
- #275 Annotation 新增 Quote 欄位，隱藏 description

## Inbox
- #276 "+" btn 改為 add source，連到 via.sense.tw
- #276 new inbox card layout
- #276 每頁 10 個
- #276 (search bar 維持隱藏)

##
以下 UI 9/13 週四確認，沒時間實作就移到下個 sprint
- 圖例
- New toolbar 變成直的，需要考慮 disabled 還是隱藏, including 縮放倍率顯示
- 選取狀態區

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1141760

**Comment by aelcenganda** [comment]
只差 #273 未實做。
