### ISSUE TITLE
規劃把 session 移到 Redis 或 Memcache

### ISSUE THREAD

**Issue by pm5** [SenseTW/sensetw#249]
@wenchen 要開始拆 multi-instance /w load balancing

**Comment by wenchen** [comment]
staging 保持在 memory 好了, production 才要拆出去, 個人偏好 redis or db

**Comment by pm5** [comment]
估計接 [connect-redis](https://github.com/tj/connect-redis) 把 session 移到 Redis 在程式這一端的 effort 是 1

**Comment by wenchen** [comment]
記錄一下, 目前僅在 production 使用, 需設定 env var 
`
REDIS_HOST= 
REDIS_PORT=
`
