### ISSUE TITLE
Edit Tags on a Card on Inspector

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#25]
# User Story
- When: 我在 Map Inbox 或是 Map 閱讀卡片時
- I want to: 更新卡片上一個 tag 的文字
- So that: 方便我之後可以更精確地在卡片上瀏覽 tag 和搜尋關鍵字找出相關的卡片。

# UI 

TBD

# Success Criteria

1. 每個卡片的側邊欄的 tag 輸入區，可以去修改一個 tag 的字串。

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/892671

**Comment by caasi** [comment]
Check https://github.com/SenseTW/sensetw/commit/71656e941d69394936539dfa9ecfe8a758646ce1
