### ISSUE TITLE
Zoom in/out 與全局觀串接

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#251]
# UI:
https://github.com/SenseTW/sensetw/issues/196

# Success Criteria
1. zoom in/out 到特定倍率切換 layout（UI 待訂），對使用者來說是縮放換 layout
2. 不同 layout 的 viewport 要一樣
3. 要有回到標準倍率的
4. 按眼睛還是跳到可以看到所有卡的全頁模式。

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1212912

**Comment by caasi** [comment]
> 1. zoom in/out 到特定倍率切換 layout（UI 待訂），對使用者來說是縮放換 layout
> 1. 不同 layout 的 viewport 要一樣

倍率還沒決定，暫定 0.66 。按 - 按鈕四下即可： https://m11-frontend.staging.sense.tw/map/8c1c6b87-8bf8-4360-af93-5e5c917aa780

**Comment by aelcenganda** [comment]
週一跟凱蘭訂了 0.33 倍率，抱歉沒更新上來。

**Comment by aelcenganda** [comment]
@caasi 凱蘭剛剛更新了不同解析度：

# UI 不同解析度卡片預先縮小數值：
* VGA (640x480)
縮一半：卡片寬度*0.5
* SVGA (800x600)
卡片寬度*0.6
* 1024 x 768
卡片寬度*0.7

**Comment by caasi** [comment]
好囉，現況：

![2018-09-05 19 45 40](https://user-images.githubusercontent.com/1164470/45091228-5793da00-b144-11e8-83f4-936b0f45caac.png)
