### ISSUE TITLE
投影機 resolution

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#252]
# UI
https://github.com/SenseTW/sensetw/issues/196

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1212913

**Comment by caasi** [comment]
#251 解了一部分，剩下 menu, inspector, inbox 的 RWD 設計。

**Comment by aelcenganda** [comment]
@Kanailly 差不同解析度的 inspector 寬度，有沒有要改 body 字級大小

**Comment by aelcenganda** [comment]
凱蘭剛剛 #196 補了 

- VGA (640x480)
縮一半：卡片寬度*0.5
inspector寬度：128
  字級： 7
  欄位高度*0.5
- SVGA (800x600)
卡片寬度*0.6
inspector寬度：160
  字級： 8
  欄位高度*0.5
- 1024 x 768
卡片寬度*0.7
  inspector寬度：204
  字級： 9
  欄位高度*0.6

**Comment by caasi** [comment]
欄位高度指的是什麼的欄位啊？單位是什麼？比例嗎？

**Comment by aelcenganda** [comment]
@Kanailly 說欄位是 inspector 輸入框高度的比例。

除了欄位高度外，其他在 m12-rest branch 可以看到。

**Comment by caasi** [comment]
![localhost_3000_map_c03aa999-534b-4fdf-8aa5-bf45ad6f3fc1_object 31db6750-a4c8-41a7-8f9b-2cd0d778f811 ipad](https://user-images.githubusercontent.com/1164470/46056840-422f3000-c185-11e8-8e29-3b08c397a5dc.png)

這是寬度 641px ~ 800px 的樣子，欄位高度 75px * 0.5 ，這樣是 @Kanailly 你想要的嗎？ description 看起來怪怪的。

**Comment by aelcenganda** [comment]
@caasi 切換全局觀的倍率改成 0.65
