### ISSUE TITLE
PM：定義 growth hacking 要的數據和行銷計畫

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#256]
# 要問工程師的問題：
1. 可以記錄鍵盤操作嗎？
2. 需要紀錄帳號操作，不然就是要用 Google 的 userid
2. 到時候可以開權限讓我用 SQL query 嗎？

# Success Criteria
- [ ] GTM setting to have funnel
- [ ] Clear spec for caasi to implement before Mon.
- [ ] Scheduled marketing plan till Dec

# Tools:
- Google Analytics
- Google Tag manager: Click events, userid, duration
Still researching:
crazyeggs, amplitude

# Goal:
1. More people to read contents longer: 
  - Single map viewing duration sum
  - Cross map readers viewing duration sum
2. More people to create a good quality map:
    - Identify user groups that create a map
    - What triggers a user to create a map
    - What is the critical point and patterns of map development that draws page views? e.g. number of cards, edges
3. More people to edit a map
    - Sign up success
    - Identify user groups that contribute others maps
    - What triggers a user to respond or to edit
    - What is the critical point and patterns of map development that draws contrbutors
4. Retention cohort:
    - which types of user visit back and continue to edit maps?
    - which campaign attracts more coming back and higher contribution users

# Questions to be answered (developing)
1. Annotation:
    - Which stage to lose users? e.g. needs more clear instruction to users: not knowing what is annotation, no guides on via.sense.tw
    - Length range of comment on a quote
    - Select map confusion
    - Tagging on client or in inbox or on map
    - What types of websites/documents people want to annotate on?
2. Map 
    - Inbox:
         - used rates on sync btn, search bar, source list
         - Opened by toolbar or slide bar
         - Open inspector to view or to edit 
         - Open inspector to edit or directly add cards to map 
    - Map Editor
         - Toolbar clicks
         - click for more info on map?
         - click to see map details?
         - What's the most frequently used zoom-in/out  ratio？
         - Fit to screen v.s. 100 %
    - Box
         - How many users add cards into Box? Boxes containing cards / all boxes
         - How many user open a box to further draw a sub map
         - How many times user expand box list? they prefered box list open or closed?
         - How users leave a box? by crumb or by other methods?
         - Do users select Box types?
         - Do they want to select box items?
    - Card
         - How many users select Card types?
         - Ave. length of summary and description
         - How many users open advanced settings?
    - Edge
    - Tag
         - Ave. tag per card
         - Ave. card No. under one tag
         - When the tags are added on a card/box, along with creation or later edit?
    - Stakeholders
         - how many active user open advanced setting for stakeholders
         - Ave. stakeholders per card
         - Ave. card No. under one stakeholder
    - Inspector

# Onboarding new users
1. sign up flow: new visitors to sign up
which landing page -> click to which item ->... -> api.sense.tw/signup -> success/error rate -> next page
2. log in flow:
which page to start -> click to which item -> api.sense.tw/login -> success/error rate-> next page
3. Forget password:
Forget password -> submit email -> reset link -> reset password -> successfully log in

# Navigate, select, inspect, and edit
1. Clicks on Navigation Bar: logo, about, dashboard, help, profile setting
2. Clicks on crumb: dashboard, map, box
**3. Copy and Paste by keyboard (?)**

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1217371

**Comment by aelcenganda** [comment]
需要更新 interaction map:

https://www.draw.io/?state=%7B%22ids%22:%5B%221usy1O2WQq-qlpXTJJ_WYdPdIaMOp3nlt%22%5D,%22action%22:%22open%22,%22userId%22:%22115175062087116734591%22%7D#G1usy1O2WQq-qlpXTJJ_WYdPdIaMOp3nlt

**Comment by wenchen** [comment]
與其學 SQL 有沒有考慮改用 GraphQL ...

**Comment by aelcenganda** [comment]
拆分成小的 issue 了 #344 #343
