### ISSUE TITLE
New Card/Box Layout

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#257]
# UI

# 5 Card types and 5 Box types
Problem: pink
Solution: Blue
Definition: yellow
Info: green
Note: white

# UI
https://github.com/SenseTW/sensetw/issues/260

![2018-09-11 17 08 56](https://user-images.githubusercontent.com/1164470/45350313-0cffdb00-b5e6-11e8-93b7-33d7cdb2a444.png)

UI
Card Color
https://zpl.io/VDnKOGv
https://zpl.io/2pdkEMN

Card & Inspector
https://zpl.io/2pdkEMN

# Success Criteria
1. 5 types of Cards and boxes
2. new layout on map display

parent issue: #240

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1212901

**Comment by caasi** [comment]
加上 card creator, card creation date 還有 box creation date ：

![2018-09-19 05 15 29](https://user-images.githubusercontent.com/1164470/45716973-24812a00-bbcb-11e8-8931-cdb78f1b3d87.png)

由於 #223 並未要求實作 box creator ，無法顯示 box creator 。
