### ISSUE TITLE
CARD 欄位修正

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#258]
# Success Criteria
維持不變，先不合併
- Summary max 150 cha
- Description: no max limit

新增：
- quote: 原本 via 上面 highlight 的文字會進 description 和複製一份到 summary，現在不複製了。現在 highlight 的文字獨立顯示成 quote，不開放在 map 編修。保留 annotation CARD 的 description 欄位，前端暫時隱藏不顯示。自己手動開的卡片就沒有 quote 。
- 5 CARD TYPE and 5 Box types: problem, solution, definition, note, info (不確定後端改了沒)

# UI 
https://github.com/SenseTW/sensetw/issues/260

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1217543

**Comment by aelcenganda** [comment]
@pm5 剛更新卡片欄位修正

**Comment by pm5** [comment]
之前的 card type 對映到新的：

* QUESTION => PROBLEM
* ANSWER => SOLUTION
* NORMAL => NOTE
* NOTE => NOTE

這樣嗎？

**Comment by aelcenganda** [comment]
@pm5 對，然後對 annotation 來的卡片要新開 quote 的欄位，不好意思晚回了。

**Comment by caasi** [comment]
我太早 migrate 到新的 card type 了，之後還要把設錯的預設值改回來。

**Comment by aelcenganda** [comment]
pm5 會做 annotation -> quote。
caasi 會做 migration，和 quote 的顯示。

**Comment by aelcenganda** [comment]
補充：
@pm5 ，希望可以幫 BOX 加上 Box Creator。

**Comment by pm5** [comment]
改好了，在 `morecardfields` branch
