### ISSUE TITLE
議題松

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#259]
Goal: 
- 凝聚社群共識
- 議題試做報告要結案

目前：
- 2 議題
目前傾向工作坊時用實體便利貼模式，討論完後的東西整理到 sense.tw 做後續衍伸討論，並且讓下一次工作坊接續上次討論的進度。

理由: 
- 實體工作坊教工具使用太花時間，且參與者容易跟議題釐清方法搞混。
- 維基的 Rake 有講過這件事。

To do
- 確認人力
- 議題 Follow up

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1217558

**Comment by aelcenganda** [comment]
https://docs.google.com/document/d/1Ebj8175iBLna_t6xBcJP27HGbmA9hFI7wOohx3EK3mk/edit#

**Comment by aelcenganda** [comment]
9/13 在摩茲工寮先用網路中立性試 run:
https://www.facebook.com/events/453192175172987/
