### ISSUE TITLE
Delete tags on a Card on Inspector

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#26]
# User Story
身為一個使用者，會想要刪除卡片上的一個 Tag。

# UI 

TBD

# Out Of Scope

# Success Criteria
1. 每個卡片的側邊欄，在輸入區的 plain text 去刪除 tag 字串。

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/892668

**Comment by caasi** [comment]
Check https://github.com/SenseTW/sensetw/commit/71656e941d69394936539dfa9ecfe8a758646ce1
