### ISSUE TITLE
UI: new card/box layout and inspector

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#260]
CARD
- creator
- 5 types：顏色、icon or 圖例幫助分辨 card type
- 2 layouts
- source title 拿掉

BOX
- creator
- 5 types：顏色、icon
- 2 layouts

INSPECTOR:
- creator
- created time
- last updated at {time} by {user}
- CARD type 往上挪

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1217568

**Comment by Kanailly** [comment]
# UI
Card Color
https://zpl.io/VDnKOGv

**Comment by aelcenganda** [comment]
# 五種卡片 type 的 placeholder:

## Problem
- summary: 簡短提問，針對這個議題、別人解法和意見的問題、疑慮、風險
- tags: tag1, tag2, 用逗號隔開
- source_title: 資料來源名稱，e.g. 【AI全面啟動Ⅱ：台灣企業行不行？關鍵在老闆｜天下雜誌】
- source_link: https://o.sense.tw/abcd
- description: 針對你提的問題有什麼補充資訊和支持證據？資料原文摘錄重點可以使用畫面右上角 Annotation 功能。
- type (string) - Card type: Problem, Solution, Definition, Info, Note
- said_by: 誰提出的意見？ e.g. XX 大學校長 XXX
- stakeholders: 誰會被影響？e.g. 經濟部, 半導體廠商, 大學（用逗號隔開）

## Solution
- summary: 簡短回答，針對別人提出的問題和疑慮，有什麼解法？
- tags: tag1, tag2, 用逗號隔開
- source_title: 資料來源名稱，e.g. 【AI全面啟動Ⅱ：台灣企業行不行？關鍵在老闆｜天下雜誌】
- source_link: https://o.sense.tw/abcd
- description: 這裏可以更詳細解釋解決方案的細節補充資訊和支持證據。資料原文摘錄重點可以使用畫面右上角 Annotation 功能。
- type (string) - Card type: Problem, Solution, Definition, Info, Note
- said_by: 誰提出的意見？ e.g. XX 大學校長 XXX
- stakeholders: 誰會被影響？e.g. 經濟部, 半導體廠商, 大學（用逗號隔開）

## Definition
- summary: 釐清專有名詞定義，例如定義什麼是 AI 人才、自由軟體、網路中立性，幫助大家討論有共同基礎。
- tags: tag1, tag2, 用逗號隔開
- source_title: 資料來源名稱，e.g. 【AI全面啟動Ⅱ：台灣企業行不行？關鍵在老闆｜天下雜誌】
- source_link: https://o.sense.tw/abcd
- description: 建議引用外部資料作為名詞定義來源。資料原文摘錄重點可以使用畫面右上角 Annotation 功能。也開放大家共編讓定義更完備。
- type (string) - Card type: Problem, Solution, Definition, Info, Note
- said_by: 誰提出的意見？ e.g. XX 大學校長 XXX
- stakeholders: 誰會被影響？e.g. 經濟部, 半導體廠商, 大學（用逗號隔開）

## Note 
- summary: 簡短表示個人意見、註解與回應，無法歸類的各種留言。
- tags: tag1, tag2, 用逗號隔開
- source_title: 資料來源名稱，e.g. 【AI全面啟動Ⅱ：台灣企業行不行？關鍵在老闆｜天下雜誌】
- source_link: https://o.sense.tw/abcd
- description: 有更多想說的可以放在這裡。
- type (string) - Card type: Problem, Solution, Definition, Info, Note
- said_by: 誰提出的意見？ e.g. XX 大學校長 XXX
- stakeholders: 誰會被影響？e.g. 經濟部, 半導體廠商, 大學（用逗號隔開）

## Info
- summary: 補充中立的資訊來源，例如統計數據、相關研究。
- tags: tag1, tag2, tag3
- source_title: 資料來源，e.g. 主計總處
- source_link: https://o.sense.tw/abcd
- description: 建議引用外部資料作為補充資訊來源。資料原文摘錄重點可以使用畫面右上角 Annotation 功能。也開放大家共編讓資訊更完備。
- type (string) - Card type: Problem, Solution, Definition, Info, Note
- said_by: 誰提出的意見？ e.g. XX 大學校長 XXX
- stakeholders: 誰會被影響？（用逗號隔開）e.g. 經濟部, 半導體廠商, 大學

**Comment by Kanailly** [comment]
@aelcenganda  Box 的 inspector的 Summary欄位的place holder也會因為type而有不同嗎？ 還是跟卡片的summary的place holder一樣？

**Comment by aelcenganda** [comment]
@Kanailly 對，  Box 的 placeholder 也一樣

**Comment by caasi** [comment]
source_title 和 Zeplin 上的設計稿有些不同耶，以哪一邊為準？

**Comment by Kanailly** [comment]
Sorry~ 我沒有注意到info的source title變了ＱＱ
