### ISSUE TITLE
UI: full history

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#263]
# 時程
四：功能討論
一：wireframe
四： real UI

# Job Story
When I re-enter the map,
I want to see what has been changed on the map,
So that I can respond to those new changes with my opinion

# Success Criteria
1. Showing {Who} {edit} {what} at {what time} on a Card, a Box and a Map
(之後會再納入物件化的 Edge, 在 View 中可以檢視編輯 description 的 Tag 和Stakeholder )
2. Links to CARD, BOX, Edge (Tag, stakeholder) mentioned in the full history.

- Edits on Card:
  - Created/ archived/ deleted  by {who} at {time}
  - Added to the map by {who} at {time}
  - {who} changed the summary {} from {} at {time}
  - {who} edited the {description}/ {tag}/ {stakeholders}/ {said_by}/ {source_link}/ {source_title} at {time}
  -  {who} changed Card type from {} to {} at {time}
  -  {who} linked/unlinked this Card to {} at {time}
  -  Added in / ejected out of {Box title} by {who} at {time}

- Edits on Box
  -  Created/ deleted by {who} at {time}
  - {who} changed the Box Title {} from {} at {time}
  - {who} edited  {tag}, {summary} at {time}
  - {who} changed Box type from {} to {} at {time}
  -  {who} linked/unlinked this Box to {} at {time}
  -  {who} added / ejected {Card Summary} out of a this Box at {time}

- Edits on Map
  - Created by {who} at {time}
  - {who} added/deleted {CARD}, {BOX}
  - {who} changed Card Summary "{CARD summary}"/ Box Title "{Box title}" from "{CARD summary}"/ "{Box title}". 
  - {who} edited {description}/ {tag}/ {stakeholders}/ {said_by}/ {source_link}/ {source_title} in Card "{summary}" at {time}
  - {who} edited {tag}, {summary} in Box "{Box title}" at {time}.
  - {who} added / deleted {EDGE} between {} and {}
  - {who} added/ejected Card "{summary}" into / out of Box "{title}".
  - {who} edited {description}, {tag} in Map Details
  - {who} changed Map Name from {} to {}

# To be discuss
1. 權限：https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1242665/detail
  - Can Map owner lock the map?
2. How to deal with Conflict?
3. At least one undo?
4. 如何顯示 full history? how to collapse changes? 不然 change log 會太細節。
    - 例如可以同一個人如果沒有下一個人修改的話，一天內的編輯壓在一起顯示，並且重點顯示差異內容。例如新增的字顏色不同，刪除線。
   - 例如可以用 icon 化的方式表達 change 的型態？或是用卡片的方式？
# UI
https://zpl.io/2jwKwWr

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1242847

**Comment by aelcenganda** [comment]
Conflict:
1. 以新的寫入為準，若已經被刪除會跳通知，告知在 inbox 裡還可以找到。
2. 系統寫入只會去改掉真的有修改的欄位。
2. 刪除：要 card creator 、 box creator 、Map owner 才能刪除。可以刪的人 toolbar 再跳出來。

**Comment by aelcenganda** [comment]
已更新文字敘述，讓改 Card Summary 和 Box Title 是獨立的敘述。

週一討論：
1. edit 的詳細內容，會要再進入一層， caasi 前端 diff 會用紅色、綠色去做新增與刪減的區分。
2. Full history 裡面 Card 和 Box 要顯示出 summary 和 title，上限 20 字，多出來的就 ...，讓他可以點進去看詳細內容。

**Comment by Kanailly** [comment]
# UI
https://zpl.io/2jwKwWr

**Comment by aelcenganda** [comment]
1. 需要給卡西不同人名輪流的顏色組
2. 希望 diff 的部分可以前後分段，from 不要在句中，要在句首分開
