### ISSUE TITLE
UI: annotation 流程改善

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#264]
# Success Criteria—之前討論要做的
- via 那頁要有功能介紹引導：https://github.com/SenseTW/sensetw/issues/231
- annotation client 頁

# To be discussed
- 需要有 page note 嗎？（ael 覺得還是需要，只是 hypothesis 的設計很令人困惑，要研究一下怎麼把 hychen 做的 source list 跟書籤 embed ）

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1246307

**Comment by Kanailly** [comment]
需要描述目前對 page note 功能需求的描述，並定義 page note 的資料欄位如何對應到目前map上的資料格式 @aelcenganda

**Comment by hychen** [comment]
unclear request. close this.
