### ISSUE TITLE
Tag manager code on sense.tw and api.sense.tw 

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#267]
- [x] tag manager on sense.tw @caasi 
- [x] tag manager on api.sense.tw @pm5 

ael 希望在週五前

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1255697

**Comment by wenchen** [comment]
Tag Manager 我想用現有容器就好了 (GTM-M9D9FX9)
接著在 變數 -> 使用者定義的變數 -> GATrackingID 置換成新的 GA ID就行了, 設定都可以通用, 目前 GA 設定是可以跨 domain tracking (**.sense.tw) 所以 front/backend 可以用同一組

**Comment by pm5** [comment]
開了新的 GTM container `backend`，ID `GTM-WR9NSMK`。掛上 production 了。
<img width="983" alt="screen shot 2018-09-12 at 12 47 53" src="https://user-images.githubusercontent.com/119645/45402787-1b9fce00-b68a-11e8-9aa1-6ec436098751.png">

**Comment by caasi** [comment]
frontend: `GTM-NZCDJ6N` ，請將 `REACT_APP_GTM_ID` 環境變數設成它。

see: 08e5897

**Comment by wenchen** [comment]
Front-end 不考慮把 Google Analystic Code 改移到 Google Tag Manager 管理嗎？我剛看一下還是兩個組件同時存在在程式碼內？

**Comment by wenchen** [comment]
我已經把 Frontend 的 GTM 先擺上了, 提醒 @caasi 跟 @pm5 , Google Tag Manager 的容器至少要發布一次以上, 才會正常運作, 我剛剛測試了一下, 皆拿到 404.
![screen shot 2018-09-16 at 11 44 05 am](https://user-images.githubusercontent.com/959457/45592647-f242b300-b9a5-11e8-92b7-02208ab0dc17.png)
![screen shot 2018-09-16 at 11 43 18 am](https://user-images.githubusercontent.com/959457/45592648-f242b300-b9a5-11e8-87f4-a168378c8142.png)

**Comment by caasi** [comment]
已發佈一次。

> Front-end 不考慮把 Google Analystic Code 改移到 Google Tag Manager 管理嗎？我剛看一下還是兩個組件同時存在在程式碼內？

@wenchen 先麻煩你拿掉 GA 的環境變數即可， React 元件我稍後再移除。

**Comment by wenchen** [comment]
okay, 我已經先把 GA 的值清空了, 下次編譯就會生效

**Comment by aelcenganda** [comment]
我今天早上測是 api.sense.tw 可以用了，sense.tw 還不行。

**Comment by aelcenganda** [comment]
caasi 解釋過後，測 staging.sense.tw 可以了，等之後上 production，感謝～
