### ISSUE TITLE
社群關心議題清單

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#269]
1. [社群關心議題整理 SOP](https://docs.google.com/spreadsheets/d/1cB07Cy4rsQCqb9FB4Ju_KoMc6AHOammQ28AQei8-Gn0/edit#gid=302505972)
2. [社群自辦 250 人以上大型活動](https://docs.google.com/spreadsheets/d/1cB07Cy4rsQCqb9FB4Ju_KoMc6AHOammQ28AQei8-Gn0/edit#gid=1963403972)
3. [創立一年以上的社群清單](https://docs.google.com/spreadsheets/d/1cB07Cy4rsQCqb9FB4Ju_KoMc6AHOammQ28AQei8-Gn0/edit#gid=0)

# Success Criteria:
- [x] 寫出主動盤點 SOP。
 - [x] 寫出主動盤點社群自辦250人以上活動 SOP。
 - [x] 寫出主動盤點社群討論空間 SOP。
 - [x] 寫出主動盤點 2013 到2018 年關心的重要議題的 SOP。
- [x] 寫議題試做報告框架。
- [ ] 寫議題試做報告草稿。

**Comment by aelcenganda** [comment]
報告草稿另開 https://github.com/SenseTW/sensetw/issues/285
