### ISSUE TITLE
對科技社群介紹 sense.tw

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#270]
# To do
- [x] 社群討論科技政策的 mailing list => 決定先不用 mailing list 了，可以導到 vTaiwan 討論
- [x] 主頁：blog.sense.tw 
- [x] 訂閱 mailing list (lloyd)
- [x] 把 lloyd 加到 GitHub (hychen)、wordpress (ael)

# To be discussed
- [x] 置頂介紹文（lloyd + hychen）：怎麼跟社群介紹 sense.tw，寫給 OCF board mailing list 去確認
- [x] 計畫定位，與 vTaiwan 差別？ (lloyd add 我們不是 vTaiwan)

**Comment by aelcenganda** [comment]
@lloydhuang 會先去 survey vTaiwan 的討論狀況。可以去 g0v slack #vTaiwan channel 問

**Comment by hychen** [comment]
@lloydhuang  還需要加 github, hackfoldr, slack 的進入點

**Comment by aelcenganda** [comment]
已補
