### ISSUE TITLE
Implement the map detail droplist

### ISSUE THREAD

**Issue by caasi** [SenseTW/sensetw#273]
![2018-09-11 17 07 33](https://user-images.githubusercontent.com/1164470/45350267-eb065880-b5e5-11e8-8292-7e43bd3e162e.png)

右上角新增 "..." ，連到 map create 的 modal，可以 Edit Map details on Map

parent issue: #240

**Comment by aelcenganda** [comment]
目前在 m12-rest 上面，已經有 map name 和 description 點開 dropdown 後的 edit map detail 是空白的，麵包屑也沒有 DAshbaord 和 map name，是正常的嗎？


![2018-09-27 13 32 58](https://user-images.githubusercontent.com/9480974/46125046-e2ef1f80-c259-11e8-8003-41c5815843bf.png)

**Comment by caasi** [comment]
只有 https://m12-rest.staging.sense.tw/map/1dbab857-942d-41d0-baa1-82fa70b0d773 有這個問題，我再看看。

**Comment by aelcenganda** [comment]
Verified
