### ISSUE TITLE
Implement the advance accordion in the inspector

### ISSUE THREAD

**Issue by caasi** [SenseTW/sensetw#274]
![2018-09-11 17 15 16](https://user-images.githubusercontent.com/1164470/45350464-6e27ae80-b5e6-11e8-8abc-fa83efe114b5.png)

Inspector 有 advanced setting 收疊

parent issue: #240

**Comment by caasi** [comment]
現況：

![2018-09-20 04 14 21](https://user-images.githubusercontent.com/1164470/45778709-f283cc80-bc8b-11e8-9979-4675539d7d63.png)
![2018-09-20 04 14 52](https://user-images.githubusercontent.com/1164470/45778718-f7e11700-bc8b-11e8-8183-010a23afd0ee.png)

**Comment by aelcenganda** [comment]
有一點請幫忙修改一下：

1. 文字：Advanced

另外一個小 bug 看之後要不要修：
2. 打開 accordion 的時候，inspector 輸入框寬度有些微不同，會跳動。
![2018-09-20 09 58 08](https://user-images.githubusercontent.com/9480974/45791404-21b23200-bcbc-11e8-9819-5ad451ec8dc2.png)
![2018-09-20 09 58 17](https://user-images.githubusercontent.com/9480974/45791414-28d94000-bcbc-11e8-9794-588cce0fa270.png)
