### ISSUE TITLE
Implement the quote field in the inspector

### ISSUE THREAD

**Issue by caasi** [SenseTW/sensetw#275]
![2018-09-11 17 17 37](https://user-images.githubusercontent.com/1164470/45350575-afb85980-b5e6-11e8-9c18-97037f814e93.png)

Annotation 新增 Quote 欄位，隱藏 description

parent issue: #240

**Comment by Kanailly** [comment]
# UI
5 card types inspector layout with placeholder
https://zpl.io/2pdkEMN

**Comment by caasi** [comment]
Map 上的 card 在有 quote 時也要顯示 quote

**Comment by caasi** [comment]
補圖：
![2018-10-09 11 41 55](https://user-images.githubusercontent.com/1164470/46645699-b66fc780-cbb8-11e8-9f7b-fb37ee3be21f.png)
