### ISSUE TITLE
UI: edge 物件化

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#282]
# Job Story
When I draw a complicated map,
I want to specify the relation of two objects,
So that 
1. Others can better read through the map and understand the structure without my explanation.
2. I can identify the key flows, factors or roots

# Success Criteria
- Selection on Edge
- Open inspector when an edge is selected
- Edge direction
    -  no direction
    -  單向箭頭方向 x 2
    -  雙向箭頭
- 箭頭在 zoom in/out 要看得清楚
(ael: 建議箭頭可以放在線中段，不然不從節點連線看不到箭頭 e.g. democracy3 )
- Inspector:
   - title    
   - direction
   - tag
   - summary
   - creator
   - last updated by {who} at {time}
- Edit history
- Hover to show edge title (because the map will look too complicated with plain text aside)
- How to create an edge
    - fast and convenient to link two objects
    - able to Edit the edge in inspector without too many steps

# To be decided
- Edge type (support/against): 覺得 Colors on edges 實在整張圖太複雜太多顏色了，但是如果有兩種顏色可以明確好像也不錯。 => 先拆 type 和實線虛線
- unique url?

# Schedule
- 9/27（四） UI sync：概念確認
- 10/1（一）實體 cowork： wireframe
- 10/3（三）UI sync（可以提早一天嗎？）realUI

# Out of Scope
2. Multiple edges between two objects
3. Auto layout
4. 曲線
5. 從節點連線。因為使用者還要選從哪個節點很麻煩。
6. 說明文字配合 edge 自動調整方向、大小

# UI
https://zpl.io/2GOY794

**Comment by aelcenganda** [comment]
Democracy3 的箭頭
![image](https://user-images.githubusercontent.com/9480974/46129779-497c3980-c26a-11e8-91c1-589880e57775.png)

**Comment by Kanailly** [comment]
hover edge 顯示說明

**Comment by Kanailly** [comment]
如何判斷起跟始
箭頭怎麼顯示？ 目前線段端點是在物件中心，線段中間也需要顯示箭頭？

**Comment by aelcenganda** [comment]
問了芳睿之後，他說 support 和 against 的關係目前是用單箭頭（對應）和雙箭頭（互相反對）表示。例如人工生殖的利害關係人：https://realtimeboard.com/app/board/o9J_kzqyEfc=/

偶爾才會用到虛線：
在左邊的地震速報中用了虛線代表現在不存在但是未來想要有的資訊流。
https://realtimeboard.com/app/board/o9J_kz_SP_s=/

他可以接受 edge 說明要滑過去才看得到，如果是為了畫面簡潔的話。但對話中我覺得需要讓人知道這個 edge 有附註，不然很多箭頭我也不知道哪一些箭頭是特別有加字的。

**Comment by Kanailly** [comment]
## 討論紀錄
1. 需要跟pm5說要開edge的欄位，前端需要等欄位開好來動。
2. 箭頭方向預設沒有箭頭，方向Ａ預設用from > to，另一個方向Ｂ就是to > from。
3. 箭頭出現的地方：線段的1/3、2/3處
4. 倍率問題：跟目前edge線段一樣不縮放，edge箭頭大小大概在6~8px
5. edge的status：
> a) normal 
> b) hover
>> color : blueA 
>> 顯示跟whole picture一樣的藍色資訊框 
> c) select
>> color : blueB
>> 點兩下一樣可以叫出inspector
