### ISSUE TITLE
g0v Summit 宣傳

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#283]
- [x] Roundtable 簡報 @ael
- [x] BoF / Unconference：議題小聚 @lloyd
    - ael 不建議討論議題如何釐清，有直接針對主題的討論比較好，例如開放資料、網路中立性等，或是配合教育、工作、長照的主題，討論 AI 會對工作造成什麼影響，政府能做什麼之類的。
- [ ] 工具推廣：
    - g0v 黑客松關心議題整理 @雅鈞

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1100007

**Comment by lloydhuang** [comment]
### Goal: 
- 推工具：
   - 議題整理的使用者（把議題整理成一個 map）
   - 開發者：星星數
- 推討論方法，用一個議題做為討論主題 => 之後會參與科技社群討論的人，希望找到科技圈的意見領袖，可以持續深耕聯絡，可以做後續議題合作。議題：假新聞、山難、data for social good、未來新的教育/工作型態、區塊鍊治理。 => 未來可以有系列討論：以太坊、IOTA。（備案：網路中立性）人多直接拆組。 @hychen @lloydhuang @Rex @宏宏（工讀費？）
- 收名單：填 email（盒子，寫紙條以後丟進去），導流到 vTaiwan? ael 提議還是可以做 mailing list。

### To Do: 

#### 會前宣傳：
- [ ] Call 人：蔡執秘、以太坊、NCC @hychen
- [ ] Register on side event hackpad
- [ ] 之前創的 FB event 討論區貼文宣傳。
- [ ] New FB event ：COSCUP 活動 cover photo 改字 @kanail
- [ ] g0v Slack、g0v 後勤中心
- [ ] blog.sense.tw 介紹計畫 => 小班 + hychen 草稿， @lloydhuang 修正

#### 會中：
- [ ] 大場曝光：Roundtable: sense.tw x vTaiwan x PDIS x 沃草—公民之情討論: @ael
- [ ] 討論：Unconference (週日：60 min, 90 min), BoF (週五： 60 min) 議題釐清小聚： @lloydhuang
- [ ] 文宣品：貼紙（剩 40 張，加印 200 張）、酷卡（通用版的，[工具介紹、手冊介紹]、議題小聚介紹）@ael 提供上次稿件、@lloydhuang。
- [ ] 要整理 SOP => 直接放到手冊裡面
- [ ] 收集聯絡資料的方式？

**Comment by aelcenganda** [comment]
@lloydhuang 

g0v Summit 的 BoF、Unconferecne、lightning talk 報名方式：
https://beta.hackfoldr.org/g0v-Summit-2018-unconf/

**Comment by aelcenganda** [comment]
我先在 g0v.hackmd.io 開了一份文件區塊鍊治理夾入 hackfoldr 了。
https://g0v.hackmd.io/eVAyMba7TSy2PMDlsWQDKQ

**Comment by aelcenganda** [comment]
Roundtable:
https://g0v.hackmd.io/c/summit18/%2Flrjusrc0Q0u1Uciwol8RbA

Unconf
https://g0v.hackmd.io/eVAyMba7TSy2PMDlsWQDKQ#

**Comment by aelcenganda** [comment]
g0v summit recap:
Result:

1. 開了 mailing list，一人參加。 17 emails
2. 以太坊研究員A認為有達成跨領域有效對話，能跟與會者把區塊鏈治理釐清成三個層次。
3. 另一個苦主B在自己的 FB 轉貼了 sense 的 map，引出另一個以太坊研究員留言。

Lesson:

- 文化衝擊  - 對於不熟悉議題的人，要有人鼓勵他勇敢發言或是聽不懂名詞自己查)  -> 小天使制度 (芳睿回饋)
- 期望落差 - 對於有在辦工作坊的人會覺得要有會前會讓專家 inform -> 這就是會前會，meetup。
- 投影機要放上 sense map，才能讓人理解現在討論到哪。 -> (這次一開始沒說有共筆可以看，有人會跟不上) 宏宏現場記錄。
- Probably a more informed introduction is needed. Or starts it with term definition. syncing data is important. Finish informed discussion.
- 90 min is too short. Post-it is not suitable for larger group discussion.
- 釐清問題就花了近 40-60 min，加自我介紹 15 min。
- Need to iterate several times.
- 透過討論來名詞聚焦自己釐清比我們直接告訴他們好
- 出來講是好事
- 邊緣的人在 Google 名詞
- 面對面討論，不要像研討會聽講。
- 用麥克風可以控制大家不插話和速度變慢
- 需要有不同領域的橋接者，需要有人補充 information gap。能夠做轉譯
- 要把討論的東西定義更清楚
- 怕花很多時間在科普
- 須要有人會後整理連接議題脈絡
- 當主持人需要關心會衆狀況
- 大家會急著想講自己想講的事情
- 須要有人拋議題
- 需要讓大家知道共筆、線上空間讓大家可以丟資訊
- 後面還會不會繼續討論，怎麼讓他們自己在社群內組織
- 每次活動會做不一樣的事情，工具應該是讓大家可以快速進入議題的資訊入口。讓問題脈絡化。以 map 做 catch up 不錯。（女性主義者給問嗎）
