### ISSUE TITLE
SEO： 加總站 description

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#287]
# Job Story
When I heard sense.tw ( not online, no direct link),
I want to use my device to search and go to sense.tw website,
So that I can 
1. know what sense.tw is
2. try to use sense.tw.

# Success Criteria
1. sense.tw 網站內部 tags and headers
  - Google 搜尋結果有 description（ael 要給文字）
  - Google 搜尋結果有分標題： About、log in (ael 要給文字)
  - 目標 sense.tw, sense tw, sensetw, sense-tw 搜尋都到 sense.tw，不要到 GitHub issue
2. Google AdSense on sense.tw => to find which keywords and audience is interested in our website @aelcenganda
3. blog.sense.tw SEO setting @aelcenganda

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1281325

**Comment by caasi** [comment]
可能的參考資料：
* https://developers.google.com/search/docs/guides/intro-structured-data
* https://github.com/nfl/react-helmet/issues/333

**Comment by aelcenganda** [comment]
總站 Description:
Issue-policy mapping tool for online discussion. 議題釐清工具，社群協作讓政策 make sense。可以標注線上文件與網頁後，整理成便利貼心智圖，方便大量資料與網路意見，梳理議題架構一目了然。

不知道能不能做到這樣
![2018-10-03 13 33 39](https://user-images.githubusercontent.com/9480974/46391752-08c06c80-c711-11e8-8fde-708214439830.png)

拆成：

[About](https://about.sense.tw/)
sense.tw 不只做工具，也在做實體議題小聚的公民討論

[Blog]
sense.tw 工具開發、實體工作坊紀錄部落格

**Comment by caasi** [comment]
要看看怎麼讓 Google 爬蟲抓到 SMO 提供的內容。

**Comment by caasi** [comment]
先把靜態資料放回 staging 的 index.html 上了：

![2018-11-19 17 34 51](https://user-images.githubusercontent.com/1164470/48698208-796c0b80-ec21-11e8-9320-4fe01a8ac3a0.png)

**Comment by aelcenganda** [comment]
- [ ] search console: 先設定，然後再到 GA 裡設定連結，開資料螢光筆 @hychen
- [ ] 準備 sitemap XML @caasi 0.5

11/23 週五 Code review:
- 5 sec sync
- sitemap XML

**Comment by caasi** [comment]
[sitemap.xml](https://staging.sense.tw/sitemap.xml)

**Comment by hychen** [comment]
已設定google search console, 並提交 https://sense.tw/sitemap.xml

**Comment by aelcenganda** [comment]
要再回來看 Google 有沒有抓到

**Comment by aelcenganda** [comment]
Google 還沒抓到，但先關。resource 不足，wipe 掉。
