### ISSUE TITLE
GTM variables in data layer

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#288]
# Goal
PM workspace
https://github.com/SenseTW/sensetw/issues/256

# Success Criteria
1. userid
https://ithelp.ithome.com.tw/articles/10191438
   - userid tracking cross device 
https://www.optimizesmart.com/cross-device-tracking-with-user-id-in-google-tag-manager/
   - userid tracking cross subdomain: api.sense.tw, via.sense.tw, sense.tw => 還是用不一樣的 container id
https://ithelp.ithome.com.tw/articles/10191438
3. User sign-up success and error, log-in success and error
4. User log-in status as variable in Tag Manager (require codes in data layer)
https://ithelp.ithome.com.tw/articles/10192163
https://ithelp.ithome.com.tw/articles/10195163
6. Toolbar、Inbox、Inspector 等按鈕需要統一格式的 id, classes，這樣 GA 比較好分類。想要在 GA 呈現的樣子：
Category: Edit
Action: {{Click id}}Icon / delete
Label: {{Click class}} Toolbar
目前是 toolbar 和 inbox 有 id，但是格式不固定。Inspector 的各個輸入框需要指定 class, id，inspector submit 更改需要有 id，可以區分是 card or box 嗎？

6. Tracking action "dragging" 
   - Dragging counts
        - dragging map
        - dragging objects
   - Dragging distance distribution (nice to have)
   - Hover
https://ithelp.ithome.com.tw/articles/10192163

# Need backend:
1. Show individual Map Name in GA

# Out of Scope

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1212898

**Comment by aelcenganda** [comment]
10/8 前目標 "research" how to implement

**Comment by caasi** [comment]
@aelcenganda 找到的書：
  * [Practical Google Analytics and Google Tag Manager for Developers](https://www.amazon.com/Practical-Google-Analytics-Manager-Developers-ebook-dp-B01JC9LECC/dp/B01JC9LECC/)

TL;DR 版的參考資料：
  * [Google Tag Manager Micro Challenge](https://ithelp.ithome.com.tw/users/20107582/ironman/1471)

**Comment by aelcenganda** [comment]
先放了 edits 和 viewing 的 event，annotation 做了從 sensemap 到 via 這段，log-in 和 Dashboard 還沒弄完。

需要幫忙的地方：

1. 需要知道 sign up 和 log in 成功會傳什麼東西可以被 tracking。目前 built-in variable 能 track 有沒有按按鈕，但是 form submission 無法，也無法用抵達頁面。會想知道有多少人在 sign-in 那邊放棄了。
2. Inspector 的各個輸入框需要指定 class, id
3. Toolbar、Inbox 等按鈕需要統一格式的 id, classes，這樣 GA 比較好分類。想要在 GA 呈現的樣子：
   - Category: Edit
   - Action: Toolbar
   - Label: Icon / delete
（有在想 label 是不是要塞 userid，但應該可以用 dimension 解決）
4. Toolbar 點按鈕的位置不同，會有時候只抓到 text 沒有 id，有時候只抓到 id 沒有 text
5. 還是分三個 container，找到方法一起倒進 GA 了。

**Comment by caasi** [comment]
@aelcenganda:

你需要的使用者資訊我已經有了，只是還沒塞到你能取用的 `dataLayer` 中：
![2018-10-23 11 10 25](https://user-images.githubusercontent.com/1164470/47333239-be4d6280-d6b4-11e8-98f4-3d3ada52e353.png)

**Comment by aelcenganda** [comment]
sign up success 另開 issue 在 #342

**Comment by aelcenganda** [comment]
現在想要 GA 收到的資料長這樣，我希望 Category 我可以在 GTM 手動訂，但是 Action 和 Label 可以統一從 class, id or text 自動產生，看卡西覺得 action 和 label 要分別放 class, id or text 比較好。

Category: Edit 
Action: Delete
Label: Toolbar_btn

Category: Edit 
Action: Delete
Label: Inbox_btn

Category: Edit
Action: Submit
Label: Box_inspector

Category: View
Action: Zoom_in
Label: Tap

Category: View
Action: Zoom_in
Label: Toolbar_btn

GTM 後台的截圖：
![2018-10-26 13 04 12](https://user-images.githubusercontent.com/9480974/47545593-bfce9300-d91f-11e8-8dbd-08abb33690d6.png)

**Comment by caasi** [comment]
GTM 的 Javascript 變數看來可以從特定來源計算出新的值，我想我們可以在 class 中放上像是 `gtm-action--delete`, `gtm-label--inbox-submit` ，再生出我們要的值。

* https://www.apasters.com/blog/google-tag-manager-custom-javascript-variable-examples/

**Comment by aelcenganda** [comment]
週一結論：

不改 class，ID 統一格式： <ui component>__<element name>-btn

Inspector 的部分，希望輸入框 input 要能夠顯示是 Box title 還是 Card description。 update 的按鈕要可以知道是 Box, Card 還是 EDge

@aelcenganda  要出給卡西一張表。

**Comment by aelcenganda** [comment]
@caasi 我需要的 object ID，不一定要更新在這，有埋進去就好
https://docs.google.com/document/d/1eysXVHqb8_NEwrM44JXmGGy78VqnY9Ibnfm6tDgTvdw/edit#heading=h.8d3fdnwumtvr

**Comment by aelcenganda** [comment]
@caasi 想跟你確認，我這邊看「GA-Named Clicks-sensemap」是做在 GTM tag 上。會好的差別是什麼呢？因為我還是需要分別根據 Edit, View , Log in 開不同的 tag。是我一開始抓 trigger 的時候不是抓 ID 而是抓其他 class 或是 text 造成的嗎？

**Comment by aelcenganda** [comment]
看起來之前的舊資料錯誤是因為 GA 沒有即時更新和沒有什麼人上去用所以沒收到新資料造成的，剛剛仔細爬了一下有看到有收到正常資料的。

**Comment by caasi** [comment]
我覺得是最前面的 all clicks 把事件都吃掉了，但是 all clicks 並沒有用到我們寫的 javascript 變數。所以把他們都停掉才正常。

要開不同的 tag 可以按 named tag 那樣，把過濾 `sense-` 開頭的 id 改成你要的值，或是改用 regexp 過濾，例如只抓有 `edit` 或 `create` 的 id 。

**Comment by aelcenganda** [comment]
現在是三個 container：frontend, backend, via，都放了 Javascript 變數
