### ISSUE TITLE
BE: Map name and description of every map

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#305]
# Job story
When I share a map on social media, e.g. Facebook,
I want people to see the map image, map name, map description of the map,
So that people would be interested to click the link.

## Discussion in #192 
Several choices:

- Universal app. Caasi 說需要先請 backend 把 html 檔分出來，這個 sprint 先出全站。
- Run a preloader with phantomjs at backend and redirect robots to there. We only need one static HTML for each map
- Run a backend to render HTML headers only for robots.

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1341397

**Comment by pm5** [comment]
# Plan

1. [ ] Add proxy by @wenchen or change frontend architecture.
2. [ ] Add a small tool to return HTML for robots.
3. [ ] Tests.

**Comment by wenchen** [comment]
我在 nginx 會按照這個方式進行設置
https://gist.github.com/thoop/8165802

另外還有包含中國 Spider 的 User Agent 清單
`
"qihoobot|Baiduspider|Yahoo! Slurp|Yahoo! Slurp China|YoudaoBot|Sosospider|Sogou spider|Sogou web spider|MSNBot|ia_archiver|Tomato Bot"
`

**Comment by wenchen** [comment]
目前先實做了一個版本是把所有 Bot/Spider 的流量導入 Backend (URL不會改變)
https://github.com/SenseTW/sensetw/commit/b61d93efd43ad80239fe3ee52fe9526e7ae626a4

然後看 Backend 最後會採用哪種方式實作，我再來修改 nginx 的行為

**Comment by pm5** [comment]
Backend 接到 https://github.com/SenseTW/sensetw/tree/master/smo

**Comment by pm5** [comment]
等 @wenchen production 調整完就完成了

**Comment by pm5** [comment]
好了 https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fsense.tw%2Fmap%2F07802bfc-bb3d-4009-a92d-c7f29c47a1d7
