### ISSUE TITLE
FE: Edge 物件化

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#307]
# Job Story
When I draw a complicated map,
I want to specify the relation of two objects,
So that 
1. Others can better read through the map and understand the structure without my explanation.
2. I can identify the key flows, factors or roots

# UI
https://github.com/SenseTW/sensetw/issues/282
https://zpl.io/2GOY794

# Success Criteria
- selection on Edge
- open inspector when edge is selected
- Edge direction (no direction, 2 directions) and Edge type (support/against)
- hover to show edge summary

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1212903

**Comment by aelcenganda** [comment]
@caasi 現在 m14-edges 有 edge detail 了～～但是 New Card 和 New Box 會無法成功創建新的卡和 Box。

**Comment by aelcenganda** [comment]
今天討論：
1. edge 箭頭圓圈不跟著縮放
2. 我覺得箭頭位置應該還是在 edge 1/3, 1/2, 2/3 的地方（箭頭才會比較集中在中間，也比較不容易被裁掉。），如果技術沒有困難的話。

**Comment by caasi** [comment]
好喔～

![2018-10-20 00 27 13](https://user-images.githubusercontent.com/1164470/47231291-165b3f00-d3ff-11e8-928d-4724e7b7885a.png)
