### ISSUE TITLE
UI: Mobile design

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#308]
拆分/定義出在手機上使用的情境與需求並match到mobile 操作行為上。

# Job Story

When I open a link from social media on my phone,
I want to understand the issue, 

So that I can share it to other friends or continue to work on laptop.

# Success Criteria

- Mobile Bounce rate 63% -> 40 %

  mobile aveg. time: 00:54 -> 3:00

- Tap events

- **Map name and map details modal -> 是議題地圖，可以至桌機編輯  -> map name + map**

- （正常程序：Map name and detail modal -> (要放 Full history 嗎？）-> map name + map）

## Dashboard

- Enter a map, share, map details
- (Search)
- 隱藏 create map

## Map

- Map name and map details
- Zoom in/out (雙指)
- 拖曳畫布
- **Hover 怎麼辦？長按？**
- Long press to show object details
- Navigation bar:
  - Go back to dahsboard
  - Easy to share the map and any objects
  - (Search)
  - more: map details, help
- 隱藏 update、toolbar、inbox、annotation
- 隱藏 log-in/out
- Toolbar 保留 open box 和倍率顯示
- 保留麵包屑

# Out of Scope

- Edit and drag object on mobile browser
- Log in on mobile browser (no feature difference whether the user is logged in or not)

# To be Discussed

- Allow tablet to edit and add new cards?(only 3% from tablet for the past 3 months) Mobile: 25-48%。要決定要跟 mobile 還是要跟 laptop。可以先跟 phone 一樣不能編輯，因為還沒設定怎麼用 tap event 多選來連線、加 box。
- 如果要用 mobile 長按跳出 inspector，能不能桌機版也是用跳出 modal 辦理？modal 的好處是可以打完收起來很清楚在處理哪個，壞處是會把 map 蓋掉，不知道相對位置。

# UI notes

RWD 分段點
最小:320
其餘設定：https://github.com/SenseTW/sensetw/issues/252

# wireframe
https://zpl.io/25w8BQ3

# UI 排版好的
https://zpl.io/aBqrO9m
https://zpl.io/anYwrNl
https://zpl.io/beLZgrD
https://zpl.io/agrwGy1
https://zpl.io/amyQBr6
https://zpl.io/29Pr58A
https://zpl.io/aXk0WgX
https://zpl.io/awmv0ZN
https://zpl.io/2jPzlmO
https://zpl.io/2EKrwDg

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1341977

**Comment by aelcenganda** [comment]
UI sync 討論有提到：

1. 要跳出提醒要到電腦才能編輯的頁面

ael: 突然覺得一進入 map 的時候，應該要先跳 map name and description 的 modal，然後再進 map，要第一次長按檢視內容時，才顯示要到電腦才能編輯。

**Comment by aelcenganda** [comment]
mobile design 草稿

![image](https://user-images.githubusercontent.com/9480974/47952964-ffa30500-df33-11e8-9813-df62bfcf0938.png)

**Comment by aelcenganda** [comment]
RWD 分段點：
瞄準 iPhone，以 iPhone 7 作為 size 預排尺寸。 750 *1334 pixel
http://konigi.com/links/ultimate-guide-to-iphone-resolutions/
因為 GA 後台數據前幾名是 iPhone。



Notice: 

1. 須考慮從 social media 打開，例如從 Facebook 打開，畫面上方會被切掉一塊。
2. 進入 map 的預設倍率
3. 不讓編輯 inspector，但是要可以滾動閱讀 decription。
4. 手機 loading 速度是一切啊
5. 盡量不要跳頁，在 map 上操作維持同一頁。



Features:

- View：user 最需要看到的 info 是什麼？
  - Map description: What is this link
    - Map name and map details
    - How many cards/boxes, how many contributors
    - last upadted time
  - Whole picture（實際上會太小）
  - 主要閱覽可以開始的卡片
  - 關係圖
  - Share：單張 Card/Box 或整張 map
  - link to original source，如果不要 via 變得很複雜，是不是不要放在 via 上？那原本有註解的要怎麼連過去呢？
  - 卡片細節

Advantages：

- 連到原始連結（網頁要跳頁還是要同一個頁面），但是 mobile 似乎不太適合一直跳頁
- Easy to share a card or a information link

Benefits：

- 拆解議題架構

Users

- 輕度 user：閱讀理解 map 的意思，並且願意 share。
- 重度 user：用手機查看 map 有哪些更動（做在第二層，例如 map detail 的 drop down 可以連到 map history）

**Comment by aelcenganda** [comment]
功能拆分：
1. 進入 map 頁面: map detail modals
2. 畫面拖曳、放大縮小，解析度、留哪些 toolbar/倍率
3. 檢視細節、檢視 Full history
4. Share btn on card, link to original source.
5. (search design) 這個 sprint 先不做

**Comment by aelcenganda** [comment]
週四 wireframe 畫完
週一 interaction map mobile 版
週四 細項核對

**Comment by Kanailly** [comment]
https://zpl.io/25w8BQ3

**Comment by Kanailly** [comment]
https://zpl.io/aBqrO9m
https://zpl.io/anYwrNl
https://zpl.io/beLZgrD
https://zpl.io/agrwGy1
https://zpl.io/amyQBr6
https://zpl.io/29Pr58A
https://zpl.io/aXk0WgX
https://zpl.io/awmv0ZN
https://zpl.io/2jPzlmO
https://zpl.io/2EKrwDg
