### ISSUE TITLE
Implement edge hovering and selected states

### ISSUE THREAD

**Issue by caasi** [SenseTW/sensetw#313]
讓 edge 在 hover 和 select 時有不同狀態。

parent issue: #307

**Comment by caasi** [comment]
![2018-10-22 06 09 58](https://user-images.githubusercontent.com/1164470/47273080-2b7fcb80-d5c1-11e8-8bfa-9d3e2d4719fa.png)

**Comment by aelcenganda** [comment]
@caasi 能否做到沒有寫 extra field 的 edge 不會 hover 顯示呢？

**Comment by caasi** [comment]
可～
