### ISSUE TITLE
資通訊社群議題關心清單

### ISSUE THREAD

**Issue by aelcenganda** [SenseTW/sensetw#316]
＃ Success Criteria
1. 盤點出每個社群的主要數位討論空間 ( facebook group or telegram )。
2. 2016 年到 2018 年的公共議題相關討論串。

**Comment by changyajune** [comment]
https://docs.google.com/spreadsheets/d/1cB07Cy4rsQCqb9FB4Ju_KoMc6AHOammQ28AQei8-Gn0/edit#gid=0

**Comment by aelcenganda** [comment]
新開一個 tab，讓每個儲存格內保持乾淨，寫一件事、一個連結、一個數字，儲存格內不要出現多餘標點符號。

| 社群 | 十個重要議題 |討論串聯結| 回應數 | 
|----|----------------|----------|-------|
|社群 A | 議題 A | one url | 8 |
|社群 A | 議題 B | one url | 8 |
|社群 A | 議題 C | one url | 8 |

要分三階段給 hychen


- [ ] 10/30 20 個
- [ ] 11/6 20 個
- [ ] 11/13 28 個

**Comment by aelcenganda** [comment]
- [ ] 12/3 50 個

- [ ] 找工讀生實體 co-work @aelcenganda 
- 11/26 （一）14:00 - 18:00 實體 co-work (4hr x 4)
- 12/1 （六）10:00 - 18:00 中間 2 hr 休息 (6 hr x 6)

**Comment by changyajune** [comment]
# Success Criteria Updated
1) 繼續盤點完目前手上的9(共19)個社團
2) 依照報章雜誌種類、官網消息、消息發布與接收時間等做分類*

歸類參考可見賴志遠，2015，STPI

**Comment by aelcenganda** [comment]
接下來要做議題分類，先不盤點了
