### ISSUE TITLE
11 月 Mopcon 高雄議題小聚規劃

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#317]
1. 擺攤
2. 不報名 unconf（shawn 想報）

**Comment by lloydhuang** [comment]
收到攤位錄取通知，大會通知 11/02 場佈。(應該還是 11/03 直接到會場場佈)

**Comment by aelcenganda** [comment]
差會議記錄報告

**Comment by lloydhuang** [comment]
MOPCON 擺攤及 unconf https://twist.com/a/31280/ch/88845/t/502454/c/49131733
