### ISSUE TITLE
10/31 台南議題小聚規劃

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#319]
10/31 晚上，好想

**Comment by lloydhuang** [comment]
10/31 台南 facebook events https://www.facebook.com/events/497496590751733/
仍在討論議題主題。二個方向 (1) 教育。(2) 台南數位治理。

**Comment by lloydhuang** [comment]
談數位治理，與選舉。狀況不好，來的人斷斷續續，總共 7 位。討論品質滿差的。說工具很難使用在政治情境上。

**Comment by aelcenganda** [comment]
差會議紀錄

**Comment by lloydhuang** [comment]
台南小聚會議記錄 https://twist.com/a/31280/ch/88845/t/502454/c/49131028
