### ISSUE TITLE
Backend onboarding 文件

### ISSUE THREAD

**Issue by aelcenganda** [SenseTW/sensetw#341]
1. backend 架構 => @pm5 @wenchen 
2. Onboarding 文件，e.g. 資料 structure、lifecycle, entry point

**Comment by aelcenganda** [comment]
會放在 Repo 裡面 doc 的目錄

**Comment by pm5** [comment]
已寫好在 https://github.com/SenseTW/sensetw/tree/doc/doc

**Comment by pm5** [comment]
已併入 wiki。
