### ISSUE TITLE
行銷計畫

### ISSUE THREAD

**Issue by aelcenganda** [SenseTW/sensetw#344]
https://docs.google.com/document/d/1cjL5n-zHP3sXRO8KlukY_Bz43Z1mxKzsoJbR0_q0Z3k/edit

**Comment by aelcenganda** [comment]
第一張 map 可以從遠距工作出發，可從 g0v hackpad 找，或是 vTaiwan 找。

**Comment by hychen** [comment]
my assignment to @aelcenganda 
1. 整理 10 個可能議題清單。
2. 整理有關心議題的可接觸者的清單。
3. 需要自己整理一個議題 map，要達到 PMPC 的層級。

**Comment by hychen** [comment]
缺 1. 10 個可能議題清單。 2. 整理有關心議題的可接觸者的清單。

**Comment by aelcenganda** [comment]
後來是整理了核能公投的兩場辯論： unique PV 173
https://sense.tw/map/a6a2d883-35e0-4229-a483-a6ea14c04c59

**Comment by aelcenganda** [comment]
# 10 個可能議題清單

進行中
- [議題小聚：文化組織如何數位開放](https://www.facebook.com/events/2284702438419942/)
- SITCON 資訊教育：中學生資訊素養，Telegram 群組，會辦活動

可整理：
- 遠距工作相關法規（vTaiwan 過去有討論過）：Remote Taiwan 社群
- 網路中立性（繼續補充資料放上去）：孝先、Irvin、網路治理論壇
- 封網：數位人權/網路治理 Telegram
- g0v 議程整理： g0v 社群
- 將資訊社群關心議題 spreadsheet 轉成 sensemap：https://docs.google.com/spreadsheets/d/1cB07Cy4rsQCqb9FB4Ju_KoMc6AHOammQ28AQei8-Gn0/edit#gid=696797850
- 政府跨部門資料協調（vTaiwan 進行中）
- 裸照外流事件（vTaiwan 進行中）：小蟹、雨蒼、womany
- 社會企業：唐鳳辦公室、余宛如辦公室、社企流
- NGO 數位協作工具： NPOst 公益交流站
- 數位國家計畫
- 台北市智慧城市

Note: 一張 map 要花 2-3 天，剩下的時間要 documentation ，可能只能再整理兩個 map

**Comment by aelcenganda** [comment]
結案順便做 map => 資訊社群關心議題，e.g. cc 創用社群、Mozilla。優先把 spreadsheet 做完，然後有空再整理成 map
