### ISSUE TITLE
Annotation and highlights can't be saved on Client

### ISSUE THREAD

**Issue by aelcenganda** [SenseTW/sensetw#348]
**Describe the bug**
我在 Client 註記和畫重點，部分 annotation 有進到 map，但是在 client 重新整理後都不見了。

**To Reproduce**
1. Go to https://via.sense.tw/https://file.sense.tw/e5a11659dbc58e752bc4f69a5308c47b/Reflecting%20on%20reflection-%20framing%20a%20design%20landscape.pdf

2. Select texts and highlight/annotate
3. post annotation to sense.tw 協作模型分析
4. Go to https://sense.tw/map/e1f2bd16-378f-4abc-a689-ade6937075e2
5. See annotation in inbox
6. Go back to  https://via.sense.tw/https://file.sense.tw/e5a11659dbc58e752bc4f69a5308c47b/Reflecting%20on%20reflection-%20framing%20a%20design%20landscape.pdf
7. Refresh
8. There is no annotation in this group.

**Expected behavior**
See just added annotations

**Screenshots**
![2018-10-30 20 51 19](https://user-images.githubusercontent.com/9480974/47719350-d6f5e380-dc85-11e8-97d1-803ad816f4b1.png)
![2018-10-30 20 52 08](https://user-images.githubusercontent.com/9480974/47719357-df4e1e80-dc85-11e8-942c-ea22919c8f24.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Google Chrome 目前是最新版本
版本 70.0.3538.77 (正式版本) (64 位元)

**Comment by pm5** [comment]
看起來後端處理 query 參數有點問題。Client 會發 https://api.sense.tw/h/api/search?_separate_replies=true&group=e1f2bd16-378f-4abc-a689-ade6937075e2&limit=200&offset=0&order=asc&sort=created&uri=urn:x-pdf:c8ed66cbf43084ea78419f10d67ac409&uri=https://file.sense.tw/e5a11659dbc58e752bc4f69a5308c47b/Reflecting%20on%20reflection-%20framing%20a%20design%20landscape.pdf。如果查 https://api.sense.tw/h/api/search?_separate_replies=true&group=e1f2bd16-378f-4abc-a689-ade6937075e2 是有結果的。

**Comment by pm5** [comment]
修掉了一個 client 會多送一個 `uri` 參數的問題。另外一個問題應該是 PDF 檔名有空白字元，於是上傳後的 URL 就會有空白字元，然後中間應該某個地方的 escape 沒有做好

**Comment by aelcenganda** [comment]
@pm5  現在是 highlight 正常、tag 正常，但是 annotation 的註記存不起來。但從 sensemap 編輯的註記，會同步到 client 上。這個對現在 annotate 辯論逐字稿然後補連結滿重要的。

**Comment by voidlps** [comment]
looks like client-side issue, text is not posted?
![image](https://user-images.githubusercontent.com/3744683/48468104-ea788100-e825-11e8-8094-563bce2cfde3.png)

**Comment by voidlps** [comment]
目前看到的問題應該是這裡的 toAnnotation 沒有把 o.text 指派到 card.summary 裡:
https://github.com/SenseTW/sensetw/blob/master/sensemap-backend/src/hypothesis/annotations.ts#L44

**Comment by caasi** [comment]
staging 上會動了。
