### ISSUE TITLE
新建的卡片內容修改後，Hover 仍為 New Card

### ISSUE THREAD

**Issue by aelcenganda** [SenseTW/sensetw#349]
**Describe the bug**
在 10/30 後新建的卡片內容修改後，Hover 過去仍顯示為 New Card 而未有新內容。

**To Reproduce**
1. Go to a Map
2. Create a New Card
3. Edit summary and update the card.
4. Go to Zoom out percentage < 60%
5. Hover over that car
6. see only "New Card"

**Expected behavior**
see new contents

**Screenshots**

![2018-11-04 07 15 39](https://user-images.githubusercontent.com/9480974/47963983-883ba700-e001-11e8-9843-b717e347c062.png)
![2018-11-04 07 15 53](https://user-images.githubusercontent.com/9480974/47963986-8c67c480-e001-11e8-9177-d82e72419522.png)

**Desktop (please complete the following information):**
 - MacOS:
Google Chrome 目前是最新版本
版本 70.0.3538.77 (正式版本) (64 位元)

**Comment by caasi** [comment]
不再是 "New Card" 了：

![2018-11-11 21 29 48](https://user-images.githubusercontent.com/1164470/48313540-f9c6b700-e5f8-11e8-8c06-0db5c6ad30fd.png)
