### ISSUE TITLE
Summary to show ( max 250 cha.)

### ISSUE THREAD

**Issue by aelcenganda** [SenseTW/sensetw#353]
In inspector:

Summary (max 250 characters)

**Comment by caasi** [comment]
按 backend 資料庫欄位的限制，加上檢查了：

![2018-11-11 22 17 29](https://user-images.githubusercontent.com/1164470/48314110-a86df600-e5ff-11e8-84e9-e7dfe4de7b30.png)

**Comment by aelcenganda** [comment]
@caasi description 沒有要加字數限制喔，description 不限字數，是要在 summary 旁邊加字數限制標示而已

**Comment by caasi** [comment]
可是 backend 的 description 有字數限制，超過應該存不進去 XD

**Comment by aelcenganda** [comment]
我以為在這個 issue 把 description 字數上限拿掉了，才會有很長的卡。
https://github.com/SenseTW/sensetw/issues/258

**Comment by caasi** [comment]
好的，我搞錯了，晚上改回來

**Comment by caasi** [comment]
已恢復：

![2018-11-16 09 12 19](https://user-images.githubusercontent.com/1164470/48591652-c335c700-e97f-11e8-8d5b-4d9eabcdbc20.png)
