### ISSUE TITLE
almost-realtime collaboration

### ISSUE THREAD

**Issue by caasi** [SenseTW/sensetw#355]
**Is your feature request related to a problem? Please describe.**
sensemap 需要即時協作功能，但是 CRDTs 的工很大。

**Describe the solution you'd like**
* pulling
* broadcast users' selection to everyone

這樣至少在編輯的人可以看到哪些東西正在被其他人編輯，主動避開。

**Additional context**
目前都放在這個 branch ： https://github.com/SenseTW/sensetw/tree/auto-update

**Comment by caasi** [comment]
目前還無法同步新增與刪除的卡片。

新增部分考慮每次都拉 map 下的 object, card, box, edge ids ，比較後決定該新增什麼與刪除什麼。

**Comment by aelcenganda** [comment]
已推上 production
