### ISSUE TITLE
when user make annotation in via.sense.tw, markdown-body is not saved

### ISSUE THREAD

**Issue by voidlps** [SenseTW/sensetw#357]
**Describe the bug**
When user tries to make annotation by uploading document to via.sense.tw, and then highlight an text then post annotation, the body will disappear.

However, if user tries to update summary in Dashboard, it will be displayed correctly in via.sense.tw

**To Reproduce**
1. Upload pdf to via.sense.tw
2. select Dashboard of this source
3. select text and add annotation
4. input some text in the text editor, 
5. Post to the dashboard

**Expected behavior**
Text is saved and clearly displayed in both Dashboard and Via

**Desktop (please complete the following information):**
- Google Chrome | 70.0.3538.102 (Official Build) (64-bit)
- Revision | 4bbeebac88fdc09c97265e47c205868bbd190497-refs/branch-heads/3538@{#1077}
- OS | Linux
- JavaScript | V8 7.0.276.38

**Comment by voidlps** [comment]
looks like duplicate to #348

**Comment by caasi** [comment]
Close for the duplication.
