### ISSUE TITLE
Hypothesis and Sensemap account integration

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#37]
sense.tw + h.sense.tw 的帳號連動

# Prerequisites

* https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1049039/detail
* https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1049093/detail

# Success Criteria
1. 在 sensemap 建的新帳號，會在 hypothesis 自己開一個新帳號
2. 同步登入狀態

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/951467

**Comment by pm5** [comment]
Deployed to https://via.sense.tw/
