### ISSUE TITLE
議題小聚操作方式 in 結案報告

### ISSUE THREAD

**Issue by aelcenganda** [SenseTW/sensetw#375]
1. [x] 會前流程、會中流程、會後流程
2. [x] 工作人員配置
3. [x] 需要設備
4. [x] 應用場景

12/7 號 check 草稿

**Comment by hychen** [comment]
麻煩參考一下公民科技政策討論機制與工具裡面的格式再補充一下
https://docs.google.com/document/d/1Wpsjzg4-RngPMoi7yLrgrzw916DtJPNhb77ONLRaJ_Q/edit

**Comment by lloydhuang** [comment]
我可以開一個新檔案，用這個格式把舊的資料重新填進去，在看有缺什麼在補進去好嗎？ 因為這個格式跟先前的大綱部份大多重疊，角度不太一樣。

**Comment by hychen** [comment]
ok
Best regards,
Hsin Yi Chen

**Comment by lloydhuang** [comment]
Hello HyChen,

表格大都填完了，但有一欄不知道要怎麼寫。
**應用案例與成果** 這個你有什麼建議呢？ 字面上的義意是要（近年台灣應用案例與計畫團隊之活動統整）

你有什麼建議？
Best Regards
Lloyd

**Comment by lloydhuang** [comment]
done
