### ISSUE TITLE
Inspect a Card which is in Map Inbox

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#38]
# Job Story
當我對一張 Card 的內容感興趣時，
我會想要可以讀更多 Card 的細節，
讓我可以決定這張 Card 要被加到 Map 哪裡。

# UI 
TBD

# Success Criteria
1. 在 map inbox 點選卡片後可以開啟 Card detail 側邊欄
2. 可以關掉側邊欄
3. 跟在 map 上的操作一樣

# Out Of Scope
1. 浮動顯示在卡片旁邊

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/958196

**Comment by pm5** [comment]
Duplicate #40?
