### ISSUE TITLE
Create a Card in Map Inbox

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#39]
# Job Story
- When: 我發現缺乏某重要資訊的卡片時/當我獲得有用的新資訊，卻還不知道要放在 Map 上哪裡時，
- I want to: 我會想要在 Map Inbox 新增 Card，
- So that 我和其他人可以收錄這個重要資訊，成為議題分析的基石。

# UI 
TBD

# Fields
## Card Base (object)
使用者可以編輯的：
+ summary:   (string, required) - the summary of a card. Max 150 characters.
       重點：AI 技術跟不上
+ tags: 產業, 人才 (string) - tags separated by comma.
+ source_title:  (string) - the title of the source. 資料來源 Max 50 characters.
      【AI全面啟動Ⅱ：台灣企業行不行？關鍵在老闆｜天下雜誌】
+ source_link: https://o.sense.tw/abcd (string) - the source url of the key information. 
+ description (string) - the description of a card. Max 1000 characters.
        真正的問題是，很多想做AI的人，不知道自己沒跟上最新進展。
        常常與科技大老開會，這位學者發現，台灣科技界研發產品，習慣先把產品規格開好，然後大家才去做。但AI研發必須一步步改善其精準度，有點像是做實驗，一步步排除問題，被市場接受了，就可以成為規格制定者。
        「很多基礎技術在網路上都是開源資訊，關鍵在要有真實的數據去玩，非常動態地從頭到尾調整，來找到AI產品的被使用者喜愛的關鍵點，」他直言，台灣也缺少有經驗的AI專案經理。
+ type (string) - Card type: Q, A, Note, Normal.
+ said_by (string) - said by who. 
+ stakeholders: 大學, 半導體, IT company (string) - involving stakeholders, separated by comma. 目的：意見多元性與可信度，目前為單純欄位，未來再決定要不要做成 tag 或是其他連結應用。

## Card [/cards/{card_id}]
A card represents a key information extracted from a source. Sources are anything on internet, such as PDF, webpages, blog post, 
video or audio.

+ Attributes (Card Base)
    + id: 250FF (string, required) - the id of a card. Max 50 characters
    + created: 1415203908 (number, required) - time stamp.
    + last_updated: 7815203908 (number, required) - time stamp.
    + ~~owner (User) - who owns this card.~~
    + ~~maps (array[Map]) - the maps a card belongs to.~~
    + ~~boxes (array[Box]) - the boxes a card belongs to.~~

## 預填欄位顯示（引導使用者使用）
- summary: 說重點
- tags: tag1, tag2, tag3
- source_title: 資料來源，e.g. 【AI全面啟動Ⅱ：台灣企業行不行？關鍵在老闆｜天下雜誌】
- source_link: https://o.sense.tw/abcd
- description: 資料原文摘錄與補充資訊
- type (string) - Card type: Q, A, Note, Normal.
- said_by: 誰提出的意見？ e.g. XX 大學校長 XXX
- stakeholders: 誰會被影響？（用逗號隔開）e.g. 經濟部, 半導體廠商, 大學

# Success Criteria
- [x] 新增 Card 在 Map Inbox
- [x] 新增 Card 跟在 Map 的操作一樣
- [x] 使用者不會搞混是新增在 Map 還是新增在 Map Inbox 裡
- [x] 新增的 Card 會排在最前面，自動跳到第一頁
- [x] inbox 第二頁之後不顯示 new card 的按鈕。
- [x] 新增的卡片的 Summary 預設寫上"New Card" 的字串。
- [ ] 自動打開 New Card 的 inspector

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/958187

**Comment by aelcenganda** [comment]
1. 新增卡片的時候，如果正在看第二頁，會沒看到新增的卡片。然後狂按 （跪）
2. 新增卡片若是沒有驚爆上師的 tag，要如何讓使用者知道可以編輯卡片？就會是白白一張？

**Comment by aelcenganda** [comment]
# Success Criteria
1. 新增的 Card 會排在最前面，自動跳到第一頁
5. inbox 第二頁之後不顯示 new card 的按鈕。
6. 新增的卡片的 Summary 預設寫上"按此編輯新卡片" 的字串。
7. 先出現一張卡片框框，再到側邊欄填內容

**Comment by hychen** [comment]
自動打開 New Card 的 inspector 這個行為很奇怪，因為打開 inspector 後，使用者不曉得是選到哪一張卡片。

建議之後 inbox 的 UX 重新設計，直接改成 db-click 後在inbox 修改 summary。

**Comment by hychen** [comment]
可以在這邊看到實作的東西

https://39.staging.sense.tw/map/12495dd1-c79b-4292-b413-98e81be4beda
