### ISSUE TITLE
Update a Box on Inspector

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#4]
# Job Story
- When: 
  1. 當我發現有更適合的 Box 名稱
  2. 想要補充說明 Box 時
- I want to: 
  1. 我會想要在 Map 上修正 Box title, summary, tags
  2. 我會想要在 Box 打開的頁面修正 Box title, summary, tags
- So that: Box 可以更精確表達有意義的概念，讓 Map 讓人看得懂

# UI 
https://zpl.io/VK0yenP
從前叫做 description

# Fields
## Box Base
使用者可以編輯的：
+ title: 缺乏跨界人才 (string, required)  - the title of a box. Max 40 characters.
+ summary: (string) - Summary of a Box. Max 150 characters.
+ tags: tag1, tag2, tag3 (string) - Tags on a Box, separated by comma.

# Success Criteria
1. 在 Map 上點選 Box 編輯後，可以在 Inspector 編輯 title, summary, tags
2. 在 Box 打開的頁面時可以點選 {XX}編輯該 Box 的 title, summary, tags

# Out Of Scope

# 待討論

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/895095

**Comment by aelcenganda** [comment]
Box 的欄位需要加上 tags，以及 required 欄位，跟 title （required）要放在 summary 前面。
