### ISSUE TITLE
Edit a Card in Map Inbox

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#40]
# Job Story 1 (Quick Edit)
- When: 我瀏覽 Map Inbox 顯示的 Card 主要資訊
- I want to: 我想要更正 Card 在 Map Inbox 顯示的主要資訊：Summary, Source Title, Tag, Card Type
- So that: 卡片上的資訊更能幫助我在 Map 上分類卡片

# Job Story 2
- When: 我閱讀 Card 的細節側邊欄時
- I want to: 我想要在細部欄位上更正錯誤、補充說明、加入連結、加 tag 、加利害關係人
- So that: 卡片上的資訊更豐富更正確，可以幫助之後閱讀卡片的人理解卡片意義。

# UI 
TBD

# Success Criteria
1. 

# Out Of Scope
1. 點擊兩下直接在 inbox 顯示 的 quick edit

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/958192

**Comment by pm5** [comment]
Used a hack from https://github.com/Semantic-Org/Semantic-UI-React/issues/2207
