### ISSUE TITLE
Delete a Card in Box

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#43]
# Job Story
- When: 我覺得這張 card 不需要出現在 Map 上，
- I want to: 我會想要從 Map 上刪掉這張 card，
- So that 不會佔 Map 的空間。

# UI 
https://app.zeplin.io/project/5ae1980f28546a5bbf985063/screen/5ae198fb0d87b4cc088b1ea3

# Success Criteria
1. 在 Box 選取一張 Card ，刪除。
2. Card 在 Map inbox 裡仍可以找到

# Out Of Scope
1. Undo
2. confirmation of delete
3. multi-select to delete

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/960108

**Comment by pm5** [comment]
落差：卡片還不會到 Map Inbox
