### ISSUE TITLE
Create a Card in Box

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#44]
# Job Story
- When: 我想要新增分析議題所需的重要資訊時，
- I want to: 我會想要在 Box 頁面上新增 Card，
- So that 我和其他人可以收錄這個重要資訊，成為議題分析的基石，不需要跑到 Map 上開卡再加進 box 裡。

# UI 
https://zpl.io/V189PMX
https://zpl.io/2y7WrXG

# Fields
## Card Base (object)
使用者可以編輯的：
+ summary:   (string, required) - the summary of a card. Max 150 characters.
       重點：AI 技術跟不上
+ tags: 產業, 人才 (string) - tags separated by comma.
+ source_title:  (string) - the title of the source. 資料來源 Max 50 characters.
      【AI全面啟動Ⅱ：台灣企業行不行？關鍵在老闆｜天下雜誌】
+ source_link: https://o.sense.tw/abcd (string) - the source url of the key information. 
+ description (string) - the description of a card. Max 1000 characters.
        真正的問題是，很多想做AI的人，不知道自己沒跟上最新進展。
        常常與科技大老開會，這位學者發現，台灣科技界研發產品，習慣先把產品規格開好，然後大家才去做。但AI研發必須一步步改善其精準度，有點像是做實驗，一步步排除問題，被市場接受了，就可以成為規格制定者。
        「很多基礎技術在網路上都是開源資訊，關鍵在要有真實的數據去玩，非常動態地從頭到尾調整，來找到AI產品的被使用者喜愛的關鍵點，」他直言，台灣也缺少有經驗的AI專案經理。
+ type (string) - Card type: Q, A, Note, Normal.
+ said_by (string) - said by who. 
+ stakeholders: 大學, 半導體, IT company (string) - involving stakeholders, separated by comma. 目的：意見多元性與可信度，目前為單純欄位，未來再決定要不要做成 tag 或是其他連結應用。

## Card [/cards/{card_id}]
A card represents a key information extracted from a source. Sources are anything on internet, such as PDF, webpages, blog post, 
video or audio.

+ Attributes (Card Base)
    + id: 250FF (string, required) - the id of a card. Max 50 characters
    + created: 1415203908 (number, required) - time stamp.
    + last_updated: 7815203908 (number, required) - time stamp.
    + ~~owner (User) - who owns this card.~~
    + ~~maps (array[Map]) - the maps a card belongs to.~~
    + ~~boxes (array[Box]) - the boxes a card belongs to.~~

## 預填欄位顯示（引導使用者使用）
- summary: 說重點
- tags: tag1, tag2, tag3
- source_title: 資料來源，e.g. 【AI全面啟動Ⅱ：台灣企業行不行？關鍵在老闆｜天下雜誌】
- source_link: https://o.sense.tw/abcd
- description: 資料原文摘錄與補充資訊
- type (string) - Card type: Q, A, Note, Normal.
- said_by: 誰提出的意見？ e.g. XX 大學校長 XXX
- stakeholders: 誰會被影響？（用逗號隔開）e.g. 經濟部, 半導體廠商, 大學

# Success Criteria
1. 有互動區可以輸入資訊在 Card 上
2. Required 欄位未填不允許創立新卡片
3. 點選新增卡片按鈕後，新增 Card 在 Box 上
2. 新增的 Card 出現在畫面中央偏下，不會被側邊欄擋到
3. Card 的大小不因為字數改變

# Out Of Scope
1.

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/960103

**Comment by aelcenganda** [comment]
實作與 spec 落差：

1. 卡片會加到 Map 那一層（已改）
2. 新增卡片的位置在中間
3. required 欄位與欄位順序
