### ISSUE TITLE
Leave a Box to Map

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#46]
# Job Story
- When: 我看完 Box 內容
- I want to: 回去看 Map
- So that: 去把這個 box 放到對的位置上

# UI 
https://zpl.io/VK0yenP

# Success Criteria
1. 在 Box 頁面上可以點選退出回到 Map

# Out Of Scope
1. Zoom in/out

# 待討論

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/960202

**Comment by aelcenganda** [comment]
上個 sprint 已經做完了，只是補開 issue
