### ISSUE TITLE
Select a Card to assign it into a Box

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#47]
# Job Story
當我在 map 上瀏覽卡片時，
我會想要選取一張 card 加入一個 box，
讓我可以幫卡片分類

# UI 
先不拖拉，先用 assign 的，但是 grouping method 要再定義
https://zpl.io/agn6wg1

# Out Of Scope
1. 拖拉卡片進 box
3. 卡片消失跟出現的動畫

# Success Criteria
1. 可以選取一張卡片
2. 可以取消選取單張卡片
4. 可以在 map 頁面，點選 box，加入一張卡片

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/960225

**Comment by aelcenganda** [comment]
因為要把 select a card 跟 multi-select cards 分開
multi select 在：https://github.com/SenseTW/sensetw/issues/6
