### ISSUE TITLE
Read a Card on Map （tag 爆掉）

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#48]
# Job Story
- When: 我在 Map 上看很多張卡片的時候
- I want to: 我會想要知道卡片的重點資訊是什麼
- So that 我可以不用看細節就可以開始將卡片分類，拉架構

# UI 
https://app.zeplin.io/project/5ae1980f28546a5bbf985063/screen/5ae69708704f1b180b6c5f34

# Fields
+ summary:   (string, required) - the summary of a card. Max 39 中文字，超過截斷
       重點：AI 技術跟不上
+ tags: 產業, 人才 (string) - tags separated by comma. Max 32 中文字，超過截斷。
+ source_title:  (string) - the title of the source. 資料來源 。Max 50 characters.
      【AI全面啟動Ⅱ：台灣企業行不行？關鍵在老闆｜天下雜誌】

# Success Criteria
1. 使用者自己做的卡片應該不需要打開詳細資料即可開始做分類
2. 要顯示 summary, tags（有 tag 的設計樣字）
3. source title 和 link 只需要顯示 domain name，要不顯眼，要看得出來是 Source title

# Out Of Scope
1. 過多不必要的顏色和 icon
2. 卡片可以超連結回原始資料
3. 展開塞不下的 tag

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/960230

**Comment by pm5** [comment]
落差：顯示 tag

**Comment by Kanailly** [comment]
今天測試，超過兩個字以上的tag無法完整顯示（只會顯示前兩個字）

**Comment by pm5** [comment]
是像這裡的「公托家園」這樣嗎？

<img width="733" alt="screen shot 2018-05-22 at 07 54 45" src="https://user-images.githubusercontent.com/119645/40335283-7046067a-5d95-11e8-94b6-f395acc98e00.png">

**Comment by pm5** [comment]
試了一下好像沒什麼問題？

<img width="1253" alt="screen shot 2018-05-22 at 07 57 48" src="https://user-images.githubusercontent.com/119645/40335377-d8382538-5d95-11e8-9d01-7b642d8b8867.png">

**Comment by Kanailly** [comment]
對欸，剛剛去看，發現顯示都正常了啊～

2018-05-22 7:58 GMT+08:00 Pomin Wu <notifications@github.com>:

**Comment by aelcenganda** [comment]
![2018-05-21 21 14 57](https://user-images.githubusercontent.com/9480974/40341083-1567cd86-5d51-11e8-8436-728885cb8e71.png)
tag 太多的時候會爆出來，看下個 sprint 要不要修

**Comment by caasi** [comment]
先處理單行 tag list ，等有換行需求再改做法：

![2018-07-11 11 34 45](https://user-images.githubusercontent.com/1164470/42550055-f322cb76-8501-11e8-8eb0-a2cd6fd1c274.png)
