### ISSUE TITLE
Map Toolbar v.1

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#49]
# Job Story
- When: 我在 Map 上要作圖的時候
- I want to: 我會想要有個工具列的按鈕可以執行所有動作
- So that 我可以把分析架構做出來

# UI 
# UI:
https://app.zeplin.io/project/5ae1980f28546a5bbf985063/screen/5b02718513965b310fc1ba3f

# Fields
- Create: open inspector to create
  - a new card
  - a new box
- Edit: open inspector to edit
- Add cards into a box: select cards and on box to add
- Move cards out of a box: select cards in a box
- Unbox a box

# Success Criteria
- 工具列不擋到右邊的編輯側邊欄
- 工具列不擋到左上的 map, box 狀態切換顯示的 bar
- 工具列在 box 中仍然存在
- 選取在切換 map 和 box 後自動 unselect
- 工具列會直列黏著 Map Inbox

**Comment by aelcenganda** [comment]
Spec 與實作落差：

1. 工具列位置要移到左邊
2. 選單名稱：加入 Box、退出 Box

**Comment by caasi** [comment]
> 工具列位置要移到左邊

![2018-05-17 11 41 26](https://user-images.githubusercontent.com/1164470/40197285-dd0e52ca-59c7-11e8-9862-45fda3c69779.png)

**Comment by aelcenganda** [comment]
工具列在同時同時打開 inbox 和 inspector 時會被吃掉
![2018-05-21 21 51 16](https://user-images.githubusercontent.com/9480974/40338045-0102840e-5d41-11e8-99be-2895d58c49a2.png)

**Comment by aelcenganda** [comment]
要改成圖形化 toolbar，close the issue
