### ISSUE TITLE
Read a Box on Map (tag 爆掉)

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#50]
# Job Story
- When: 我在 Map 上看很多張卡片和 Box 的時候
- I want to: 我會想要知道 Box 聚集了什麼概念或是是什麼 argument
- So that 我可以不用看細節就可以開始將卡片分類，拉架構

# UI 
https://app.zeplin.io/project/5ae1980f28546a5bbf985063/screen/5ae69708704f1b180b6c5f34

# Fields
+ title (string, required) - the summary of a card. Max 18 中文字，超過截斷（20 characters in English?）
+ tags: 產業, 人才 (string) - tags separated by comma. Max 32 中文字，超過截斷。
+ ~~card_count (number): 有幾張卡在 box 裡~~

# Success Criteria
1. 使用者自己做的 Box 應該不需要打開詳細資料即可開始做分類
2. 要顯示 title, tags（有 tag 的設計樣字）

# Out Of Scope
1. 過多不必要的顏色和 icon
2. 卡片可以超連結回原始資料
3. 展開塞不下的 tag

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/960228

**Comment by pm5** [comment]
落差：顯示 tag

**Comment by caasi** [comment]
現況：

![2018-05-17 09 12 32](https://user-images.githubusercontent.com/1164470/40189953-7a43ff06-59b2-11e8-9547-0b912b144ee8.png)

**Comment by aelcenganda** [comment]
![2018-05-21 21 43 08](https://user-images.githubusercontent.com/9480974/40341065-f24814c8-5d50-11e8-9095-4a456898fbd8.png)

tag 太多的時候會爆出來，看下個 sprint 要不要修

**Comment by caasi** [comment]
同 #48 ：

![2018-07-12 08 54 19](https://user-images.githubusercontent.com/1164470/42606637-57bb13b8-85b1-11e8-91ba-f5258a8b0b78.png)
