### ISSUE TITLE
Read a Box in Inspector

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#51]
# Job Story
- When: 我在 map 上看到一個 box 
- I want to: 我會想要知道 Box 多一點的 info
- So that :可以決定要不要打開來看整個 Box

# Fields
## Box Base
使用者可以編輯的，按順序：
+ title: 缺乏跨界人才 (string, required)  - the title of a box. Max 20 characters.
+ summary: (string) - Summary of a Box. Max 150 characters.
+ tags: tag1, tag2, tag3 (string) - Tags on a Box, separated by comma.

## Box
+ Attributes (Box Base)
    + box_id: 780FF (string, required) - the id of a box.
    + created: 1415203908 (number) - time stamp.
    + last_updated: 7815203908 (number) - time stamp.
    + ~~owner (User) - who own this box.~~
    + map_id (string, required) - the id of the map it belongs to.
    + cards (array[Card]) - the cards in this box.

## 預填欄位
使用者可以編輯的，按順序：
+ Box Title: one concept or one argument
+ summary: 文化部提供的議題分析表
+ tags: tag1, tag2, tag3 

# UI 
zpl.io/2y7WrXG
https://zpl.io/VK0yenP

# Success Criteria
1.  用跟卡片一樣的 Inspector 側邊欄
2. 使用者按下更新後感覺有更新

# Out Of Scope
1. 選取多張卡片直接新增一個 box，然後卡片消失

# 待討論
1. Box title, summary, tag 的字數限制
2. 要不要顯示 Box 裡面有哪些卡的 summary 或是 tag

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/960243

**Comment by aelcenganda** [comment]
實作與 spec 落差：

欄位順序

**Comment by caasi** [comment]
現況：

![2018-05-17 09 13 38](https://user-images.githubusercontent.com/1164470/40190010-a10cf57a-59b2-11e8-8b17-2f336da6ae8f.png)
