### ISSUE TITLE
Close Map Inbox

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#53]
# Job Story
- When: 我想要拉 Map 架構時
- I want to: 關掉 Map Inbox
- So that 我有更大的畫布 Map

# UI 

# Fields

# Success Criteria
- 成功關閉
- 關閉後有按鈕可點選打開 Map Inbox

# Out of Scope
1.

# 待討論

**Comment by pm5** [comment]
Closed by 1ece5c2a61c1e8ef5dedf4b3d3a131179729d894

**Comment by aelcenganda** [comment]
![2018-05-21 21 39 08](https://user-images.githubusercontent.com/9480974/40337748-521b571e-5d3f-11e8-8084-a2199f34aede.png)
現在往下捲動，會找不到地方關 inbox，先打開這個 issue，但是下個 sprint 應該是要看要不要改捲動

**Comment by aelcenganda** [comment]
這個 sprint 主要是完成 close map inbox 改成按鈕在 inbox 右側。resize 另外討論。
