### ISSUE TITLE
Add Tags on a Box on Inspector

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#55]
# Job Story
- When: 我整理完一個 Box 時
- I want to: 我會想要對 Box 利用 tag 做分類
- So that: 在 Map 那一層知道這個 Box 裡面有什麼東西

# UI 
TBD

# Out Of Scope
1. 巢狀 Tag。
2. different type of tags

# Success Criteria
1. 每個卡片的側邊欄有一個字串輸入欄可以讓使用者輸入多個 tag ，plain text 即可。 範例： "tag1, tag2, tag3"
2. tag 之間用 " , " 分割。
3. 預填欄位示範範例： tag1, tag2, tag3

# 待討論
就是 tag 輸入後在 inspector 上的樣子： UI & RD

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/962232

**Comment by caasi** [comment]
Check https://github.com/SenseTW/sensetw/commit/1406951ee5ed99f274e155406360df95535ec314

**Comment by aelcenganda** [comment]
![2018-05-21 21 43 08](https://user-images.githubusercontent.com/9480974/40337948-84de32ce-5d40-11e8-9476-214a2e18df1d.png)

tag 太多的時候會爆出來，看下個 sprint 要不要修

**Comment by aelcenganda** [comment]
抱歉，這個 bug 應該開在 read a box on map
