### ISSUE TITLE
Edit Tags on a Box on Inspector

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#56]
# Job Story
- When: 我在整理 box 的資訊時
- I want to: 我會想要修改 Box 上的 tag
- So that: 在 Map 那一層知道這個 Box 裡面有什麼東西

# UI 
TBD

# Out Of Scope
1. 巢狀 Tag。
2. different type of tags

# Success Criteria
1. 每個卡片的側邊欄有一個字串輸入欄可以讓使用者輸入多個 tag ，plain text 即可。 範例： "tag1, tag2, tag3"
2. tag 之間用 " , " 分割。

# 待討論
就是 tag 輸入後在 inspector 上的樣子： UI & RD

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/962234

**Comment by caasi** [comment]
Check https://github.com/SenseTW/sensetw/commit/1406951ee5ed99f274e155406360df95535ec314
