### ISSUE TITLE
Remove Tags on a Box on Inspector

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#57]
# User Story
身為一個使用者，會想要刪除 Box 上的一個 Tag。

# UI 

TBD

# Out Of Scope

# Success Criteria
1. 每個 Box 的側邊欄，在輸入區的 plain text 去刪除 tag 字串。

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/962235

**Comment by caasi** [comment]
Check https://github.com/SenseTW/sensetw/commit/1406951ee5ed99f274e155406360df95535ec314
