### ISSUE TITLE
幾個 refactoring

### ISSUE THREAD

**Issue by pm5** [SenseTW/sensetw#58]
- [x] 刪除 `sampleStateObjects`, `sampleStateBoxes`, `sampleStateCards`, `sampleCardMap`, `sampleCardList`、`types/sense-article`。這些測試資料在 code 裡已經不再使用了，以後可能會在修改 object model 的時候造成阻礙。
- [x] 對 `Object` 的操作用 reducer 封裝起來。
- [ ] 把 `object-editor` 合併進 `selection`，讓 selection 在剛好只選到一個 object 的時候自動處理 state copy。這樣以後可以順便處理選擇多個 object 的時候出現 bulk edit UI。
- [ ] 把 `ObjectContent` component 的 local state 改成 global app state。側欄的編輯器 state 可能需要讓整個 app 都能存取，例如在編輯器修改卡片的時候要能立即（還沒按更新）就能在 map 裡看到改變，這是圖形編輯器常有的 UI 設計。

**Comment by caasi** [comment]
目前把基礎類型放在 `/src/types/sense/` 下， application state 放在 `/src/types/` 下。

非必要 application 應該大部分都 import `/src/types` 下的東西，而不是去摸 `/src/types/sense/` 下的東西。

如果要好好封裝，大概得討論一下要把哪些 `/src/types/sense/` 裡的 data constructors re-export 出來。

**Comment by caasi** [comment]
這兩項：

- [ ] 把 `object-editor` 合併進 `selection`，讓 selection 在剛好只選到一個 object 的時候自動處理 state copy。這樣以後可以順便處理選擇多個 object 的時候出現 bulk edit UI。
- [ ] 把 `ObjectContent` component 的 local state 改成 global app state。側欄的編輯器 state 可能需要讓整個 app 都能存取，例如在編輯器修改卡片的時候要能立即（還沒按更新）就能在 map 裡看到改變，這是圖形編輯器常有的 UI 設計。

另開 #73 處理。
