### ISSUE TITLE
規劃 staging infrastructure

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#60]

**Comment by pm5** [comment]
之前討論過 domain names：

- sense.tw - sensemap。
- h.sense.tw - hypothesis 。
- via.sense.tw - 維持 via 。
- o.sense.tw - 維持 bouncer。

目前佈署 sensemap 只要放 build 好的靜態檔案就可以了。我的想法是這樣：

- sense.tw - `YYYYMMDD` tag
- staging.sense.tw - `master` branch
- <branch_name>.sense.tw - `branch_name` branch

**Comment by pm5** [comment]
目前佈署 sensemap 只要放 build 好的靜態檔案就可以了。我的想法是這樣：

- sense.tw - `v<x.y.z>` tag
- staging.sense.tw - `master` branch
- <branch_name>.staging.sense.tw - `branch_name` branch

幾個考量是想減少 ad-hoc branch name 和 domain name 的數量，跟我們用 GitHub flow 的道理一樣。所以只有 master branch 是 ad-hoc，它總是佈署到 staging。所有其它 branch 都要 staging 底下的 <branch_name>.staging。

sense.tw 用 tag 管理是為了方便比較不同版本之間改了哪些東西，還有將來有必要開發全新 branch 的時候，用 tag 觸發不會卡在只能佈署 master branch。

版號打算下一版從 `v0.1.0` 開始，再下一個 sprint `v0.2.0`，一直下去。理論上 MVP 就是 `v1.0.0`？這樣未來可以配合 roadmap 去規劃版號。

**Comment by pm5** [comment]
討論完畢。Backend 的事情移到 #59
