### ISSUE TITLE
Hypothesis Annotations in one group as a card in map inbox

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#62]
# Job Story
when: 當我利用 via.sense.tw 閱讀一份線上的PDF或是網頁，下完 annotation
want: 我會希望這個 annotation 會出現在我的 Map Inbox。
so that: 我可以在之後去做分類、拉議題脈絡。

# Prerequisites

* https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1049039/detail
* https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1049093/detail
* https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1012075/detail

# Success criteria
1. Sync new Hypothesis Annotations to a map inbox.
2. Cards in map inbox can only archived and not deleted.
3. Annotation as summary of a Card, if there is no annotations, use first 20 character in highlights from Hypothesis as summary
4. Annotations from one hypothesis group to a Map Inbox
5. Changes on Card can be synced to  annotations in hypothesis group

# UI:
sync btn 放在 inbox 左上角
https://app.zeplin.io/project/5ae1980f28546a5bbf985063/screen/5b215df14daaca5228e44b77

# Out of Scope
- Realtime sync. It can be refreshed or an sync button
- Personal Inbox
- Multi-groups import
- Import comments

# Fields
Card- Hypothesis annotation 的對應

|Card|Hypothesis Annotation| page note|
|---|---|---|
|summary|annotation|page note|
|quote|quote|NA|
|source title | source title|Source title|
|tag|tag|tag|
|Source link| annotation_url | source link in via.sense.tw|
|said_by who|||
|stakeholders|||
|card type |||
|card_url | annotation_url | |
|card_id| annotation_id|annotation id|
|created time|created time|created time|
|owner|annotator|annotator|
|last_updated|last_updated|last_updated|
|~~in_map~~ |||
|~~in_boxe~~ |||
|~~comment~~|~~comment~~|~~comment~~|

// 如果沒有註解，做成卡的時候，直接複製 quote 前 20 字做 summary
//先不處理 annotation 上的 comment

現在能做到雙邊連動嗎？

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/983674

**Comment by caasi** [comment]
> Cards in map inbox can only archived and not deleted.

必須要紀錄哪些 card 來自 annotation 才能完成這點。

**Comment by aelcenganda** [comment]
已更新 annotation 與 card 對應欄位。想問有辦法做到雙邊連動嗎？就是在 map 改了 summary ，可以同步改到 hypothesis annotation 上的字？

我現在寫 push 是不是意思是單向的？
（如果不行雙向就單向從 hypothesis push 過來）

**Comment by pm5** [comment]
"Push" means (single) directional.  We could do bi-directional linkage between SenseMap and WebClipper data in our current way of implementation.

**Comment by aelcenganda** [comment]
Can we do bi-directional linkage in this sprint?

**Comment by pm5** [comment]
Yes, I think so.

**Comment by pm5** [comment]
Closed by 1476a688eff07d70109d4d4d0c6b1f7dba7b370a

**Comment by aelcenganda** [comment]
我之前 spec 沒有寫清楚 

```
Success Criteria 
3. Annotation as summary of a Card, if there is no annotations, use first 20 character in highlights from Hypothesis as summary
```
原本的 highlight 可以同時放在 description 嗎？意思是從 highlight -> description，再從 description 複製一段到 summary。這樣之後在 inbox 改 summary 還是可以同時看到 description。

But this is minor, so it depends on your time.

**Comment by pm5** [comment]
再問清楚一下：沒有 annotation 的話，是 highlight -> description & summary，所以 description 和 summary 的內容會一樣，是這樣嗎？有 annotation 的話，也是 annotation -> description & summary 嗎？

**Comment by aelcenganda** [comment]
@pm5 
沒有 annotation：
highlight -> description & summary

有 annotation：
annotation -> summary
highlight -> description

**Comment by aelcenganda** [comment]
現在 highlight 只進到 summary，沒有進到 description

**Comment by pm5** [comment]
修好了。
