### ISSUE TITLE
Box List (read on Map)

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#65]
# Job Story
- When: 我看到多張卡片似乎有某種關係時 (E.x. 同一天的文章片段, 同一個人說的話)
- I want to: 我會想要選取多張卡片放在一個 Box 堆疊起來，在 Map 上可以看到不同 Box 裡面有什麼東西。
- So that 可以在建立 Box, Card 過程中漸漸找出更適合的分類。

# Key Concept
1. like Trello list。

# UI
TBD
https://app.zeplin.io/project/5ae1980f28546a5bbf985063/screen/5b0af751033442b5224e3a24

# Success Criteria

1. ** 使用者可以在 Map 上看到每個 Box 裡面有幾張卡，在 box list 裡 Card 只顯示 Summary  ，如果沒有 Summary 則顯示 Quote 。 (undone)
2. 如果 Box 裡面沒有卡片，則只顯示 Box Name 跟 Box Tag。
4. 使用者可以對 Box 滑鼠左鍵雙擊，打開 Inspector。
10. Box List 可以收折。

# Out of Scope
1. 換頁。
2. 使用者仍然可以切換到 Box 裡面，並且拉線去做對應關係。
3. 巢狀 Box。
4. double click box 打開 Box。 (先拿掉，對 user 的好處還不清楚)
5. 5. 放在 Box 裡面的卡片能加上 Edge。

# Reference Design
1.  Milanote 的 Column。
2. 參考 https://etblue.blogspot.tw/2018/04/storyliner-interactive-gossip-viewer.html 裡面一個 Box 裡面可能會多個 Quote 讓讀者看了可以更了解這個 Box。

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/972965

**Comment by pm5** [comment]
詢問 spec 中。

**Comment by pm5** [comment]
For milestone M4 we would only have time to finish: show a box list, drag cards from map into a box list, and drag cards out of a box list.  Edges and card orders are out of scope.

**Comment by aelcenganda** [comment]
Box List 顯示要放 summary instead of source title
