### ISSUE TITLE
Open source link on a new browser tab

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#66]
# Job Story
When: 我看卡片 Summary 仍然不清楚是什麼意思時
Want: 回去查看原文的 highlight
So: 可以了解這張卡片是什麼意思。

# UI

# Success Criteria
1. 使用者可以 double click 一張卡片開啟 inspector， 並且在 nspector 的 source link 欄位旁邊找到一個按鈕，該按鈕可以讓 user 點擊，點擊後會開啟該網頁在 browser 的新分頁。

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/983619

**Comment by caasi** [comment]
現況：

![2018-06-04 19 54 29](https://user-images.githubusercontent.com/1164470/40916124-2641d170-6831-11e8-9db4-ee1238e42987.png)

若要修改就 reopen 吧。
