### ISSUE TITLE
Scroll the canvas

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#68]
# Job Story
- When: 我覺得 Map 上的卡超過 300 張時
- I want to: 我會想要移動 Canvas
- So that 可以在 map 上看到超過畫面的 Card, Box。

# Success Criteria
1. user could 壓住 Space + 點擊背景拖拉移動畫布。

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/889991

**Comment by pm5** [comment]
WIP: https://github.com/SenseTW/sensetw/tree/viewport

**Comment by hychen** [comment]
修改一下 spec:  操作改成壓住 Space + 點擊背景拖拉移動畫布。 

否則會拖拉行為會打架

**Comment by pm5** [comment]
Realtimeboard 好像沒有打架的問題。你說的打架是什麼意思？

**Comment by pm5** [comment]
Okay，不過這個目前只是測一下效能，我會先弄別的 issue。

**Comment by pm5** [comment]
Closed by 155bbf7

**Comment by pm5** [comment]
加了 76e7683d5272ffe7117c2c088239d3f927679b1b 讓壓住 space 的時候才能拖拉畫布。
