### ISSUE TITLE
Edit a card on Map on Inspector

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#8]
# Job Story
- When: 
1.  當我在 map 上發現卡片資訊錯誤
2. 想加入補充資訊，
- I want to: 我會想要在 Map 上點選卡片編輯修改，
- So that 卡片的資訊更正確、有更多資訊，幫助我在 map 上分類跟其他人看懂卡片要傳達的資訊

# UI 
https://zpl.io/V189PMX

# Fields
## Card Base (object)
使用者可以編輯的：
+ summary:   (string, required) - the summary of a card. Max 150 characters.
       重點：AI 技術跟不上
+ tags: 產業, 人才 (string) - tags separated by comma.
+ source_title:  (string) - the title of the source. 資料來源 Max 50 characters.
      【AI全面啟動Ⅱ：台灣企業行不行？關鍵在老闆｜天下雜誌】
+ source_link: https://o.sense.tw/abcd (string) - the source url of the key information. 
+ description (string) - the description of a card. Max 1000 characters.
        真正的問題是，很多想做AI的人，不知道自己沒跟上最新進展。
        常常與科技大老開會，這位學者發現，台灣科技界研發產品，習慣先把產品規格開好，然後大家才去做。但AI研發必須一步步改善其精準度，有點像是做實驗，一步步排除問題，被市場接受了，就可以成為規格制定者。
        「很多基礎技術在網路上都是開源資訊，關鍵在要有真實的數據去玩，非常動態地從頭到尾調整，來找到AI產品的被使用者喜愛的關鍵點，」他直言，台灣也缺少有經驗的AI專案經理。
+ type (string) - Card type: Q, A, Note, Normal.
+ said_by (string) - said by who. 
+ stakeholders: 大學, 半導體, IT company (string) - involving stakeholders, separated by comma. 

## Card [/cards/{card_id}]
A card represents a key information extracted from a source. Sources are anything on internet, such as PDF, webpages, blog post, 
video or audio.

+ Attributes (Card Base)
    + id: 250FF (string, required) - the id of a card. Max 50 characters
    + created: 1415203908 (number) - time stamp.
    + last_updated: 7815203908 (number) - time stamp.
    + ~~owner (User) - who owns this card.~~

## 預填欄位顯示（引導使用者使用）
- summary: 說重點
- tags: tag1, tag2, tag3
- source_title: 資料來源，e.g. 【AI全面啟動Ⅱ：台灣企業行不行？關鍵在老闆｜天下雜誌】
- source_link: https://o.sense.tw/abcd
- description: 資料原文摘錄與補充資訊
- type (string) - Card type: Q, A, Note, Normal.
- said_by: 誰提出的意見？ e.g. XX 大學校長 XXX
- stakeholders: 誰會被影響？（用逗號隔開）e.g. 經濟部, 半導體廠商, 大學

# Success Criteria
1. 有互動區可以輸入資訊在 Card 上
2. ~~Required 欄位空白不允許更改，跳警告~~
3. 超過字數限制不允許更改，跳警告
3. Card 的大小不因為字數改變
4. 編輯完按更新之後，側邊欄的 UI 設計要讓使用者覺得有變，不然一時之間找不到卡片的改變會覺得很奇怪。
5. Card type 用選的，不是用輸入的，改完 type 會變顏色

# Out Of Scope
1.

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/902187

**Comment by aelcenganda** [comment]
更改欄位以及需要編輯完之後給 user feedback 之後有成功更新。
UI 要先給互動。

**Comment by aelcenganda** [comment]
1. 欄位順序
2. 需加上 Required 欄位
3. 更新完後讓使用者有回饋知道有更新 => 凱蘭會出四態的 save button

**Comment by aelcenganda** [comment]
剩下的調整去 required 欄位訊息
https://github.com/SenseTW/sensetw/issues/110
