### ISSUE TITLE
redux-thunk相容性問題

### ISSUE THREAD

**Issue by wenchen** [SenseTW/sensetw#84]
**Describe the bug**
redux-thunk與v2.3.0不相容, 在編譯的時候會出現
(14,84): Type 'Middleware' is not generic.
在redux-thunk的release note有詳述這件事情 https://github.com/reduxjs/redux-thunk/releases
他們提供的建議是，要不是停在 v2.2.0 不然就是 升級到redux 4.0

**To Reproduce**
1.	git clone
2.	改tsconfig.js 加入baseUrl到compilerOptions, 先設定為”/“
3.	npm install yarn -g
4.	npm install
5.	yarn run build
6.     See error

**Expected behavior**
可以正常編譯

**Screenshots**
wenchenx@ggv:~/ggvworkdir/sensetw/sensemap/src$ NODE_ENV=development yarn run build
yarn run v1.7.0
$ react-scripts-ts build
Creating an optimized production build...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
ts-loader: Using typescript@2.9.1 and /home/wenchenx/ggvworkdir/sensetw/sensemap/tsconfig.json
No valid rules have been specified for JavaScript files
Failed to compile.

/home/wenchenx/ggvworkdir/sensetw/sensemap/node_modules/redux-thunk/index.d.ts
(14,84): Type 'Middleware' is not generic.

error Command failed with exit code 1.
{
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Desktop (please complete the following information):**
 - OS: ubuntu 16.04.4

**Additional context**

**Comment by caasi** [comment]
see also: https://github.com/SenseTW/sensetw/issues/80#issuecomment-394352837

**Comment by wenchen** [comment]
這邊大概哪時候會merge回master呀

**Comment by pm5** [comment]
So this is solved?
