### ISSUE TITLE
Hypothesis Client 客製後的 UI

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#85]
要導回 map，關掉除了註記跟回應以外 hypothesis 的功能:

1. 隱藏 Page Note
3. 隱藏分享按鈕
4. 隱藏 annotation  的權限設定選單。 (預設 in that group, 非 only me)
5. default 不打開 sidebar。
6. 隱藏 reply to comment
7. 隱藏 account setting，只能 log out
8. logo 連回 dashboard

# UI 隱藏功能示意圖
https://www.figma.com/file/CblZ9n4CV1gVnLs4ZIgNljwL/Hypothesis-client-%E9%A0%81%E4%BF%AE%E6%94%B9

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1012085

**Comment by aelcenganda** [comment]
KL: 請 @ael 截圖說哪些要隱藏，哪些要加。
ael: 需要再跟 hychen 確認 spec。

**Comment by aelcenganda** [comment]
先更新了要隱藏的功能標注在 figma 上。
要怎麼連回 map editor 週一再跟凱蘭討論

**Comment by aelcenganda** [comment]
不順 UI，直接隱藏
