### ISSUE TITLE
Sign up  & Login page, log out UI

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#86]
# 目標：
- 新註冊
- log in

# Success Criteria
1. uniques user name: 限英數，不能改，要檢查
2. Sign up page:可以 switch to log in
3. Log in page: 可以 switch to sign up
4. log in 後在 navigator bar 可以 log-out
4. 包含 忘記密碼、reset password 等下個 sprint 需要實作的功能

# Access Criteria
1. username must be between 3 and 30 characters, containing only letters, numbers, periods, and underscores.
2. email is case insensitive.
3. password must be between 8 and 16 characters.

# Out of scope
1. 從 landing page 登入（下個 sprint）

# UI

Figma File:
https://www.figma.com/file/eCh4hpIkRzk3TVXQbcY580zv/sense_login

Zeplin Frames:
Sign-in_1
https://zpl.io/be4XZeN

Sign-in_2
error message
https://zpl.io/aXzQ0WM

Sign-up_1
https://zpl.io/bPdlZdm

Sign-up_2
Textfield hints/tooltips
https://zpl.io/anmGwmY

Sign-up_3
error message
https://zpl.io/am6gQ69

Reset Password
https://zpl.io/2pdD5Jr

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1015050

**Comment by Kanailly** [comment]
我需要PM確認欄位噴出的錯誤提示內容
https://zpl.io/aXzQ0WM
https://zpl.io/am6gQ69
https://zpl.io/anmGwmY

**Comment by Kanailly** [comment]
## Sign-in_1 
https://zpl.io/be4XZeN

## Sign-in_2
error message
https://zpl.io/aXzQ0WM

## Sign-up_1
https://zpl.io/bPdlZdm

## Sign-up_2
Textfield hints/tooltips
https://zpl.io/anmGwmY

## Sign-up_3
error message
https://zpl.io/am6gQ69

## Reset Password
https://zpl.io/2pdD5Jr

**Comment by pm5** [comment]
Are these finalized?  Can we close the issue (and start RD work on this)?

**Comment by Kanailly** [comment]
hmmmmm 我這邊沒有要再改這裡的設計了，除了錯誤提示的內容不確定會不會修正，但應該可以關閉這個issue吧

**Comment by Kanailly** [comment]
呃 @aelcenganda 你是不是還沒看畫面。目前每個畫面至少有兩個入口可以讓sign-in連到sign-up（反之亦然)
工程師先等PM確認再開吧

**Comment by aelcenganda** [comment]
@Kanailly 抱歉我早上沒寫清楚，那時候有看圖，指的是你很貼心在 sign up 下面有放 already have an account 讓他去 log in。希望 sign in page 下面也有那行小字。

我在 Figma 上加註了：

1. sign in 統稱 log in
2. 麻煩幫忙在 log in page 加小字附註
3. user name 不想讓他用逗號

（看到顏色之後覺得我們之後 UI 會往一個活潑簡單的風格走 XD）

**Comment by aelcenganda** [comment]
@Kanailly 我忘了

1.  password 是不是需要 double confirmation。
2. 還差 log out 的圖喔，你也可以加在 Navigator 那邊。這邊做好先 close

**Comment by Kanailly** [comment]
所以 password 的 double confirmation是要在圖面上出現什麼資訊嗎？
log out 的圖不會出現在這串，要先登入了之後才會有 log out的選項跟畫面r。

**Comment by aelcenganda** [comment]
@Kanailly 輸入 password 兩次
好，log out 不在這串。

**Comment by Kanailly** [comment]
確定真的要讓人在註冊的時候打兩次密碼嗎～？
這麼做的需求是什麼？對我們的好處是什麼呢？
我自己是覺得越來越少看到這樣的形式，google了一下看到這個討論串。
https://ux.stackexchange.com/questions/484/is-a-repeat-password-field-necessary-in-a-signup-page

**Comment by aelcenganda** [comment]
@Kanailly 對不起，我剛剛 further search ，同意你，覺得不需要 double confirmation。

**Comment by Kanailly** [comment]
OK 的，有圖面邊看資料邊討論比較容易想。 我把figma那裡提到要改的地方改完，更新到zeplin上，這串就可以close囉？

**Comment by Kanailly** [comment]
更新完畢

**Comment by aelcenganda** [comment]
Verified
