### ISSUE TITLE
Sign up by email

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#87]
# Prerequisites

* https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1049039/detail
* https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1049093/detail
* https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/951393/detail (log in after sign up)

# Success Criteria
1. username must be between 3 and 30 characters, containing only letters, numbers, periods, and underscores.
2. email is case insensitive.
3. password must be between 8 and 16 characters.

# UI
https://sensetw.productboard.com/feature-board/152244-feature-organization/features/1015050/detail

https://zpl.io/bzMJO0A

https://zpl.io/bAvzw8B

https://zpl.io/agnZ5LZ

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/951412

**Comment by aelcenganda** [comment]
有規定一個 email 只能註冊一個 username 嗎？

**Comment by pm5** [comment]
> 有規定一個 email 只能註冊一個 username 嗎?

Yes.  Is that okay?

**Comment by pm5** [comment]
@Kanailly the background color is different from that of #88 ?

**Comment by Kanailly** [comment]
The are different!  Sign-in bg color: #B3FCFB

**Comment by pm5** [comment]
Closed by ad1e8ee
