### ISSUE TITLE
Log in by email

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#88]
OAuth 2.0 login API.

# Prerequisites

* https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1049039/detail
* https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1049093/detail

# UI
https://sensetw.productboard.com/feature-board/152244-feature-organization/features/1015050/detail

https://zpl.io/25qeMQ0

https://zpl.io/2ymJxoJ

Forget password linked to hello@sense.tw

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/951393

**Comment by Kanailly** [comment]
log in bg color: #B3E5FC

**Comment by pm5** [comment]
Closed by ad1e8ee
