### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#89]
Logout sense.tw and also logout hypothesis account.

# Prerequisites

* https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1049039/detail
* https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1049093/detail

# UI
https://sensetw.productboard.com/feature-board/152244-feature-organization/features/1015050/detail

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/960341

**Comment by pm5** [comment]
Closed by ad1e8ee
