### ISSUE TITLE
Create a new card on Map

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#9]
# Job Story
- When: 我想要新增分析議題所需的重要資訊時，
- I want to: 我會想要在 Map 上新增 Card，
- So that 我和其他人可以收錄這個重要資訊，成為議題分析的基石。

# UI 
https://zpl.io/V189PMX
https://zpl.io/2y7WrXG

# Fields
## Card Base (object)
使用者可以編輯的：
+ summary:   (string, required) - the summary of a card. Max 150 characters.
       重點：AI 技術跟不上
+ tags: 產業, 人才 (string) - tags separated by comma.
+ source_title:  (string) - the title of the source. 資料來源 Max 50 characters.
      【AI全面啟動Ⅱ：台灣企業行不行？關鍵在老闆｜天下雜誌】
+ source_link: https://o.sense.tw/abcd (string) - the source url of the key information. 
+ description (string) - the description of a card. Max 1000 characters. Quote from Hypothesis
        真正的問題是，很多想做AI的人，不知道自己沒跟上最新進展。
        常常與科技大老開會，這位學者發現，台灣科技界研發產品，習慣先把產品規格開好，然後大家才去做。但AI研發必須一步步改善其精準度，有點像是做實驗，一步步排除問題，被市場接受了，就可以成為規格制定者。
        「很多基礎技術在網路上都是開源資訊，關鍵在要有真實的數據去玩，非常動態地從頭到尾調整，來找到AI產品的被使用者喜愛的關鍵點，」他直言，台灣也缺少有經驗的AI專案經理。
+ type (string) - Card type: Q, A, Note, Normal.
+ said_by (string) - said by who. 「發言人」
+ stakeholders: 大學, 半導體, IT company (string) - involving stakeholders, separated by comma. 目的：意見多元性與可信度，目前為單純欄位，未來再決定要不要做成 tag 或是其他連結應用。「利害關係人」

## Card [/cards/{card_id}]
A card represents a key information extracted from a source. Sources are anything on internet, such as PDF, webpages, blog post, 
video or audio.

+ Attributes (Card Base)
    + id: 250FF (string, required) - the id of a card. Max 50 characters
    + created: 1415203908 (number) - time stamp.
    + last_updated: 7815203908 (number) - time stamp.
    + ~~owner (User) - who owns this card.~~
    + ~~maps (array[Map]) - the maps a card belongs to.~~
    + ~~boxes (array[Box]) - the boxes a card belongs to.~~

## 預填欄位顯示（引導使用者使用）
- Summary (summary): 說重點
- Tag (tags): tag1, tag2, tag3
- Source Title (source_title): 資料來源，e.g. 【AI全面啟動Ⅱ：台灣企業行不行？關鍵在老闆｜天下雜誌】
- Source Link (source_link): https://o.sense.tw/abcd
- Description (description): 資料原文摘錄與補充資訊
- Card type (string) - Card type: Q, A, Note, Normal.
- Said By (said_by): 誰提出的意見？ e.g. XX 大學校長 XXX
- Stakeholders (stakeholders): 誰會被影響？（用逗號隔開）e.g. 經濟部, 半導體廠商, 大學

# Success Criteria
1. 在側邊欄輸入資訊在 Card 上
2. ~~Required 欄位未填不允許創立新卡片~~
3. 點選新增卡片按鈕後，新增 Card 在 Map 上
2. 新增的 Card 出現在畫面正中央，不會被側邊欄擋到
3. Card 的大小不因為字數改變
3. 看得出來是在編輯卡片不是編輯 box
3. 新增到 Map Inbox

# Out Of Scope
1.

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/889920

**Comment by aelcenganda** [comment]
差距：預填欄位文字修正

**Comment by caasi** [comment]
> 新卡片要出現在 map 中央

![2018-05-17 11 46 39](https://user-images.githubusercontent.com/1164470/40197381-2706af6c-59c8-11e8-98df-5a05cd3f2774.png)

> 預填欄位文字修正

@aelcenganda 麻煩提供一下預填欄位文字～
