### ISSUE TITLE
Map owner

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#90]
Note: 先做 map owner，還不需要加入 group，加卡、拉線大家都可以做。

# Success Criteria
1. Map 屬於 Map owner
2. Dashboard 也要標注誰創建 map
3. 只要 log in 都使用 map editor 、inbox、annotation
4. 所有 map 只能選 public

# Out of Scope
權限控管，未來完整 Map member 權限
https://docs.google.com/document/d/1Tpebb1ZkfcC4iv1CCFe_5ENBImf2qijFyEZ2NWE3clg/edit
* 只有 map owner 可以 edit map details 跟 delete map

# Prerequisites

* https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1049039/detail
* https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1049093/detail

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1012087

**Comment by pm5** [comment]
This might need to be postponed until we have map members feature?

**Comment by aelcenganda** [comment]
But at least the map owner can create a group corresponding to the map on hypothesis and can use that group to annotate? 

If we are not going put members in a map right now, does that mean we need to disable the feature to add others into a group?

**Comment by Kanailly** [comment]
還是先引導(協調)使用者去hypothesis(sense.tw)那裡加好友到group？ 這樣map上的卡片仍然可以以group方式協作加卡片，對吧？？？

**Comment by pm5** [comment]
現在的 sense.tw 的 hypothesis 後端沒有做權限，所以任何人只要申請了帳號，都可以在任何 group/map 裡加 annotation。所以我上面的意思是說，是不是等我們做了權限，有鎖權限的功能之後，再來做兩邊的權限系統的整合，不然，沒有東西需要整合呀。

**Comment by hychen** [comment]
per discussion with @aelcenganda, 等權限功能規劃完在實作這個。

**Comment by hychen** [comment]
修正這個功能描述變成加上 Map Owner。

**Comment by pm5** [comment]
Closed by #183. 創建 map 時記錄 owner 這個流程，要等 #151 完成才看得到。

**Comment by pm5** [comment]
顯示 map owner 了（for example "First Map" on production）

顯示 last updated time 是不是等之後 history 再做？

**Comment by aelcenganda** [comment]
last updated time 先做會衝到嗎？使用者現在希望可以看到 map and card 最近什麼時候改過，跟 card owner 是誰。如果先做 map 的 last updated time，會需要額外時間規劃架構嗎？

**Comment by pm5** [comment]
last updated time 要再加一些東西。不過 last updated time #223 有了，這裡也沒有 spec，那就移到 #223 去好了。
