### ISSUE TITLE
Basic Dashboard UI

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#91]
# UI 

https://app.zeplin.io/project/5ae1980f28546a5bbf985063/screen/5b1116a526d51037706b7e90

# Success Criteria (first week)
1. add a map，去哪裡填資料，要選 private or public
https://sensetw.productboard.com/feature-board/152244-feature-organization/features/951494/detail
2. delete a map
3. 區分自己與別人的 map (by color or 分隔線）
4. Sorted by last updated

# Next sprint implement:
1. add a member （https://github.com/SenseTW/sensetw/issues/100）
2. edit details （會跳出跟 create 一樣的流程）

# UI links:

##### Dashboard
https://zpl.io/brN1eoW
##### Dashborad - dropdown(log-out)
https://zpl.io/bzWwje4
##### Add new map
https://zpl.io/VKqG1Nq
##### Add new map - required field
https://zpl.io/a74wnZW
##### [future] Add new map - step1
https://zpl.io/2j4pW8r
##### [future] Add new map - step2
https://zpl.io/bzWwLMz

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/975261

**Comment by aelcenganda** [comment]
UI 預計 6/8 updata

**Comment by aelcenganda** [comment]
@Kanailly create a map 的部分， map name 要標一下 required

**Comment by Kanailly** [comment]
畫面 link 補上

**Comment by aelcenganda** [comment]
@Kanailly log out 是也要畫在這裡嗎？

**Comment by Kanailly** [comment]
嗯，之前討論是

**Comment by Kanailly** [comment]
@aelcenganda  但是現在有很多產品log out之後就直接跳到 landing page或是跳回登入頁。
如果這邊沒有特別的指示或是想法的話，我會畫一張簡單的道別圖示跟說掰掰的文字這樣噢

**Comment by aelcenganda** [comment]
之後會直接跳回 landing page，現在跳回 log in page。不用額外出圖
KL <notifications@github.com>於 2018年6月13日 週三，下午2:45寫道：

**Comment by Kanailly** [comment]
好喔～ 不過我把按帳號（icon）dropdown 的選項補上去了，https://zpl.io/bzWwje4。把logout /setting塞進去了

**Comment by aelcenganda** [comment]
Verified. 關 issue
