### ISSUE TITLE
Open a Map from dashboard

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#92]
# Job Story
When 我想分析一個議題時
Want 我想在 https://sensetw.productboard.com/feature-board/152244-feature-organization/features/975261/detail 上點擊 1 個  Map
So that  我可以刪除一個 map。

# Success Criteria
1. 打開 map editor。

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/962327

**Comment by aelcenganda** [comment]
Verified

**Comment by aelcenganda** [comment]
最新的 map 要在最上面

**Comment by hychen** [comment]
fixed by 146a878f8dbe74df0e5f684cc8e743d83e14d38f, close this issue.

**Comment by caasi** [comment]
滑鼠移到 owner 或 map name 上可以看到時間。

**Comment by aelcenganda** [comment]
> 滑鼠移到 owner 或 map name 上可以看到時間
@caasi  我要去哪裡可以看到
