### ISSUE TITLE
Create a Map from dashboard

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#93]
# Job Story
When 我想分析一個議題時
Want 我想在 https://sensetw.productboard.com/feature-board/152244-feature-organization/features/975261/detail 上點擊 "新增 Map" 的按鈕
So that  我可以開始蒐集議題相關的資訊並且分析。

# Fields
使用者自填：
1. map name (string, 40 chars). 預填：Map name
2. map description (text, 250 chars). 預填：介紹這張 map 要整理什麼樣的議題資訊，需要什麼樣的幫忙（上限 250 字）。
3. tag
4. Type: Public or private
5. member (這個 sprint 不做)
6. photo upload （nice to have，這個 sprint 不一定要完成）

要記錄：
3. map owner
4. created time
5. map_url

# Success Criteria
1. 成功建立新的 map
2. 讓 map owner 解釋這張 map 在做什麼、需要什麼協作、map 的結論
2. Map 建立完後，打開 Map Editor。

# Out of Scope
- public/private 權限控管，只是先讓使用者選

# UI links:

##### Dashboard
https://zpl.io/brN1eoW
##### Dashborad - dropdown(log-out)
https://zpl.io/bzWwje4
##### Add new map
https://zpl.io/VKqG1Nq
##### Add new map - required field
https://zpl.io/a74wnZW
##### [future] Add new map - step1
https://zpl.io/2j4pW8r
##### [future] Add new map - step2
https://zpl.io/bzWwLMz

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/951494

**Comment by aelcenganda** [comment]
網址：http://dashboard.staging.sense.tw

![2018-06-26 1 15 09](https://user-images.githubusercontent.com/9480974/41890777-a2db3780-7943-11e8-9840-7eb0236c84c2.png)

@Kanailly 想跟你確認卡西現在的 dashboard
1. 要在 dashboard 右上角加 annotation 嗎？我的想法是要到 map 裡面加（在 map editor 或是在 dashboard 上選一個 map 的 annotation），不會在 dashboard 頁面右上角。
2. 左上角的加號，我用 13 吋螢幕，沒開全螢幕的話，很容易會選取到左上角已經開好的 map ，而不是新增 map。
3. 圖片比例 ratio 要給卡西。

**Comment by pm5** [comment]
I think that annotation button is a bug?

**Comment by Kanailly** [comment]
> I think that annotation button is a bug?
我想它是。 https://zpl.io/brN1eoW 圖上沒有

按不到那顆btn的問題是什麼？  顏色不清楚？ 按了會消失？  問題的點是在功能還沒做上去而導致的問題，還是設計上的哪一個點導致目前你無法進行這項操作？

那需要請卡西把圖片顯示範圍固定在9:5的比例上（原圖設定是320:200）

**Comment by caasi** [comment]
我以為 annotation button 一直都在（為了連到 via ），而 Map/Inbox/View_1 tab 則是在進入 map 後才出現的。

![2018-06-27 04 43 32](https://user-images.githubusercontent.com/1164470/41938160-dcef0600-79c4-11e8-9f6e-3838ecb40e50.png)

所以 annotation button 不該出現在 dashboard 頁囉？

---

下次方便的話，把圖片比例標出來或留在 comment 中吧。

**Comment by Kanailly** [comment]
## 記錄一下剛剛sync的討論：
dashboard上那顆黑色的annotation按鈕會保留。（在每個map卡片底下的annotate按鈕都是連去via的話，那不如就更動設計讓連去via的入口統一放在 second navigation bar上）（目前做不到從map連出去的via能預先判斷所處的group）

----------
好，我會記得要把解釋的事項標在zeplin上

**Comment by aelcenganda** [comment]
OK，那就在右上角放 button to annotation，要麻煩 @Kanailly update 到 UI 上。但是這樣 [ hypothesis Client](https://github.com/SenseTW/sensetw/issues/116) 那頁是不是就要把 group 的選擇中 public 的部分隱藏，因為希望每張卡還是要屬於一個 map。

@pm5 那現在 via.sense.tw 貼完連結，打開 client 之後，預設在的 group 會是什麼？是最近一次使用的 Map？

**Comment by Kanailly** [comment]
@aelcenganda 對，應該要把public的部分隱藏。 不過你在figma上放的截圖的group list選項剛好沒有public XD 
然後dashboard圖已更新

**Comment by caasi** [comment]
see: 0da8f10145980aa589b95263964350a1934ebf04 for map creation

**Comment by aelcenganda** [comment]
Verified
