### ISSUE TITLE
Delete a Map from dashboard

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#94]
# Job Story
When 我想分析一個議題時
Want 我想在 https://sensetw.productboard.com/feature-board/152244-feature-organization/features/975261/detail 上點擊 "刪除" 的按鈕
So that  我可以刪除一個 map。

# Success Criteria
1. owner 可以刪除一個 map

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/965695

**Comment by aelcenganda** [comment]
Verified
