### ISSUE TITLE
Basic Navigator Bar UI

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#95]
Navigator includes

- logo: /dashboard
- about: (open in new tab) https://beta.hackfoldr.org/sense-tw
- help icon: (open in new tab)
- user profile icon

# UI 
1. https://app.zeplin.io/project/5ae1980f28546a5bbf985063/screen/5b1116a526d51037706b7e90
2. https://app.zeplin.io/project/5ae1980f28546a5bbf985063/screen/5b1116a5d2155a4e2c9500fd

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1011930

**Comment by aelcenganda** [comment]
UI 不變，verified
