### ISSUE TITLE
Click About to open about page

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#96]
Click https://sensetw.productboard.com/feature-board/152244-feature-organization/features/1011930/detail to open https://sensetw.productboard.com/feature-board/152244-feature-organization/features/1011940/detail in new tab

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1011934

**Comment by aelcenganda** [comment]
VErified
