### ISSUE TITLE
Click logo to redirect to dashboard page

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#97]
Click "logo"  in https://sensetw.productboard.com/feature-board/152244-feature-organization/features/1011930/detail to open https://sensetw.productboard.com/feature-board/152244-feature-organization/features/992329/detail

**Comment by aelcenganda** [comment]
# UI 
1. https://app.zeplin.io/project/5ae1980f28546a5bbf985063/screen/5b1116a526d51037706b7e90
2. https://app.zeplin.io/project/5ae1980f28546a5bbf985063/screen/5b1116a5d2155a4e2c9500fd

**Comment by aelcenganda** [comment]
VErified
