### ISSUE TITLE
Create a Hypothesis group when a map is created automatically

### ISSUE THREAD

**Issue by hychen** [SenseTW/sensetw#98]
# Prerequisites

https://sensetw.productboard.com/feature-board/152248-progress-by-release/features/1049093/detail

# Success Criteria

* As title.

**Comment by hychen** [comment]
Link to feature: https://sensetw.productboard.com/feature-board/planning/features/1012075

**Comment by pm5** [comment]
Closed by 063c73389554942380331bd318000e5c20dae235
